<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationActionPrivate.h' l='28' u='w' c='_ZN23_WebKitNavigationActionC1EON3WTF3RefIN3API16NavigationActionENS0_12RawPtrTraitsIS3_EEEE'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationActionPrivate.h' l='33' u='w' c='_ZN23_WebKitNavigationActionC1EPS_'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationActionPrivate.h' l='33' u='r' c='_ZN23_WebKitNavigationActionC1EPS_'/>
<dec f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationActionPrivate.h' l='37' type='RefPtr&lt;API::NavigationAction&gt;'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.cpp' l='86' u='m' c='_Z44webkit_navigation_action_get_navigation_typeP23_WebKitNavigationAction'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.cpp' l='103' u='m' c='_Z41webkit_navigation_action_get_mouse_buttonP23_WebKitNavigationAction'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.cpp' l='120' u='m' c='_Z38webkit_navigation_action_get_modifiersP23_WebKitNavigationAction'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.cpp' l='159' u='m' c='_Z40webkit_navigation_action_is_user_gestureP23_WebKitNavigationAction'/>
<use f='WebKit/Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.cpp' l='175' u='m' c='_Z36webkit_navigation_action_is_redirectP23_WebKitNavigationAction'/>
