<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='110'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='111'/>
<def f='WebKit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='113' ll='141'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='115' c='_ZN5angle7FeatureC1ERKS0_'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/Feature.h' l='143' c='_ZN5angle7FeatureC1ERKS0_'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='26'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='34'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='42'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='48'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='54'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='60'/>
<use f='WebKit/Source/ThirdParty/ANGLE/include/platform/FrontendFeatures.h' l='65'/>
<size>48</size>
<fun r='_ZN5angle7FeatureC1ERKS0_'/>
<fun r='_ZN5angle7FeatureC1EPKcRKNS_15FeatureCategoryES2_PSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPS0_St4lessISC_ESaISt4pairIKSC_SD_EEES2_'/>
<fun r='_ZN5angle7FeatureD1Ev'/>
<mbr r='angle::Feature::name' o='0' t='const char *const'/>
<mbr r='angle::Feature::category' o='64' t='const angle::FeatureCategory'/>
<mbr r='angle::Feature::description' o='128' t='const char *const'/>
<mbr r='angle::Feature::bug' o='192' t='const char *const'/>
<mbr r='angle::Feature::enabled' o='256' t='bool'/>
<mbr r='angle::Feature::condition' o='320' t='const char *'/>
<fun r='_ZN5angle7FeatureC1ERKS0_'/>
<fun r='_ZN5angle7FeatureC1EPKcRKNS_15FeatureCategoryES2_PSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPS0_St4lessISC_ESaISt4pairIKSC_SD_EEES2_'/>
<fun r='_ZN5angle7FeatureD1Ev'/>
