<use f='WebKit/bmalloc/Headers/bmalloc/Scavenger.h' l='56' u='r' c='_ZN7bmalloc9Scavenger7willRunEv'/>
<dec f='WebKit/bmalloc/Headers/bmalloc/Scavenger.h' l='80' type='1'/>
<use f='WebKit/Source/bmalloc/bmalloc/Scavenger.h' l='56' u='r' c='_ZN7bmalloc9Scavenger7willRunEv'/>
<dec f='WebKit/Source/bmalloc/bmalloc/Scavenger.h' l='80' type='1'/>
<use f='WebKit/Source/bmalloc/bmalloc/Scavenger.cpp' l='101' u='r' c='_ZN7bmalloc9Scavenger3runERKSt11scoped_lockIJNS_5MutexEEE'/>
