<dec f='WebKit/bmalloc/Headers/bmalloc/IsoAllocator.h' l='35' type='0'/>
<use f='WebKit/bmalloc/Headers/bmalloc/IsoHeapImpl.h' l='92'/>
<use f='WebKit/bmalloc/Headers/bmalloc/IsoHeapImpl.h' l='92'/>
<use f='WebKit/bmalloc/Headers/bmalloc/IsoHeapImplInlines.h' l='286' c='_ZN7bmalloc11IsoHeapImpl20updateAllocationModeEv'/>
<dec f='WebKit/Source/bmalloc/bmalloc/IsoAllocator.h' l='35' type='0'/>
<use f='WebKit/Source/bmalloc/bmalloc/IsoHeapImpl.h' l='92'/>
<use f='WebKit/Source/bmalloc/bmalloc/IsoHeapImpl.h' l='92'/>
<use f='WebKit/Source/bmalloc/bmalloc/IsoHeapImplInlines.h' l='286' c='_ZN7bmalloc11IsoHeapImpl20updateAllocationModeEv'/>
