<dec f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.h' l='365' type='3'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedEnums.h' l='201'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1400' u='r' c='_ZN2gl10FromGLenumEj'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1416' c='_ZN2gl8ToGLenumENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='1437' c='_ZN2gllsERSoNS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/utilities.cpp' l='1091' c='_ZN2gl15GetPipelineTypeENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='124' u='r' c='_ZN2gl17ProgramExecutable21setLinkedShaderStagesENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='126' u='r' c='_ZN2gl17ProgramExecutable21setLinkedShaderStagesENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramExecutable.h' l='138' u='r' c='_ZNK2gl17ProgramExecutable20hasLinkedShaderStageENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='339' u='r' c='_ZNK2gl12ProgramState9isComputeEv'/>
