<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedEnums.h' l='590'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='157' c='_ZNK2gl20ShaderProgramManager9getShaderENS_15ShaderProgramIDE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='168' c='_ZNK2gl20ShaderProgramManager20getShadersForCaptureEv'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ResourceManager.h' l='185'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/ProgramLinkedResources.h' l='68' c='_ZN2gl13UniformLinker36flattenUniformsAndCheckCapsForShaderEPNS_6ShaderERKNS_4CapsERSt6vectorINS_13LinkedUniformESaIS7_EESA_SA_RS6_INS_13UnusedUniform15844351'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.h' l='113'/>
<inh f='WebKit/Source/ThirdParty/ANGLE/src/common/angleutils.h' l='43' c='angle::NonCopyable'/>
<inh f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Debug.h' l='25' c='gl::LabeledObject'/>
<def f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Shader.h' l='148' ll='260'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='211' c='_ZNK2gl12ProgramState17getAttachedShaderENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='212' c='_ZNK2gl12ProgramState18getAttachedShadersEv'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='393'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='481' c='_ZN2gl7Program12attachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='482' c='_ZN2gl7Program12detachShaderEPKNS_7ContextEPNS_6ShaderE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Program.h' l='485' c='_ZNK2gl7Program17getAttachedShaderENS_10ShaderTypeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/libANGLE/Context.h' l='564' c='_ZNK2gl7Context9getShaderENS_15ShaderProgramIDE'/>
<size>496</size>
<fun r='_ZN2gl6ShaderC1EPNS_20ShaderProgramManagerEPN2rx13GLImplFactoryERKNS_11LimitationsENS_10ShaderTypeENS_15ShaderProgramIDE'/>
<fun r='_ZN2gl6Shader9onDestroyEPKNS_7ContextE'/>
<fun r='_ZN2gl6Shader8setLabelEPKNS_7ContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZNK2gl6Shader8getLabelB5cxx11Ev'/>
<fun r='_ZNK2gl6Shader7getTypeEv'/>
<fun r='_ZNK2gl6Shader9getHandleEv'/>
<fun r='_ZNK2gl6Shader17getImplementationEv'/>
<fun r='_ZN2gl6Shader9setSourceEiPKPKcPKi'/>
<fun r='_ZN2gl6Shader16getInfoLogLengthEv'/>
<fun r='_ZN2gl6Shader10getInfoLogEiPiPc'/>
<fun r='_ZNK2gl6Shader16getInfoLogStringB5cxx11Ev'/>
<fun r='_ZNK2gl6Shader15getSourceLengthEv'/>
<fun r='_ZNK2gl6Shader15getSourceStringB5cxx11Ev'/>
<fun r='_ZNK2gl6Shader9getSourceEiPiPc'/>
<fun r='_ZN2gl6Shader25getTranslatedSourceLengthEv'/>
<fun r='_ZN2gl6Shader38getTranslatedSourceWithDebugInfoLengthEv'/>
<fun r='_ZN2gl6Shader19getTranslatedSourceB5cxx11Ev'/>
<fun r='_ZN2gl6Shader19getTranslatedSourceEiPiPc'/>
<fun r='_ZN2gl6Shader32getTranslatedSourceWithDebugInfoEiPiPc'/>
<fun r='_ZN2gl6Shader7compileEPKNS_7ContextE'/>
<fun r='_ZN2gl6Shader10isCompiledEv'/>
<fun r='_ZN2gl6Shader11isCompletedEv'/>
<fun r='_ZN2gl6Shader6addRefEv'/>
<fun r='_ZN2gl6Shader7releaseEPKNS_7ContextE'/>
<fun r='_ZNK2gl6Shader11getRefCountEv'/>
<fun r='_ZNK2gl6Shader20isFlaggedForDeletionEv'/>
<fun r='_ZN2gl6Shader15flagForDeletionEv'/>
<fun r='_ZNK2gl6Shader33hasEarlyFragmentTestsOptimizationEv'/>
<fun r='_ZN2gl6Shader16getShaderVersionEv'/>
<fun r='_ZN2gl6Shader16getInputVaryingsEv'/>
<fun r='_ZN2gl6Shader17getOutputVaryingsEv'/>
<fun r='_ZN2gl6Shader11getUniformsEv'/>
<fun r='_ZN2gl6Shader16getUniformBlocksEv'/>
<fun r='_ZN2gl6Shader22getShaderStorageBlocksEv'/>
<fun r='_ZN2gl6Shader19getActiveAttributesEv'/>
<fun r='_ZN2gl6Shader16getAllAttributesEv'/>
<fun r='_ZN2gl6Shader24getActiveOutputVariablesEv'/>
<fun r='_ZN2gl6Shader37getTransformFeedbackVaryingMappedNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN2gl6Shader16getWorkGroupSizeEv'/>
<fun r='_ZN2gl6Shader11getNumViewsEv'/>
<fun r='_ZN2gl6Shader35getGeometryShaderInputPrimitiveTypeEv'/>
<fun r='_ZN2gl6Shader36getGeometryShaderOutputPrimitiveTypeEv'/>
<fun r='_ZN2gl6Shader28getGeometryShaderInvocationsEv'/>
<fun r='_ZN2gl6Shader28getGeometryShaderMaxVerticesEv'/>
<fun r='_ZNK2gl6Shader26getCompilerResourcesStringB5cxx11Ev'/>
<fun r='_ZNK2gl6Shader8getStateEv'/>
<fun r='_ZNK2gl6Shader40getCurrentMaxComputeWorkGroupInvocationsEv'/>
<fun r='_ZNK2gl6Shader25getMaxComputeSharedMemoryEv'/>
<fun r='_ZNK2gl6Shader14hasBeenDeletedEv'/>
<fun r='_ZN2gl6ShaderD1Ev'/>
<fun r='_ZN2gl6Shader13GetSourceImplERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiPiPc'/>
<fun r='_ZN2gl6Shader14resolveCompileEv'/>
<mbr r='gl::Shader::mState' o='64' t='gl::ShaderState'/>
<mbr r='gl::Shader::mImplementation' o='2816' t='std::unique_ptr&lt;rx::ShaderImpl&gt;'/>
<mbr r='gl::Shader::mRendererLimitations' o='2880' t='const gl::Limitations'/>
<mbr r='gl::Shader::mHandle' o='2976' t='const gl::ShaderProgramID'/>
<mbr r='gl::Shader::mType' o='3008' t='const gl::ShaderType'/>
<mbr r='gl::Shader::mRefCount' o='3040' t='unsigned int'/>
<mbr r='gl::Shader::mDeleteStatus' o='3072' t='bool'/>
<mbr r='gl::Shader::mInfoLog' o='3136' t='std::string'/>
<mbr r='gl::Shader::mBoundCompiler' o='3392' t='BindingPointer&lt;gl::Compiler&gt;'/>
<mbr r='gl::Shader::mCompilingState' o='3520' t='std::unique_ptr&lt;CompilingState&gt;'/>
<mbr r='gl::Shader::mCompilerResourcesString' o='3584' t='std::string'/>
<mbr r='gl::Shader::mResourceManager' o='3840' t='gl::ShaderProgramManager *'/>
<mbr r='gl::Shader::mCurrentMaxComputeWorkGroupInvocations' o='3904' t='GLuint'/>
<mbr r='gl::Shader::mMaxComputeSharedMemory' o='3936' t='unsigned int'/>
