<dec f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.h' l='145' type='0'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='511' u='r' c='_ZN2gl10FromGLenumEj'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='525' c='_ZN2gl8ToGLenumENS_7FogModeE'/>
<use f='WebKit/Source/ThirdParty/ANGLE/src/common/PackedGLEnums_autogen.cpp' l='541' c='_ZN2gllsERSoNS_7FogModeE'/>
