<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7989' ll='8078'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7993' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7995' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8006' c='_ZN9Inspector8Protocol4Page6Cookie7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8013' c='_ZN9Inspector8Protocol4Page6Cookie7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8020' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8027' c='_ZN9Inspector8Protocol4Page6Cookie7Builder7setPathERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8034' c='_ZN9Inspector8Protocol4Page6Cookie7Builder10setExpiresEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8041' c='_ZN9Inspector8Protocol4Page6Cookie7Builder10setSessionEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8048' c='_ZN9Inspector8Protocol4Page6Cookie7Builder11setHttpOnlyEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8055' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9setSecureEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8062' c='_ZN9Inspector8Protocol4Page6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8094' c='_ZN9Inspector8Protocol4Page6Cookie6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8096' c='_ZN9Inspector8Protocol4Page6Cookie6createEv'/>
<mbr r='Inspector::Protocol::Page::Cookie::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7setPathERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder10setExpiresEd'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder10setSessionEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder11setHttpOnlyEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9setSecureEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7989' ll='8078'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7993' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7995' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8006' c='_ZN9Inspector8Protocol4Page6Cookie7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8013' c='_ZN9Inspector8Protocol4Page6Cookie7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8020' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8027' c='_ZN9Inspector8Protocol4Page6Cookie7Builder7setPathERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8034' c='_ZN9Inspector8Protocol4Page6Cookie7Builder10setExpiresEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8041' c='_ZN9Inspector8Protocol4Page6Cookie7Builder10setSessionEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8048' c='_ZN9Inspector8Protocol4Page6Cookie7Builder11setHttpOnlyEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8055' c='_ZN9Inspector8Protocol4Page6Cookie7Builder9setSecureEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8062' c='_ZN9Inspector8Protocol4Page6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8094' c='_ZN9Inspector8Protocol4Page6Cookie6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8096' c='_ZN9Inspector8Protocol4Page6Cookie6createEv'/>
<mbr r='Inspector::Protocol::Page::Cookie::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9setDomainERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7setPathERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder10setExpiresEd'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder10setSessionEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder11setHttpOnlyEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder9setSecureEb'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder11setSameSiteENS1_20CookieSameSitePolicyE'/>
<fun r='_ZN9Inspector8Protocol4Page6Cookie7Builder7releaseEv'/>
