<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7236' ll='7283'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7240' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7242' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7253' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7260' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder13setStatusTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7267' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7293' c='_ZN9Inspector8Protocol7Network17WebSocketResponse6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7295' c='_ZN9Inspector8Protocol7Network17WebSocketResponse6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketResponse::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder13setStatusTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7236' ll='7283'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7240' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7242' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7253' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7260' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder13setStatusTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7267' c='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7293' c='_ZN9Inspector8Protocol7Network17WebSocketResponse6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7295' c='_ZN9Inspector8Protocol7Network17WebSocketResponse6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketResponse::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder13setStatusTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network17WebSocketResponse7Builder7releaseEv'/>
