<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4454' ll='4508'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4458' c='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4460' c='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4471' c='_ZN9Inspector8Protocol8Database8Database7Builder5setIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4478' c='_ZN9Inspector8Protocol8Database8Database7Builder9setDomainERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4485' c='_ZN9Inspector8Protocol8Database8Database7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4492' c='_ZN9Inspector8Protocol8Database8Database7Builder10setVersionERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4519' c='_ZN9Inspector8Protocol8Database8Database6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4521' c='_ZN9Inspector8Protocol8Database8Database6createEv'/>
<mbr r='Inspector::Protocol::Database::Database::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder5setIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder9setDomainERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder10setVersionERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4454' ll='4508'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4458' c='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4460' c='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4471' c='_ZN9Inspector8Protocol8Database8Database7Builder5setIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4478' c='_ZN9Inspector8Protocol8Database8Database7Builder9setDomainERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4485' c='_ZN9Inspector8Protocol8Database8Database7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4492' c='_ZN9Inspector8Protocol8Database8Database7Builder10setVersionERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4519' c='_ZN9Inspector8Protocol8Database8Database6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4521' c='_ZN9Inspector8Protocol8Database8Database6createEv'/>
<mbr r='Inspector::Protocol::Database::Database::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder5setIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder9setDomainERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder10setVersionERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Database8Database7Builder7releaseEv'/>
