<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7737' ll='7784'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7741' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7743' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7754' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7761' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder7setTypeENS1_12ResourceTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7768' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7794' c='_ZN9Inspector8Protocol4Page13FrameResource6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7796' c='_ZN9Inspector8Protocol4Page13FrameResource6createEv'/>
<mbr r='Inspector::Protocol::Page::FrameResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder7setTypeENS1_12ResourceTypeE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7737' ll='7784'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7741' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7743' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7754' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7761' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder7setTypeENS1_12ResourceTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7768' c='_ZN9Inspector8Protocol4Page13FrameResource7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7794' c='_ZN9Inspector8Protocol4Page13FrameResource6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7796' c='_ZN9Inspector8Protocol4Page13FrameResource6createEv'/>
<mbr r='Inspector::Protocol::Page::FrameResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder7setTypeENS1_12ResourceTypeE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page13FrameResource7Builder7releaseEv'/>
