<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3439' ll='3472'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3443' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3445' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3456' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder13setCallFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9CallFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3480' c='_ZN9Inspector8Protocol7Console10StackTrace6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3482' c='_ZN9Inspector8Protocol7Console10StackTrace6createEv'/>
<mbr r='Inspector::Protocol::Console::StackTrace::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder13setCallFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9CallFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3439' ll='3472'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3443' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3445' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3456' c='_ZN9Inspector8Protocol7Console10StackTrace7Builder13setCallFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9CallFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3480' c='_ZN9Inspector8Protocol7Console10StackTrace6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3482' c='_ZN9Inspector8Protocol7Console10StackTrace6createEv'/>
<mbr r='Inspector::Protocol::Console::StackTrace::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder13setCallFramesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9CallFrameEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Console10StackTrace7Builder7releaseEv'/>
