<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6856' ll='6903'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6860' c='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6862' c='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6873' c='_ZN9Inspector8Protocol7Network7Request7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6880' c='_ZN9Inspector8Protocol7Network7Request7Builder9setMethodERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6887' c='_ZN9Inspector8Protocol7Network7Request7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6913' c='_ZN9Inspector8Protocol7Network7Request6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6915' c='_ZN9Inspector8Protocol7Network7Request6createEv'/>
<mbr r='Inspector::Protocol::Network::Request::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder9setMethodERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6856' ll='6903'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6860' c='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6862' c='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6873' c='_ZN9Inspector8Protocol7Network7Request7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6880' c='_ZN9Inspector8Protocol7Network7Request7Builder9setMethodERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6887' c='_ZN9Inspector8Protocol7Network7Request7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6913' c='_ZN9Inspector8Protocol7Network7Request6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6915' c='_ZN9Inspector8Protocol7Network7Request6createEv'/>
<mbr r='Inspector::Protocol::Network::Request::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder9setMethodERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Request7Builder7releaseEv'/>
