<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4273' ll='4299'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4277' c='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4279' c='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4306' c='_ZN9Inspector8Protocol3DOM15HighlightConfig6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4308' c='_ZN9Inspector8Protocol3DOM15HighlightConfig6createEv'/>
<mbr r='Inspector::Protocol::DOM::HighlightConfig::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4273' ll='4299'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4277' c='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4279' c='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4306' c='_ZN9Inspector8Protocol3DOM15HighlightConfig6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4308' c='_ZN9Inspector8Protocol3DOM15HighlightConfig6createEv'/>
<mbr r='Inspector::Protocol::DOM::HighlightConfig::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM15HighlightConfig7Builder7releaseEv'/>
