<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1717' ll='1757'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1721' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1723' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1734' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1741' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1766' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1768' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleAttribute::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1717' ll='1757'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1721' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1723' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1734' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1741' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1766' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1768' c='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleAttribute::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17CSSStyleAttribute7Builder7releaseEv'/>
