<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3810' ll='3864'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3814' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3816' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3827' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder18setEventListenerIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3834' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder7setTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3841' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder13setUseCaptureEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3848' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder14setIsAttributeEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3875' c='_ZN9Inspector8Protocol3DOM13EventListener6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3877' c='_ZN9Inspector8Protocol3DOM13EventListener6createEv'/>
<mbr r='Inspector::Protocol::DOM::EventListener::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder18setEventListenerIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder7setTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder13setUseCaptureEb'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder14setIsAttributeEb'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3810' ll='3864'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3814' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3816' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3827' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder18setEventListenerIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3834' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder7setTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3841' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder13setUseCaptureEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3848' c='_ZN9Inspector8Protocol3DOM13EventListener7Builder14setIsAttributeEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3875' c='_ZN9Inspector8Protocol3DOM13EventListener6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3877' c='_ZN9Inspector8Protocol3DOM13EventListener6createEv'/>
<mbr r='Inspector::Protocol::DOM::EventListener::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder18setEventListenerIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder7setTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder13setUseCaptureEb'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder14setIsAttributeEb'/>
<fun r='_ZN9Inspector8Protocol3DOM13EventListener7Builder7releaseEv'/>
