<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4841' ll='4874'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4845' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4847' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4858' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4882' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4884' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails6createEv'/>
<mbr r='Inspector::Protocol::Debugger::FunctionDetails::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4841' ll='4874'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4845' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4847' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4858' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4882' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4884' c='_ZN9Inspector8Protocol8Debugger15FunctionDetails6createEv'/>
<mbr r='Inspector::Protocol::Debugger::FunctionDetails::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger15FunctionDetails7Builder7releaseEv'/>
