<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9618' ll='9672'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9622' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9624' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9635' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setStartOffsetEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9642' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder12setEndOffsetEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9649' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setHasExecutedEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9656' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder17setExecutionCountEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9683' c='_ZN9Inspector8Protocol7Runtime10BasicBlock6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9685' c='_ZN9Inspector8Protocol7Runtime10BasicBlock6createEv'/>
<mbr r='Inspector::Protocol::Runtime::BasicBlock::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setStartOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder12setEndOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setHasExecutedEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder17setExecutionCountEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9618' ll='9672'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9622' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9624' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9635' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setStartOffsetEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9642' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder12setEndOffsetEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9649' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setHasExecutedEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9656' c='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder17setExecutionCountEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9683' c='_ZN9Inspector8Protocol7Runtime10BasicBlock6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9685' c='_ZN9Inspector8Protocol7Runtime10BasicBlock6createEv'/>
<mbr r='Inspector::Protocol::Runtime::BasicBlock::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setStartOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder12setEndOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder14setHasExecutedEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder17setExecutionCountEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10BasicBlock7Builder7releaseEv'/>
