<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8207' ll='8240'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8211' c='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8213' c='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8224' c='_ZN9Inspector8Protocol9Recording5Frame7Builder10setActionsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8248' c='_ZN9Inspector8Protocol9Recording5Frame6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8250' c='_ZN9Inspector8Protocol9Recording5Frame6createEv'/>
<mbr r='Inspector::Protocol::Recording::Frame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder10setActionsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8207' ll='8240'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8211' c='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8213' c='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8224' c='_ZN9Inspector8Protocol9Recording5Frame7Builder10setActionsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8248' c='_ZN9Inspector8Protocol9Recording5Frame6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8250' c='_ZN9Inspector8Protocol9Recording5Frame6createEv'/>
<mbr r='Inspector::Protocol::Recording::Frame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder10setActionsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording5Frame7Builder7releaseEv'/>
