<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5528' ll='5575'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5532' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5534' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5545' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5552' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder10setVersionEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5559' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder15setObjectStoresEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11ObjectStoreEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5585' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5587' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::DatabaseWithObjectStores::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder10setVersionEd'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder15setObjectStoresEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11ObjectStoreEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5528' ll='5575'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5532' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5534' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5545' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5552' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder10setVersionEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5559' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder15setObjectStoresEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11ObjectStoreEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5585' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5587' c='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::DatabaseWithObjectStores::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder10setVersionEd'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder15setObjectStoresEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11ObjectStoreEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB24DatabaseWithObjectStores7Builder7releaseEv'/>
