<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6311' ll='6337'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6315' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6317' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6344' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6346' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::CompositingReasons::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6311' ll='6337'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6315' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6317' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6344' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6346' c='_ZN9Inspector8Protocol9LayerTree18CompositingReasons6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::CompositingReasons::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree18CompositingReasons7Builder7releaseEv'/>
