<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10069' ll='10095'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10073' c='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10075' c='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10102' c='_ZN9Inspector8Protocol8Security10Connection6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10104' c='_ZN9Inspector8Protocol8Security10Connection6createEv'/>
<mbr r='Inspector::Protocol::Security::Connection::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10069' ll='10095'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10073' c='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10075' c='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10102' c='_ZN9Inspector8Protocol8Security10Connection6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10104' c='_ZN9Inspector8Protocol8Security10Connection6createEv'/>
<mbr r='Inspector::Protocol::Security::Connection::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security10Connection7Builder7releaseEv'/>
