<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4766' ll='4792'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4770' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4772' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4799' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4801' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointOptions::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4766' ll='4792'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4770' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4772' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4799' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4801' c='_ZN9Inspector8Protocol8Debugger17BreakpointOptions6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointOptions::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger17BreakpointOptions7Builder7releaseEv'/>
