<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10267' ll='10321'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10271' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10273' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10284' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder11setTargetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10291' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10298' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10305' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder10setContentERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10332' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10334' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration6createEv'/>
<mbr r='Inspector::Protocol::ServiceWorker::Configuration::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder11setTargetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder10setContentERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10267' ll='10321'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10271' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10273' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10284' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder11setTargetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10291' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10298' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10305' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder10setContentERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10332' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10334' c='_ZN9Inspector8Protocol13ServiceWorker13Configuration6createEv'/>
<mbr r='Inspector::Protocol::ServiceWorker::Configuration::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder11setTargetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder10setContentERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol13ServiceWorker13Configuration7Builder7releaseEv'/>
