<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1301' ll='1341'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1305' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1307' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1318' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1325' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder10setOrdinalEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1350' c='_ZN9Inspector8Protocol3CSS9CSSRuleId6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1352' c='_ZN9Inspector8Protocol3CSS9CSSRuleId6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSRuleId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder10setOrdinalEi'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1301' ll='1341'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1305' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1307' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1318' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1325' c='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder10setOrdinalEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1350' c='_ZN9Inspector8Protocol3CSS9CSSRuleId6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1352' c='_ZN9Inspector8Protocol3CSS9CSSRuleId6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSRuleId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder10setOrdinalEi'/>
<fun r='_ZN9Inspector8Protocol3CSS9CSSRuleId7Builder7releaseEv'/>
