<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4918' ll='4986'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4922' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4924' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4935' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder14setCallFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4942' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4949' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4956' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder13setScopeChainEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_5ScopeEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4963' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7setThisEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4970' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder16setIsTailDeletedEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4999' c='_ZN9Inspector8Protocol8Debugger9CallFrame6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5001' c='_ZN9Inspector8Protocol8Debugger9CallFrame6createEv'/>
<mbr r='Inspector::Protocol::Debugger::CallFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder14setCallFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder13setScopeChainEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_5ScopeEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7setThisEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder16setIsTailDeletedEb'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4918' ll='4986'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4922' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4924' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4935' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder14setCallFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4942' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4949' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4956' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder13setScopeChainEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_5ScopeEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4963' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7setThisEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4970' c='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder16setIsTailDeletedEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4999' c='_ZN9Inspector8Protocol8Debugger9CallFrame6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5001' c='_ZN9Inspector8Protocol8Debugger9CallFrame6createEv'/>
<mbr r='Inspector::Protocol::Debugger::CallFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder14setCallFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder15setFunctionNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder11setLocationEON3WTF3RefINS1_8LocationENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder13setScopeChainEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_5ScopeEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7setThisEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder16setIsTailDeletedEb'/>
<fun r='_ZN9Inspector8Protocol8Debugger9CallFrame7Builder7releaseEv'/>
