<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3737' ll='3777'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3741' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3743' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3754' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder10setBindingERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3761' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3786' c='_ZN9Inspector8Protocol3DOM11DataBinding6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3788' c='_ZN9Inspector8Protocol3DOM11DataBinding6createEv'/>
<mbr r='Inspector::Protocol::DOM::DataBinding::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder10setBindingERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3737' ll='3777'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3741' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3743' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3754' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder10setBindingERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3761' c='_ZN9Inspector8Protocol3DOM11DataBinding7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3786' c='_ZN9Inspector8Protocol3DOM11DataBinding6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3788' c='_ZN9Inspector8Protocol3DOM11DataBinding6createEv'/>
<mbr r='Inspector::Protocol::DOM::DataBinding::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder10setBindingERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM11DataBinding7Builder7releaseEv'/>
