<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5449' ll='5496'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5453' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5455' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5466' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5473' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder12setStartTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5480' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder10setEndTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5506' c='_ZN9Inspector8Protocol4Heap17GarbageCollection6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5508' c='_ZN9Inspector8Protocol4Heap17GarbageCollection6createEv'/>
<mbr r='Inspector::Protocol::Heap::GarbageCollection::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder12setStartTimeEd'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder10setEndTimeEd'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5449' ll='5496'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5453' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5455' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5466' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5473' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder12setStartTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5480' c='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder10setEndTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5506' c='_ZN9Inspector8Protocol4Heap17GarbageCollection6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5508' c='_ZN9Inspector8Protocol4Heap17GarbageCollection6createEv'/>
<mbr r='Inspector::Protocol::Heap::GarbageCollection::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder12setStartTimeEd'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder10setEndTimeEd'/>
<fun r='_ZN9Inspector8Protocol4Heap17GarbageCollection7Builder7releaseEv'/>
