<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7831' ll='7871'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7835' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7837' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7848' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder8setFrameEON3WTF3RefINS1_5FrameENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7855' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_13FrameResourceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7880' c='_ZN9Inspector8Protocol4Page17FrameResourceTree6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7882' c='_ZN9Inspector8Protocol4Page17FrameResourceTree6createEv'/>
<mbr r='Inspector::Protocol::Page::FrameResourceTree::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder8setFrameEON3WTF3RefINS1_5FrameENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_13FrameResourceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7831' ll='7871'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7835' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7837' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7848' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder8setFrameEON3WTF3RefINS1_5FrameENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7855' c='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_13FrameResourceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7880' c='_ZN9Inspector8Protocol4Page17FrameResourceTree6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7882' c='_ZN9Inspector8Protocol4Page17FrameResourceTree6createEv'/>
<mbr r='Inspector::Protocol::Page::FrameResourceTree::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder8setFrameEON3WTF3RefINS1_5FrameENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_13FrameResourceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page17FrameResourceTree7Builder7releaseEv'/>
