<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/RemoteControllableTarget.h' l='60' type='2'/>
<dec f='WebKit/Source/JavaScriptCore/inspector/remote/RemoteControllableTarget.h' l='60' type='2'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGlobalObjectDebuggable.h' l='64'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGlobalObjectDebuggable.h' l='64'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGlobalObjectDebuggable.h' l='72' u='r' c='_ZN3WTF14TypeCastTraitsIKN3JSC24JSGlobalObjectDebuggableET_Lb0EE6isTypeERKN9Inspector24RemoteControllableTargetE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorGlib.cpp' l='156' c='_ZN9InspectorL20targetDebuggableTypeENS_24RemoteControllableTarget4TypeE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorGlib.cpp' l='176' u='r' c='_ZNK9Inspector15RemoteInspector26listingForInspectionTargetERKNS_22RemoteInspectionTargetE'/>
