<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5604' ll='5658'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5608' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5610' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5621' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5628' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5635' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder16setAutoIncrementEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5642' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setIndexesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_16ObjectStoreIndexEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5669' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5671' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::ObjectStore::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder16setAutoIncrementEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setIndexesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_16ObjectStoreIndexEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5604' ll='5658'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5608' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5610' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5621' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5628' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5635' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder16setAutoIncrementEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5642' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setIndexesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_16ObjectStoreIndexEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5669' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5671' c='_ZN9Inspector8Protocol9IndexedDB11ObjectStore6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::ObjectStore::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder16setAutoIncrementEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder10setIndexesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_16ObjectStoreIndexEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB11ObjectStore7Builder7releaseEv'/>
