<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5199' ll='5225'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5203' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5205' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5232' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5234' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::AssertPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5199' ll='5225'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5203' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5205' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5232' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5234' c='_ZN9Inspector8Protocol8Debugger17AssertPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::AssertPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger17AssertPauseReason7Builder7releaseEv'/>
