<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10361' ll='10401'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10365' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10367' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10378' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder11setTargetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10385' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10410' c='_ZN9Inspector8Protocol6Target10TargetInfo6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10412' c='_ZN9Inspector8Protocol6Target10TargetInfo6createEv'/>
<mbr r='Inspector::Protocol::Target::TargetInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder11setTargetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10361' ll='10401'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10365' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10367' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10378' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder11setTargetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10385' c='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10410' c='_ZN9Inspector8Protocol6Target10TargetInfo6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10412' c='_ZN9Inspector8Protocol6Target10TargetInfo6createEv'/>
<mbr r='Inspector::Protocol::Target::TargetInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder11setTargetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol6Target10TargetInfo7Builder7releaseEv'/>
