<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10200' ll='10226'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10204' c='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10206' c='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10233' c='_ZN9Inspector8Protocol8Security8Security6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10235' c='_ZN9Inspector8Protocol8Security8Security6createEv'/>
<mbr r='Inspector::Protocol::Security::Security::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10200' ll='10226'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10204' c='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10206' c='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10233' c='_ZN9Inspector8Protocol8Security8Security6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10235' c='_ZN9Inspector8Protocol8Security8Security6createEv'/>
<mbr r='Inspector::Protocol::Security::Security::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Security8Security7Builder7releaseEv'/>
