<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5945' ll='5992'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5949' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5951' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5962' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder6setKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5969' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder13setPrimaryKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5976' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder8setValueEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6002' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6004' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::DataEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder6setKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder13setPrimaryKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder8setValueEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5945' ll='5992'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5949' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5951' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5962' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder6setKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5969' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder13setPrimaryKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5976' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder8setValueEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6002' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6004' c='_ZN9Inspector8Protocol9IndexedDB9DataEntry6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::DataEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder6setKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder13setPrimaryKeyEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder8setValueEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB9DataEntry7Builder7releaseEv'/>
