<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2934' ll='2974'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2938' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2940' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2951' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder11setCanvasIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2958' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder14setContextTypeENS1_11ContextTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2983' c='_ZN9Inspector8Protocol6Canvas6Canvas6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2985' c='_ZN9Inspector8Protocol6Canvas6Canvas6createEv'/>
<mbr r='Inspector::Protocol::Canvas::Canvas::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder11setCanvasIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder14setContextTypeENS1_11ContextTypeE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2934' ll='2974'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2938' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2940' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2951' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder11setCanvasIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2958' c='_ZN9Inspector8Protocol6Canvas6Canvas7Builder14setContextTypeENS1_11ContextTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2983' c='_ZN9Inspector8Protocol6Canvas6Canvas6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2985' c='_ZN9Inspector8Protocol6Canvas6Canvas6createEv'/>
<mbr r='Inspector::Protocol::Canvas::Canvas::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder11setCanvasIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder14setContextTypeENS1_11ContextTypeE'/>
<fun r='_ZN9Inspector8Protocol6Canvas6Canvas7Builder7releaseEv'/>
