<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='507' ll='533'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='511' c='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='513' c='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='540' c='_ZN9Inspector8Protocol9Animation6Effect6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='542' c='_ZN9Inspector8Protocol9Animation6Effect6createEv'/>
<mbr r='Inspector::Protocol::Animation::Effect::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='507' ll='533'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='511' c='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='513' c='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='540' c='_ZN9Inspector8Protocol9Animation6Effect6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='542' c='_ZN9Inspector8Protocol9Animation6Effect6createEv'/>
<mbr r='Inspector::Protocol::Animation::Effect::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation6Effect7Builder7releaseEv'/>
