<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1385' ll='1425'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1389' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1391' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1402' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder11setPseudoIdENS1_8PseudoIdE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1409' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder10setMatchesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1434' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1436' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches6createEv'/>
<mbr r='Inspector::Protocol::CSS::PseudoIdMatches::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder11setPseudoIdENS1_8PseudoIdE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder10setMatchesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1385' ll='1425'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1389' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1391' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1402' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder11setPseudoIdENS1_8PseudoIdE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1409' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder10setMatchesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1434' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1436' c='_ZN9Inspector8Protocol3CSS15PseudoIdMatches6createEv'/>
<mbr r='Inspector::Protocol::CSS::PseudoIdMatches::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder11setPseudoIdENS1_8PseudoIdE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder10setMatchesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS15PseudoIdMatches7Builder7releaseEv'/>
