<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2652' ll='2692'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2656' c='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2658' c='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2669' c='_ZN9Inspector8Protocol3CSS4Font7Builder14setDisplayNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2676' c='_ZN9Inspector8Protocol3CSS4Font7Builder16setVariationAxesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_17FontVariationAxisEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2701' c='_ZN9Inspector8Protocol3CSS4Font6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2703' c='_ZN9Inspector8Protocol3CSS4Font6createEv'/>
<mbr r='Inspector::Protocol::CSS::Font::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder14setDisplayNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder16setVariationAxesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_17FontVariationAxisEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2652' ll='2692'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2656' c='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2658' c='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2669' c='_ZN9Inspector8Protocol3CSS4Font7Builder14setDisplayNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2676' c='_ZN9Inspector8Protocol3CSS4Font7Builder16setVariationAxesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_17FontVariationAxisEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2701' c='_ZN9Inspector8Protocol3CSS4Font6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2703' c='_ZN9Inspector8Protocol3CSS4Font6createEv'/>
<mbr r='Inspector::Protocol::CSS::Font::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder14setDisplayNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder16setVariationAxesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_17FontVariationAxisEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS4Font7Builder7releaseEv'/>
