<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6505' ll='6545'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6509' c='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6511' c='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6522' c='_ZN9Inspector8Protocol6Memory5Event7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6529' c='_ZN9Inspector8Protocol6Memory5Event7Builder13setCategoriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_12CategoryDataEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6554' c='_ZN9Inspector8Protocol6Memory5Event6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6556' c='_ZN9Inspector8Protocol6Memory5Event6createEv'/>
<mbr r='Inspector::Protocol::Memory::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder13setCategoriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_12CategoryDataEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6505' ll='6545'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6509' c='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6511' c='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6522' c='_ZN9Inspector8Protocol6Memory5Event7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6529' c='_ZN9Inspector8Protocol6Memory5Event7Builder13setCategoriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_12CategoryDataEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6554' c='_ZN9Inspector8Protocol6Memory5Event6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6556' c='_ZN9Inspector8Protocol6Memory5Event6createEv'/>
<mbr r='Inspector::Protocol::Memory::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder13setCategoriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_12CategoryDataEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol6Memory5Event7Builder7releaseEv'/>
