<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8961' ll='8994'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8965' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8967' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8978' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9002' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9004' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor6createEv'/>
<mbr r='Inspector::Protocol::Runtime::InternalPropertyDescriptor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8961' ll='8994'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8965' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8967' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8978' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9002' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9004' c='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor6createEv'/>
<mbr r='Inspector::Protocol::Runtime::InternalPropertyDescriptor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime26InternalPropertyDescriptor7Builder7releaseEv'/>
