<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10009' ll='10042'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10013' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10015' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10026' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder14setStackTracesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackTraceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10050' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10052' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::Samples::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder14setStackTracesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackTraceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10009' ll='10042'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10013' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10015' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10026' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder14setStackTracesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackTraceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10050' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10052' c='_ZN9Inspector8Protocol14ScriptProfiler7Samples6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::Samples::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder14setStackTracesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_10StackTraceEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler7Samples7Builder7releaseEv'/>
