<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1151' ll='1191'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1155' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1157' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1168' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1175' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder8setUsageEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1200' c='_ZN9Inspector8Protocol11CPUProfiler5Event6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1202' c='_ZN9Inspector8Protocol11CPUProfiler5Event6createEv'/>
<mbr r='Inspector::Protocol::CPUProfiler::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder8setUsageEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1151' ll='1191'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1155' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1157' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1168' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1175' c='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder8setUsageEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1200' c='_ZN9Inspector8Protocol11CPUProfiler5Event6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1202' c='_ZN9Inspector8Protocol11CPUProfiler5Event6createEv'/>
<mbr r='Inspector::Protocol::CPUProfiler::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder8setUsageEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler5Event7Builder7releaseEv'/>
