<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4378' ll='4418'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4382' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4384' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4395' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4402' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setIsLocalStorageEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4427' c='_ZN9Inspector8Protocol10DOMStorage9StorageId6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4429' c='_ZN9Inspector8Protocol10DOMStorage9StorageId6createEv'/>
<mbr r='Inspector::Protocol::DOMStorage::StorageId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setIsLocalStorageEb'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4378' ll='4418'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4382' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4384' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4395' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4402' c='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setIsLocalStorageEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4427' c='_ZN9Inspector8Protocol10DOMStorage9StorageId6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4429' c='_ZN9Inspector8Protocol10DOMStorage9StorageId6createEv'/>
<mbr r='Inspector::Protocol::DOMStorage::StorageId::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder17setIsLocalStorageEb'/>
<fun r='_ZN9Inspector8Protocol10DOMStorage9StorageId7Builder7releaseEv'/>
