<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7395' ll='7442'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7399' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7401' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7412' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7419' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder7setTypeENS0_4Page12ResourceTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7426' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder11setBodySizeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7452' c='_ZN9Inspector8Protocol7Network14CachedResource6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7454' c='_ZN9Inspector8Protocol7Network14CachedResource6createEv'/>
<mbr r='Inspector::Protocol::Network::CachedResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder7setTypeENS0_4Page12ResourceTypeE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder11setBodySizeEd'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7395' ll='7442'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7399' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7401' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7412' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7419' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder7setTypeENS0_4Page12ResourceTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7426' c='_ZN9Inspector8Protocol7Network14CachedResource7Builder11setBodySizeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7452' c='_ZN9Inspector8Protocol7Network14CachedResource6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7454' c='_ZN9Inspector8Protocol7Network14CachedResource6createEv'/>
<mbr r='Inspector::Protocol::Network::CachedResource::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder7setTypeENS0_4Page12ResourceTypeE'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder11setBodySizeEd'/>
<fun r='_ZN9Inspector8Protocol7Network14CachedResource7Builder7releaseEv'/>
