<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8792' ll='8825'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8796' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8798' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8809' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder8setValueEON3WTF3RefINS1_12RemoteObjectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8833' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8835' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry6createEv'/>
<mbr r='Inspector::Protocol::Runtime::CollectionEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder8setValueEON3WTF3RefINS1_12RemoteObjectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8792' ll='8825'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8796' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8798' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8809' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder8setValueEON3WTF3RefINS1_12RemoteObjectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8833' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8835' c='_ZN9Inspector8Protocol7Runtime15CollectionEntry6createEv'/>
<mbr r='Inspector::Protocol::Runtime::CollectionEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder8setValueEON3WTF3RefINS1_12RemoteObjectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15CollectionEntry7Builder7releaseEv'/>
