<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5688' ll='5742'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5692' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5694' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5705' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5712' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5719' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9setUniqueEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5726' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder13setMultiEntryEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5753' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5755' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::ObjectStoreIndex::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9setUniqueEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder13setMultiEntryEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5688' ll='5742'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5692' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5694' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5705' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5712' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5719' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9setUniqueEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5726' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder13setMultiEntryEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5753' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5755' c='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::ObjectStoreIndex::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder10setKeyPathEON3WTF3RefINS1_7KeyPathENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder9setUniqueEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder13setMultiEntryEb'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB16ObjectStoreIndex7Builder7releaseEv'/>
