<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1985' ll='2039'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1989' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1991' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2002' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder15setSelectorListEON3WTF3RefINS1_12SelectorListENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2009' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder13setSourceLineEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2016' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9setOriginENS1_16StyleSheetOriginE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2023' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2050' c='_ZN9Inspector8Protocol3CSS7CSSRule6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2052' c='_ZN9Inspector8Protocol3CSS7CSSRule6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSRule::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder15setSelectorListEON3WTF3RefINS1_12SelectorListENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder13setSourceLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9setOriginENS1_16StyleSheetOriginE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1985' ll='2039'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1989' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1991' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2002' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder15setSelectorListEON3WTF3RefINS1_12SelectorListENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2009' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder13setSourceLineEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2016' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9setOriginENS1_16StyleSheetOriginE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2023' c='_ZN9Inspector8Protocol3CSS7CSSRule7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2050' c='_ZN9Inspector8Protocol3CSS7CSSRule6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2052' c='_ZN9Inspector8Protocol3CSS7CSSRule6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSRule::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder15setSelectorListEON3WTF3RefINS1_12SelectorListENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder13setSourceLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder9setOriginENS1_16StyleSheetOriginE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder8setStyleEON3WTF3RefINS1_8CSSStyleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS7CSSRule7Builder7releaseEv'/>
