<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6949' ll='7017'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6953' c='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6955' c='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6966' c='_ZN9Inspector8Protocol7Network8Response7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6973' c='_ZN9Inspector8Protocol7Network8Response7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6980' c='_ZN9Inspector8Protocol7Network8Response7Builder13setStatusTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6987' c='_ZN9Inspector8Protocol7Network8Response7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6994' c='_ZN9Inspector8Protocol7Network8Response7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7001' c='_ZN9Inspector8Protocol7Network8Response7Builder9setSourceENS2_6SourceE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7030' c='_ZN9Inspector8Protocol7Network8Response6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7032' c='_ZN9Inspector8Protocol7Network8Response6createEv'/>
<mbr r='Inspector::Protocol::Network::Response::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder13setStatusTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9setSourceENS2_6SourceE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6949' ll='7017'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6953' c='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6955' c='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6966' c='_ZN9Inspector8Protocol7Network8Response7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6973' c='_ZN9Inspector8Protocol7Network8Response7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6980' c='_ZN9Inspector8Protocol7Network8Response7Builder13setStatusTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6987' c='_ZN9Inspector8Protocol7Network8Response7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6994' c='_ZN9Inspector8Protocol7Network8Response7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7001' c='_ZN9Inspector8Protocol7Network8Response7Builder9setSourceENS2_6SourceE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7030' c='_ZN9Inspector8Protocol7Network8Response6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7032' c='_ZN9Inspector8Protocol7Network8Response6createEv'/>
<mbr r='Inspector::Protocol::Network::Response::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder13setStatusTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder10setHeadersEON3WTF3RefINS1_7HeadersENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder9setSourceENS2_6SourceE'/>
<fun r='_ZN9Inspector8Protocol7Network8Response7Builder7releaseEv'/>
