<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='921' ll='968'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='925' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='927' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='938' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='945' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder14setManifestURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='952' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='978' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='980' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::FrameWithManifest::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder14setManifestURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='921' ll='968'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='925' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='927' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='938' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='945' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder14setManifestURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='952' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9setStatusEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='978' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='980' c='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::FrameWithManifest::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder14setManifestURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder9setStatusEi'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache17FrameWithManifest7Builder7releaseEv'/>
