<dec f='WebKit/Source/WebCore/inspector/InspectorDebuggableType.h' l='32' type='1'/>
<use f='WebKit/Source/WebCore/inspector/InspectorDebuggableType.h' l='46'/>
<doc f='WebKit/Source/WebCore/inspector/InspectorDebuggableType.h' l='32'>// JSC::JSGlobalObject</doc>
<use f='WebKit/Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.cpp' l='215' u='r' c='_ZN6WebKitL14debuggableTypeERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorFrontendHost.cpp' l='344' c='_ZN7WebCoreL22debuggableTypeToStringEN9Inspector14DebuggableTypeE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorFrontendHost.cpp' l='361' u='r' c='_ZNK7WebCore21InspectorFrontendHost14debuggableInfoEv'/>
<use f='WebKit/Source/WebCore/inspector/InspectorFrontendHost.cpp' l='361' u='r' c='_ZNK7WebCore21InspectorFrontendHost14debuggableInfoEv'/>
