<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9710' ll='9757'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9714' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9716' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9727' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder12setStartTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9734' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder10setEndTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9741' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7setTypeENS1_9EventTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9767' c='_ZN9Inspector8Protocol14ScriptProfiler5Event6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9769' c='_ZN9Inspector8Protocol14ScriptProfiler5Event6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder12setStartTimeEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder10setEndTimeEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7setTypeENS1_9EventTypeE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9710' ll='9757'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9714' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9716' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9727' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder12setStartTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9734' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder10setEndTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9741' c='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7setTypeENS1_9EventTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9767' c='_ZN9Inspector8Protocol14ScriptProfiler5Event6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9769' c='_ZN9Inspector8Protocol14ScriptProfiler5Event6createEv'/>
<mbr r='Inspector::Protocol::ScriptProfiler::Event::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder12setStartTimeEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder10setEndTimeEd'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7setTypeENS1_9EventTypeE'/>
<fun r='_ZN9Inspector8Protocol14ScriptProfiler5Event7Builder7releaseEv'/>
