<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10477' ll='10517'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10481' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10483' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10494' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setTypeENS1_9EventTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10501' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setDataEON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10526' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='10528' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent6createEv'/>
<mbr r='Inspector::Protocol::Timeline::TimelineEvent::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setTypeENS1_9EventTypeE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setDataEON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10477' ll='10517'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10481' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10483' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10494' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setTypeENS1_9EventTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10501' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setDataEON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10526' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='10528' c='_ZN9Inspector8Protocol8Timeline13TimelineEvent6createEv'/>
<mbr r='Inspector::Protocol::Timeline::TimelineEvent::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setTypeENS1_9EventTypeE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7setDataEON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Timeline13TimelineEvent7Builder7releaseEv'/>
