<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9184' ll='9224'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9188' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9190' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9201' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder14setStartOffsetEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9208' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder12setEndOffsetEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9233' c='_ZN9Inspector8Protocol7Runtime10ErrorRange6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9235' c='_ZN9Inspector8Protocol7Runtime10ErrorRange6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ErrorRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder14setStartOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder12setEndOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9184' ll='9224'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9188' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9190' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9201' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder14setStartOffsetEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9208' c='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder12setEndOffsetEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9233' c='_ZN9Inspector8Protocol7Runtime10ErrorRange6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9235' c='_ZN9Inspector8Protocol7Runtime10ErrorRange6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ErrorRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder14setStartOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder12setEndOffsetEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime10ErrorRange7Builder7releaseEv'/>
