<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6185' ll='6253'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6189' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6191' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6202' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder10setLayerIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6209' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setNodeIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6216' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6223' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder13setPaintCountEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6230' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setMemoryEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6237' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder19setCompositedBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6266' c='_ZN9Inspector8Protocol9LayerTree5Layer6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6268' c='_ZN9Inspector8Protocol9LayerTree5Layer6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::Layer::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder10setLayerIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder13setPaintCountEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setMemoryEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder19setCompositedBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6185' ll='6253'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6189' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6191' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6202' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder10setLayerIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6209' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setNodeIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6216' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6223' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder13setPaintCountEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6230' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setMemoryEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6237' c='_ZN9Inspector8Protocol9LayerTree5Layer7Builder19setCompositedBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6266' c='_ZN9Inspector8Protocol9LayerTree5Layer6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6268' c='_ZN9Inspector8Protocol9LayerTree5Layer6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::Layer::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder10setLayerIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder13setPaintCountEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder9setMemoryEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder19setCompositedBoundsEON3WTF3RefINS1_7IntRectENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree5Layer7Builder7releaseEv'/>
