<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9094' ll='9148'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9098' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9100' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9111' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder5setIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9118' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setTypeENS1_20ExecutionContextTypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9125' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9132' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9159' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9161' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ExecutionContextDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder5setIdEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setTypeENS1_20ExecutionContextTypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9094' ll='9148'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9098' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9100' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9111' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder5setIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9118' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setTypeENS1_20ExecutionContextTypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9125' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9132' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9159' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9161' c='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ExecutionContextDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder5setIdEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setTypeENS1_20ExecutionContextTypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime27ExecutionContextDescription7Builder7releaseEv'/>
