<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2720' ll='2774'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2724' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2726' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2737' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder6setTagERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2744' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMinimumValueEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2751' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMaximumValueEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2758' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setDefaultValueEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2785' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2787' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis6createEv'/>
<mbr r='Inspector::Protocol::CSS::FontVariationAxis::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder6setTagERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMinimumValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMaximumValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setDefaultValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2720' ll='2774'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2724' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2726' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2737' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder6setTagERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2744' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMinimumValueEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2751' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMaximumValueEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2758' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setDefaultValueEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2785' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2787' c='_ZN9Inspector8Protocol3CSS17FontVariationAxis6createEv'/>
<mbr r='Inspector::Protocol::CSS::FontVariationAxis::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder6setTagERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMinimumValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setMaximumValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder15setDefaultValueEd'/>
<fun r='_ZN9Inspector8Protocol3CSS17FontVariationAxis7Builder7releaseEv'/>
