<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='830' ll='891'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='834' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='836' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='847' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder14setManifestURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='854' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7setSizeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='861' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder15setCreationTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='868' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder13setUpdateTimeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='875' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_24ApplicationCacheResourceEEENS411534300'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='903' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='905' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::ApplicationCache::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder14setManifestURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7setSizeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder15setCreationTimeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder13setUpdateTimeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_24ApplicationCacheResourceEEENS411534300'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='830' ll='891'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='834' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='836' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='847' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder14setManifestURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='854' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7setSizeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='861' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder15setCreationTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='868' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder13setUpdateTimeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='875' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_24ApplicationCacheResourceEEENS411534300'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='903' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='905' c='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache6createEv'/>
<mbr r='Inspector::Protocol::ApplicationCache::ApplicationCache::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder14setManifestURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7setSizeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder15setCreationTimeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder13setUpdateTimeEd'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder12setResourcesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_24ApplicationCacheResourceEEENS411534300'/>
<fun r='_ZN9Inspector8Protocol16ApplicationCache16ApplicationCache7Builder7releaseEv'/>
