<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3967' ll='4021'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3971' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3973' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3984' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setExistsEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3991' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder8setLabelERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3998' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setNodeIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4005' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7setRoleERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4032' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4034' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties6createEv'/>
<mbr r='Inspector::Protocol::DOM::AccessibilityProperties::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setExistsEb'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder8setLabelERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7setRoleERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3967' ll='4021'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3971' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3973' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3984' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setExistsEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3991' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder8setLabelERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3998' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setNodeIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4005' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7setRoleERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4032' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4034' c='_ZN9Inspector8Protocol3DOM23AccessibilityProperties6createEv'/>
<mbr r='Inspector::Protocol::DOM::AccessibilityProperties::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setExistsEb'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder8setLabelERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder9setNodeIdEi'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7setRoleERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3DOM23AccessibilityProperties7Builder7releaseEv'/>
