<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1578' ll='1611'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1582' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1584' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1595' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1619' c='_ZN9Inspector8Protocol3CSS11CSSSelector6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1621' c='_ZN9Inspector8Protocol3CSS11CSSSelector6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSSelector::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1578' ll='1611'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1582' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1584' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1595' c='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1619' c='_ZN9Inspector8Protocol3CSS11CSSSelector6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1621' c='_ZN9Inspector8Protocol3CSS11CSSSelector6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSSelector::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS11CSSSelector7Builder7releaseEv'/>
