<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7903' ll='7950'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7907' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7909' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7920' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7927' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7934' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder15setMatchesCountEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7960' c='_ZN9Inspector8Protocol4Page12SearchResult6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7962' c='_ZN9Inspector8Protocol4Page12SearchResult6createEv'/>
<mbr r='Inspector::Protocol::Page::SearchResult::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder15setMatchesCountEd'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7903' ll='7950'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7907' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7909' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7920' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7927' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7934' c='_ZN9Inspector8Protocol4Page12SearchResult7Builder15setMatchesCountEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7960' c='_ZN9Inspector8Protocol4Page12SearchResult6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7962' c='_ZN9Inspector8Protocol4Page12SearchResult6createEv'/>
<mbr r='Inspector::Protocol::Page::SearchResult::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder15setMatchesCountEd'/>
<fun r='_ZN9Inspector8Protocol4Page12SearchResult7Builder7releaseEv'/>
