<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8854' ll='8887'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8858' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8860' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8871' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8895' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8897' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor6createEv'/>
<mbr r='Inspector::Protocol::Runtime::PropertyDescriptor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8854' ll='8887'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8858' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8860' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8871' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8895' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8897' c='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor6createEv'/>
<mbr r='Inspector::Protocol::Runtime::PropertyDescriptor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime18PropertyDescriptor7Builder7releaseEv'/>
