<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9458' ll='9491'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9462' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9464' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9475' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder10setIsValidEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9499' c='_ZN9Inspector8Protocol7Runtime15TypeDescription6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9501' c='_ZN9Inspector8Protocol7Runtime15TypeDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::TypeDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder10setIsValidEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9458' ll='9491'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9462' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9464' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9475' c='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder10setIsValidEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9499' c='_ZN9Inspector8Protocol7Runtime15TypeDescription6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9501' c='_ZN9Inspector8Protocol7Runtime15TypeDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::TypeDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder10setIsValidEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime15TypeDescription7Builder7releaseEv'/>
