<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2306' ll='2346'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2310' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2312' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2323' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2330' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2355' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2357' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSComputedStyleProperty::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2306' ll='2346'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2310' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2312' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2323' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2330' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2355' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2357' c='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSComputedStyleProperty::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS24CSSComputedStyleProperty7Builder7releaseEv'/>
