<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1790' ll='1879'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1794' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1796' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1807' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1814' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1821' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setSourceURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1828' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9setOriginENS1_16StyleSheetOriginE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1835' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder8setTitleERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1842' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setDisabledEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1849' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setIsInlineEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1856' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setStartLineEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1863' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder14setStartColumnEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1895' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1897' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleSheetHeader::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setSourceURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9setOriginENS1_16StyleSheetOriginE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder8setTitleERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setDisabledEb'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setIsInlineEb'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setStartLineEd'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder14setStartColumnEd'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1790' ll='1879'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1794' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1796' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1807' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1814' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder10setFrameIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1821' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setSourceURLERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1828' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9setOriginENS1_16StyleSheetOriginE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1835' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder8setTitleERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1842' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setDisabledEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1849' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setIsInlineEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1856' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setStartLineEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1863' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder14setStartColumnEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1895' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1897' c='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyleSheetHeader::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder15setStyleSheetIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder10setFrameIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setSourceURLERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder9setOriginENS1_16StyleSheetOriginE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder8setTitleERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setDisabledEb'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder11setIsInlineEb'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder12setStartLineEd'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder14setStartColumnEd'/>
<fun r='_ZN9Inspector8Protocol3CSS19CSSStyleSheetHeader7Builder7releaseEv'/>
