<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9537' ll='9584'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9541' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9543' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9554' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder28setTypeInformationDescriptorEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9561' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder11setSourceIDERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9568' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder8setDivotEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9594' c='_ZN9Inspector8Protocol7Runtime12TypeLocation6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9596' c='_ZN9Inspector8Protocol7Runtime12TypeLocation6createEv'/>
<mbr r='Inspector::Protocol::Runtime::TypeLocation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder28setTypeInformationDescriptorEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder11setSourceIDERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder8setDivotEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9537' ll='9584'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9541' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9543' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9554' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder28setTypeInformationDescriptorEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9561' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder11setSourceIDERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9568' c='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder8setDivotEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9594' c='_ZN9Inspector8Protocol7Runtime12TypeLocation6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9596' c='_ZN9Inspector8Protocol7Runtime12TypeLocation6createEv'/>
<mbr r='Inspector::Protocol::Runtime::TypeLocation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder28setTypeInformationDescriptorEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder11setSourceIDERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder8setDivotEi'/>
<fun r='_ZN9Inspector8Protocol7Runtime12TypeLocation7Builder7releaseEv'/>
