<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1513' ll='1553'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1517' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1519' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1530' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7setRuleEON3WTF3RefINS1_7CSSRuleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1537' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder20setMatchingSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfIiEENS4_12RawPtrTraitsIS8_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1562' c='_ZN9Inspector8Protocol3CSS9RuleMatch6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1564' c='_ZN9Inspector8Protocol3CSS9RuleMatch6createEv'/>
<mbr r='Inspector::Protocol::CSS::RuleMatch::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7setRuleEON3WTF3RefINS1_7CSSRuleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder20setMatchingSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfIiEENS4_12RawPtrTraitsIS8_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1513' ll='1553'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1517' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1519' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1530' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7setRuleEON3WTF3RefINS1_7CSSRuleENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1537' c='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder20setMatchingSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfIiEENS4_12RawPtrTraitsIS8_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1562' c='_ZN9Inspector8Protocol3CSS9RuleMatch6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1564' c='_ZN9Inspector8Protocol3CSS9RuleMatch6createEv'/>
<mbr r='Inspector::Protocol::CSS::RuleMatch::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7setRuleEON3WTF3RefINS1_7CSSRuleENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder20setMatchingSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfIiEENS4_12RawPtrTraitsIS8_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS9RuleMatch7Builder7releaseEv'/>
