<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7312' ll='7366'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7316' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7318' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7329' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9setOpcodeEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7336' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7setMaskEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7343' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder14setPayloadDataERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7350' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder16setPayloadLengthEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7377' c='_ZN9Inspector8Protocol7Network14WebSocketFrame6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7379' c='_ZN9Inspector8Protocol7Network14WebSocketFrame6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9setOpcodeEd'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7setMaskEb'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder14setPayloadDataERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder16setPayloadLengthEd'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7312' ll='7366'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7316' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7318' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7329' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9setOpcodeEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7336' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7setMaskEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7343' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder14setPayloadDataERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7350' c='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder16setPayloadLengthEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7377' c='_ZN9Inspector8Protocol7Network14WebSocketFrame6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7379' c='_ZN9Inspector8Protocol7Network14WebSocketFrame6createEv'/>
<mbr r='Inspector::Protocol::Network::WebSocketFrame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder9setOpcodeEd'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7setMaskEb'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder14setPayloadDataERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder16setPayloadLengthEd'/>
<fun r='_ZN9Inspector8Protocol7Network14WebSocketFrame7Builder7releaseEv'/>
