<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5027' ll='5067'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5031' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5033' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5044' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9setObjectEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5051' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5076' c='_ZN9Inspector8Protocol8Debugger5Scope6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5078' c='_ZN9Inspector8Protocol8Debugger5Scope6createEv'/>
<mbr r='Inspector::Protocol::Debugger::Scope::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder9setObjectEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5027' ll='5067'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5031' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5033' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5044' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder9setObjectEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5051' c='_ZN9Inspector8Protocol8Debugger5Scope7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5076' c='_ZN9Inspector8Protocol8Debugger5Scope6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5078' c='_ZN9Inspector8Protocol8Debugger5Scope6createEv'/>
<mbr r='Inspector::Protocol::Debugger::Scope::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder9setObjectEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol8Debugger5Scope7Builder7releaseEv'/>
