<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1450' ll='1483'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1454' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1456' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1467' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder18setMatchedCSSRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1491' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1493' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry6createEv'/>
<mbr r='Inspector::Protocol::CSS::InheritedStyleEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder18setMatchedCSSRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1450' ll='1483'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1454' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1456' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1467' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder18setMatchedCSSRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1491' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1493' c='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry6createEv'/>
<mbr r='Inspector::Protocol::CSS::InheritedStyleEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder18setMatchedCSSRulesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_9RuleMatchEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS19InheritedStyleEntry7Builder7releaseEv'/>
