<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2829' type='50'/>
<dec f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2829' type='50'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='505' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='505' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorShaderProgram.cpp' l='121' c='_ZN7WebCoreL13shaderForTypeERNS_12WebGLProgramEN9Inspector8Protocol6Canvas10ShaderTypeE'/>
