<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6099' ll='6153'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6103' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6105' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6116' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setXEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6123' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setYEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6130' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder8setWidthEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6137' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9setHeightEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6164' c='_ZN9Inspector8Protocol9LayerTree7IntRect6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6166' c='_ZN9Inspector8Protocol9LayerTree7IntRect6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::IntRect::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setXEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setYEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder8setWidthEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9setHeightEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6099' ll='6153'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6103' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6105' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6116' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setXEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6123' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setYEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6130' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder8setWidthEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6137' c='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9setHeightEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6164' c='_ZN9Inspector8Protocol9LayerTree7IntRect6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6166' c='_ZN9Inspector8Protocol9LayerTree7IntRect6createEv'/>
<mbr r='Inspector::Protocol::LayerTree::IntRect::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setXEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder4setYEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder8setWidthEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder9setHeightEi'/>
<fun r='_ZN9Inspector8Protocol9LayerTree7IntRect7Builder7releaseEv'/>
