<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2165' ll='2205'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2169' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2171' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2182' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2189' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2214' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2216' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry6createEv'/>
<mbr r='Inspector::Protocol::CSS::ShorthandEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2165' ll='2205'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2169' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2171' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2182' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2189' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder8setValueERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2214' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2216' c='_ZN9Inspector8Protocol3CSS14ShorthandEntry6createEv'/>
<mbr r='Inspector::Protocol::CSS::ShorthandEntry::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder8setValueERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS14ShorthandEntry7Builder7releaseEv'/>
