<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5253' ll='5286'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5257' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5259' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5270' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder15setBreakpointIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5294' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5296' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder15setBreakpointIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5253' ll='5286'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5257' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5259' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5270' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder15setBreakpointIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5294' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5296' c='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder15setBreakpointIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger21BreakpointPauseReason7Builder7releaseEv'/>
