<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9022' ll='9048'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9026' c='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9028' c='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9055' c='_ZN9Inspector8Protocol7Runtime12CallArgument6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9057' c='_ZN9Inspector8Protocol7Runtime12CallArgument6createEv'/>
<mbr r='Inspector::Protocol::Runtime::CallArgument::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9022' ll='9048'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9026' c='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9028' c='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9055' c='_ZN9Inspector8Protocol7Runtime12CallArgument6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9057' c='_ZN9Inspector8Protocol7Runtime12CallArgument6createEv'/>
<mbr r='Inspector::Protocol::Runtime::CallArgument::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime12CallArgument7Builder7releaseEv'/>
