<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1076' ll='1116'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1080' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1082' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1093' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1100' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder8setUsageEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1125' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1127' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo6createEv'/>
<mbr r='Inspector::Protocol::CPUProfiler::ThreadInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder8setUsageEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1076' ll='1116'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1080' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1082' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1093' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1100' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder8setUsageEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1125' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1127' c='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo6createEv'/>
<mbr r='Inspector::Protocol::CPUProfiler::ThreadInfo::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder8setUsageEd'/>
<fun r='_ZN9Inspector8Protocol11CPUProfiler10ThreadInfo7Builder7releaseEv'/>
