<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2372' ll='2412'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2376' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2378' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2389' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder16setCssPropertiesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSPropertyEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2396' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder19setShorthandEntriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_14ShorthandEntryEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2421' c='_ZN9Inspector8Protocol3CSS8CSSStyle6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2423' c='_ZN9Inspector8Protocol3CSS8CSSStyle6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyle::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder16setCssPropertiesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSPropertyEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder19setShorthandEntriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_14ShorthandEntryEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2372' ll='2412'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2376' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2378' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2389' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder16setCssPropertiesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSPropertyEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2396' c='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder19setShorthandEntriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_14ShorthandEntryEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2421' c='_ZN9Inspector8Protocol3CSS8CSSStyle6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2423' c='_ZN9Inspector8Protocol3CSS8CSSStyle6createEv'/>
<mbr r='Inspector::Protocol::CSS::CSSStyle::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder16setCssPropertiesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSPropertyEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder19setShorthandEntriesEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_14ShorthandEntryEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8CSSStyle7Builder7releaseEv'/>
