<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1646' ll='1686'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1650' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1652' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1663' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder12setSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSSelectorEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1670' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1695' c='_ZN9Inspector8Protocol3CSS12SelectorList6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1697' c='_ZN9Inspector8Protocol3CSS12SelectorList6createEv'/>
<mbr r='Inspector::Protocol::CSS::SelectorList::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder12setSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSSelectorEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1646' ll='1686'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1650' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1652' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1663' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder12setSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSSelectorEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1670' c='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1695' c='_ZN9Inspector8Protocol3CSS12SelectorList6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1697' c='_ZN9Inspector8Protocol3CSS12SelectorList6createEv'/>
<mbr r='Inspector::Protocol::CSS::SelectorList::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder12setSelectorsEON3WTF3RefINS4_8JSONImpl7ArrayOfINS1_11CSSSelectorEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS12SelectorList7Builder7releaseEv'/>
