<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2084' ll='2138'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2088' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2090' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2101' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setStartLineEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2108' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder14setStartColumnEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2115' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder10setEndLineEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2122' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setEndColumnEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2149' c='_ZN9Inspector8Protocol3CSS11SourceRange6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2151' c='_ZN9Inspector8Protocol3CSS11SourceRange6createEv'/>
<mbr r='Inspector::Protocol::CSS::SourceRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setStartLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder14setStartColumnEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder10setEndLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setEndColumnEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2084' ll='2138'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2088' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2090' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2101' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setStartLineEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2108' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder14setStartColumnEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2115' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder10setEndLineEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2122' c='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setEndColumnEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2149' c='_ZN9Inspector8Protocol3CSS11SourceRange6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2151' c='_ZN9Inspector8Protocol3CSS11SourceRange6createEv'/>
<mbr r='Inspector::Protocol::CSS::SourceRange::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setStartLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder14setStartColumnEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder10setEndLineEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder12setEndColumnEi'/>
<fun r='_ZN9Inspector8Protocol3CSS11SourceRange7Builder7releaseEv'/>
