<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7637' ll='7698'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7641' c='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7643' c='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7654' c='_ZN9Inspector8Protocol4Page5Frame7Builder5setIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7661' c='_ZN9Inspector8Protocol4Page5Frame7Builder11setLoaderIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7668' c='_ZN9Inspector8Protocol4Page5Frame7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7675' c='_ZN9Inspector8Protocol4Page5Frame7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7682' c='_ZN9Inspector8Protocol4Page5Frame7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7710' c='_ZN9Inspector8Protocol4Page5Frame6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7712' c='_ZN9Inspector8Protocol4Page5Frame6createEv'/>
<mbr r='Inspector::Protocol::Page::Frame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder5setIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder11setLoaderIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7637' ll='7698'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7641' c='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7643' c='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7654' c='_ZN9Inspector8Protocol4Page5Frame7Builder5setIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7661' c='_ZN9Inspector8Protocol4Page5Frame7Builder11setLoaderIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7668' c='_ZN9Inspector8Protocol4Page5Frame7Builder6setUrlERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7675' c='_ZN9Inspector8Protocol4Page5Frame7Builder17setSecurityOriginERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7682' c='_ZN9Inspector8Protocol4Page5Frame7Builder11setMimeTypeERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7710' c='_ZN9Inspector8Protocol4Page5Frame6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7712' c='_ZN9Inspector8Protocol4Page5Frame6createEv'/>
<mbr r='Inspector::Protocol::Page::Frame::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder5setIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder11setLoaderIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder6setUrlERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder17setSecurityOriginERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder11setMimeTypeERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol4Page5Frame7Builder7releaseEv'/>
