<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='3103' type='55'/>
<dec f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='3103' type='55'/>
<use f='WebKit/Source/JavaScriptCore/inspector/ConsoleMessage.cpp' l='181' u='r' c='_ZN9InspectorL18messageSourceValueEN3JSC13MessageSourceE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='523' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='523' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageConsoleAgent.cpp' l='88' u='r' c='_ZN7WebCore16PageConsoleAgent18getLoggingChannelsEv'/>
