<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9247' ll='9273'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9251' c='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9253' c='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9280' c='_ZN9Inspector8Protocol7Runtime20StructureDescription6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='9282' c='_ZN9Inspector8Protocol7Runtime20StructureDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::StructureDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9247' ll='9273'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9251' c='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9253' c='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9280' c='_ZN9Inspector8Protocol7Runtime20StructureDescription6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='9282' c='_ZN9Inspector8Protocol7Runtime20StructureDescription6createEv'/>
<mbr r='Inspector::Protocol::Runtime::StructureDescription::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime20StructureDescription7Builder7releaseEv'/>
