<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7474' type='159'/>
<dec f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7474' type='159'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='915' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.cpp' l='915' u='r' c='_ZN9Inspector8Protocol7Helpers24parseEnumValueFromStringERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp' l='747' u='r' c='_ZN7WebCore21InspectorNetworkAgent20buildInitiatorObjectEPNS_8DocumentEPKNS_15ResourceRequestE'/>
