<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5111' ll='5172'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5115' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5117' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5128' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setProbeIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5135' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder11setSampleIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5142' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setBatchIdEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5149' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5156' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setPayloadEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5184' c='_ZN9Inspector8Protocol8Debugger11ProbeSample6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5186' c='_ZN9Inspector8Protocol8Debugger11ProbeSample6createEv'/>
<mbr r='Inspector::Protocol::Debugger::ProbeSample::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setProbeIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder11setSampleIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setBatchIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setPayloadEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5111' ll='5172'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5115' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5117' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5128' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setProbeIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5135' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder11setSampleIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5142' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setBatchIdEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5149' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder12setTimestampEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5156' c='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setPayloadEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5184' c='_ZN9Inspector8Protocol8Debugger11ProbeSample6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5186' c='_ZN9Inspector8Protocol8Debugger11ProbeSample6createEv'/>
<mbr r='Inspector::Protocol::Debugger::ProbeSample::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setProbeIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder11setSampleIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setBatchIdEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder12setTimestampEd'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder10setPayloadEON3WTF3RefINS0_7Runtime12RemoteObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger11ProbeSample7Builder7releaseEv'/>
