<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='999' ll='1039'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1003' c='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1005' c='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1016' c='_ZN9Inspector8Protocol7Browser9Extension7Builder14setExtensionIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1023' c='_ZN9Inspector8Protocol7Browser9Extension7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1048' c='_ZN9Inspector8Protocol7Browser9Extension6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='1050' c='_ZN9Inspector8Protocol7Browser9Extension6createEv'/>
<mbr r='Inspector::Protocol::Browser::Extension::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder14setExtensionIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='999' ll='1039'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1003' c='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1005' c='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1016' c='_ZN9Inspector8Protocol7Browser9Extension7Builder14setExtensionIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1023' c='_ZN9Inspector8Protocol7Browser9Extension7Builder7setNameERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1048' c='_ZN9Inspector8Protocol7Browser9Extension6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='1050' c='_ZN9Inspector8Protocol7Browser9Extension6createEv'/>
<mbr r='Inspector::Protocol::Browser::Extension::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder14setExtensionIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder7setNameERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol7Browser9Extension7Builder7releaseEv'/>
