<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8522' ll='8562'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8526' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8528' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8539' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8546' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder11setLosslessEb'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8571' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8573' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ObjectPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder11setLosslessEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8522' ll='8562'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8526' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8528' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8539' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8546' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder11setLosslessEb'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8571' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8573' c='_ZN9Inspector8Protocol7Runtime13ObjectPreview6createEv'/>
<mbr r='Inspector::Protocol::Runtime::ObjectPreview::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder11setLosslessEb'/>
<fun r='_ZN9Inspector8Protocol7Runtime13ObjectPreview7Builder7releaseEv'/>
