<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4190' ll='4237'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4194' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4196' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4207' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setREi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4214' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setGEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4221' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setBEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4247' c='_ZN9Inspector8Protocol3DOM9RGBAColor6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4249' c='_ZN9Inspector8Protocol3DOM9RGBAColor6createEv'/>
<mbr r='Inspector::Protocol::DOM::RGBAColor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setREi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setGEi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setBEi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4190' ll='4237'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4194' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4196' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4207' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setREi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4214' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setGEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4221' c='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setBEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4247' c='_ZN9Inspector8Protocol3DOM9RGBAColor6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4249' c='_ZN9Inspector8Protocol3DOM9RGBAColor6createEv'/>
<mbr r='Inspector::Protocol::DOM::RGBAColor::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setREi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setGEi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder4setBEi'/>
<fun r='_ZN9Inspector8Protocol3DOM9RGBAColor7Builder7releaseEv'/>
