<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4606' ll='4646'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4610' c='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4612' c='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4623' c='_ZN9Inspector8Protocol8Debugger8Location7Builder11setScriptIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4630' c='_ZN9Inspector8Protocol8Debugger8Location7Builder13setLineNumberEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4655' c='_ZN9Inspector8Protocol8Debugger8Location6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4657' c='_ZN9Inspector8Protocol8Debugger8Location6createEv'/>
<mbr r='Inspector::Protocol::Debugger::Location::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder11setScriptIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder13setLineNumberEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4606' ll='4646'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4610' c='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4612' c='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4623' c='_ZN9Inspector8Protocol8Debugger8Location7Builder11setScriptIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4630' c='_ZN9Inspector8Protocol8Debugger8Location7Builder13setLineNumberEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4655' c='_ZN9Inspector8Protocol8Debugger8Location6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4657' c='_ZN9Inspector8Protocol8Debugger8Location6createEv'/>
<mbr r='Inspector::Protocol::Debugger::Location::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder11setScriptIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder13setLineNumberEi'/>
<fun r='_ZN9Inspector8Protocol8Debugger8Location7Builder7releaseEv'/>
