<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6025' ll='6058'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6029' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6031' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6042' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6066' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6068' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::KeyPath::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6025' ll='6058'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6029' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6031' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6042' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6066' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6068' c='_ZN9Inspector8Protocol9IndexedDB7KeyPath6createEv'/>
<mbr r='Inspector::Protocol::IndexedDB::KeyPath::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9IndexedDB7KeyPath7Builder7releaseEv'/>
