<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8276' ll='8330'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8280' c='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8282' c='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8293' c='_ZN9Inspector8Protocol9Recording9Recording7Builder10setVersionEi'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8300' c='_ZN9Inspector8Protocol9Recording9Recording7Builder7setTypeENS1_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8307' c='_ZN9Inspector8Protocol9Recording9Recording7Builder15setInitialStateEON3WTF3RefINS1_12InitialStateENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8314' c='_ZN9Inspector8Protocol9Recording9Recording7Builder7setDataEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8341' c='_ZN9Inspector8Protocol9Recording9Recording6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='8343' c='_ZN9Inspector8Protocol9Recording9Recording6createEv'/>
<mbr r='Inspector::Protocol::Recording::Recording::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder10setVersionEi'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7setTypeENS1_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder15setInitialStateEON3WTF3RefINS1_12InitialStateENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7setDataEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8276' ll='8330'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8280' c='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8282' c='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8293' c='_ZN9Inspector8Protocol9Recording9Recording7Builder10setVersionEi'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8300' c='_ZN9Inspector8Protocol9Recording9Recording7Builder7setTypeENS1_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8307' c='_ZN9Inspector8Protocol9Recording9Recording7Builder15setInitialStateEON3WTF3RefINS1_12InitialStateENS4_12RawPtrTraitsIS6_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8314' c='_ZN9Inspector8Protocol9Recording9Recording7Builder7setDataEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8341' c='_ZN9Inspector8Protocol9Recording9Recording6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='8343' c='_ZN9Inspector8Protocol9Recording9Recording6createEv'/>
<mbr r='Inspector::Protocol::Recording::Recording::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder10setVersionEi'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7setTypeENS1_4TypeE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder15setInitialStateEON3WTF3RefINS1_12InitialStateENS4_12RawPtrTraitsIS6_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7setDataEON3WTF3RefINS4_8JSONImpl7ArrayOfINS6_5ValueEEENS4_12RawPtrTraitsIS9_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Recording9Recording7Builder7releaseEv'/>
