<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5310' ll='5343'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5314' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5316' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5327' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder12setDirectiveERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5351' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5353' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::CSPViolationPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder12setDirectiveERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5310' ll='5343'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5314' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5316' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5327' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder12setDirectiveERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5351' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5353' c='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason6createEv'/>
<mbr r='Inspector::Protocol::Debugger::CSPViolationPauseReason::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder12setDirectiveERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol8Debugger23CSPViolationPauseReason7Builder7releaseEv'/>
