<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='427' ll='460'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='431' c='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='433' c='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='444' c='_ZN9Inspector8Protocol9Animation9Animation7Builder14setAnimationIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='468' c='_ZN9Inspector8Protocol9Animation9Animation6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='470' c='_ZN9Inspector8Protocol9Animation9Animation6createEv'/>
<mbr r='Inspector::Protocol::Animation::Animation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder14setAnimationIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='427' ll='460'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='431' c='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='433' c='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='444' c='_ZN9Inspector8Protocol9Animation9Animation7Builder14setAnimationIdERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='468' c='_ZN9Inspector8Protocol9Animation9Animation6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='470' c='_ZN9Inspector8Protocol9Animation9Animation6createEv'/>
<mbr r='Inspector::Protocol::Animation::Animation::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder14setAnimationIdERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol9Animation9Animation7Builder7releaseEv'/>
