<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5372' ll='5412'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5376' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5378' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5389' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder13setLineNumberEd'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5396' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder14setLineContentERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5421' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='5423' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch6createEv'/>
<mbr r='Inspector::Protocol::GenericTypes::SearchMatch::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder13setLineNumberEd'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder14setLineContentERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5372' ll='5412'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5376' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5378' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5389' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder13setLineNumberEd'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5396' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder14setLineContentERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5421' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='5423' c='_ZN9Inspector8Protocol12GenericTypes11SearchMatch6createEv'/>
<mbr r='Inspector::Protocol::GenericTypes::SearchMatch::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder13setLineNumberEd'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder14setLineContentERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol12GenericTypes11SearchMatch7Builder7releaseEv'/>
