<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7073' ll='7099'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7077' c='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7079' c='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7106' c='_ZN9Inspector8Protocol7Network7Metrics6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='7108' c='_ZN9Inspector8Protocol7Network7Metrics6createEv'/>
<mbr r='Inspector::Protocol::Network::Metrics::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7073' ll='7099'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7077' c='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7079' c='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7106' c='_ZN9Inspector8Protocol7Network7Metrics6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='7108' c='_ZN9Inspector8Protocol7Network7Metrics6createEv'/>
<mbr r='Inspector::Protocol::Network::Metrics::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Metrics7Builder7releaseEv'/>
