<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4689' ll='4722'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4693' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4695' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4706' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4730' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='4732' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointAction::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4689' ll='4722'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4693' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4695' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4706' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4730' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='4732' c='_ZN9Inspector8Protocol8Debugger16BreakpointAction6createEv'/>
<mbr r='Inspector::Protocol::Debugger::BreakpointAction::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol8Debugger16BreakpointAction7Builder7releaseEv'/>
