<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2581' ll='2621'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2585' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2587' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2598' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2605' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2630' c='_ZN9Inspector8Protocol3CSS8Grouping6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='2632' c='_ZN9Inspector8Protocol3CSS8Grouping6createEv'/>
<mbr r='Inspector::Protocol::CSS::Grouping::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2581' ll='2621'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2585' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2587' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2598' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTextERKN3WTF6StringE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2605' c='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTypeENS2_4TypeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2630' c='_ZN9Inspector8Protocol3CSS8Grouping6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='2632' c='_ZN9Inspector8Protocol3CSS8Grouping6createEv'/>
<mbr r='Inspector::Protocol::CSS::Grouping::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTextERKN3WTF6StringE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7setTypeENS2_4TypeE'/>
<fun r='_ZN9Inspector8Protocol3CSS8Grouping7Builder7releaseEv'/>
