<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6649' ll='6675'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6653' c='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6655' c='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6682' c='_ZN9Inspector8Protocol7Network7Headers6createEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorProtocolObjects.h' l='6684' c='_ZN9Inspector8Protocol7Network7Headers6createEv'/>
<mbr r='Inspector::Protocol::Network::Headers::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7Builder7releaseEv'/>
<def f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6649' ll='6675'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6653' c='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6655' c='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6682' c='_ZN9Inspector8Protocol7Network7Headers6createEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/inspector/InspectorProtocolObjects.h' l='6684' c='_ZN9Inspector8Protocol7Network7Headers6createEv'/>
<mbr r='Inspector::Protocol::Network::Headers::Builder::m_result' t='RefPtr&lt;JSON::Object&gt;'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7Builder9castStateEv'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7BuilderC1EON3WTF3RefINS4_8JSONImpl6ObjectENS4_12RawPtrTraitsIS7_EEEE'/>
<fun r='_ZN9Inspector8Protocol7Network7Headers7Builder7releaseEv'/>
