<dec f='WebKit/Source/JavaScriptCore/wasm/WasmFormat.h' l='153' type='const JSC::Wasm::Name'/>
<offset>0</offset>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmEntryPlan.cpp' l='128' u='r' c='_ZN3JSC4Wasm9EntryPlan7prepareEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.cpp' l='175' u='r' c='_ZN3JSC21JSWebAssemblyInstance9tryCreateERNS_2VMEPNS_14JSGlobalObjectERKNS_10IdentifierEPNS_19JSWebAssemblyModuleEPNS_8JSObjectEPNS_9StructureEON3WTF313901825'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.cpp' l='203' u='r' c='_ZN3JSC21JSWebAssemblyInstance9tryCreateERNS_2VMEPNS_14JSGlobalObjectERKNS_10IdentifierEPNS_19JSWebAssemblyModuleEPNS_8JSObjectEPNS_9StructureEON3WTF313901825'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/WebAssemblyModuleConstructor.cpp' l='119' u='r' c='_ZN3JSCL24webAssemblyModuleImportsEPNS_14JSGlobalObjectEPNS_9CallFrameE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/WebAssemblyModuleRecord.cpp' l='123' u='r' c='_ZN3JSC23WebAssemblyModuleRecord8linkImplEPNS_14JSGlobalObjectEPNS_8JSObjectENS_4Wasm12CreationModeE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/WebAssemblyModuleRecord.cpp' l='138' u='r' c='_ZN3JSC23WebAssemblyModuleRecord8linkImplEPNS_14JSGlobalObjectEPNS_8JSObjectENS_4Wasm12CreationModeE'/>
<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmFormat.h' l='153' type='const JSC::Wasm::Name'/>
<offset>0</offset>
