<dec f='WebKit/Source/JavaScriptCore/jit/JITPlan.h' l='61' type='2'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITPlan.cpp' l='83' u='r' c='_ZNK3JSC7JITPlan4tierEv'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITWorklist.cpp' l='261' u='r' c='_ZN3JSC11JITWorklist43setMaximumNumberOfConcurrentFTLCompilationsEj'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITWorklist.cpp' l='262' u='r' c='_ZN3JSC11JITWorklist43setMaximumNumberOfConcurrentFTLCompilationsEj'/>
