<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ParserModes.h' l='36' type='1'/>
<dec f='WebKit/Source/JavaScriptCore/parser/ParserModes.h' l='36' type='1'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.h' l='1864' c='_ZN3JSC6Parser21canUseIdentifierAwaitEv'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.h' l='1922' c='_ZN3JSC6Parser31disallowedIdentifierAwaitReasonEv'/>
<use f='WebKit/Source/JavaScriptCore/debugger/DebuggerParseData.cpp' l='127'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.cpp' l='5131' c='_ZN3JSC6Parser21parseMemberExpressionERT_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp' l='376' u='r' c='_ZN3JSCL23moduleLoaderParseModuleEPNS_14JSGlobalObjectEPNS_9CallFrameE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/CodeCache.cpp' l='201' u='r' c='_ZN3JSC9CodeCache33getUnlinkedModuleProgramCodeBlockERNS_2VMEPNS_23ModuleProgramExecutableERKNS_10SourceCodeEN3WTF9OptionSetINS_18CodeGenerationModeEEERNS_11ParserErrorE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/CodeCache.cpp' l='301' u='r' c='_ZN3JSC32sourceCodeKeyForSerializedModuleERNS_2VMERKNS_10SourceCodeE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/Completion.cpp' l='79' u='r' c='_ZN3JSC17checkModuleSyntaxEPNS_14JSGlobalObjectERKNS_10SourceCodeERNS_11ParserErrorE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/Completion.cpp' l='114' u='r' c='_ZN3JSC22generateModuleBytecodeERNS_2VMERKNS_10SourceCodeEP14_GFileIOStreamRNS_18BytecodeCacheErrorE'/>
<use f='WebKit/Source/JavaScriptCore/API/glib/JSCContext.cpp' l='972' u='r' c='_Z24jsc_context_check_syntaxP11_JSCContextPKcl18JSCCheckSyntaxModeS2_jPP13_JSCException'/>
