<def f='WebKit/Source/JavaScriptCore/tools/VMInspector.cpp' l='305' ll='308'/>
<use f='WebKit/Source/JavaScriptCore/tools/VMInspector.cpp' l='310' c='_ZN3JSC16DumpFrameFunctorC1ENS0_6ActionEj'/>
<use f='WebKit/Source/JavaScriptCore/tools/VMInspector.cpp' l='330'/>
