<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ParserTokens.h' l='79' type='527'/>
<dec f='WebKit/Source/JavaScriptCore/parser/ParserTokens.h' l='79' type='527'/>
<use f='WebKit/JavaScriptCore/DerivedSources/KeywordLookup.h' l='379' u='r' c='_ZN3JSC5LexerIDsE12parseKeywordEPNS_11JSTokenDataE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/KeywordLookup.h' l='750' u='r' c='_ZN3JSC5LexerIhE12parseKeywordEPNS_11JSTokenDataE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='169'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='169' u='r'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='169'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='169' u='r'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.cpp' l='1960' c='_ZN3JSC6Parser14parseStatementERT_RPKNS_10IdentifierEPj'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.cpp' l='3343' c='_ZN3JSC6Parser31parseExpressionOrLabelStatementERT_b'/>
