<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ParserTokens.h' l='70' type='518'/>
<dec f='WebKit/Source/JavaScriptCore/parser/ParserTokens.h' l='70' type='518'/>
<use f='WebKit/JavaScriptCore/DerivedSources/KeywordLookup.h' l='110' u='r' c='_ZN3JSC5LexerIDsE12parseKeywordEPNS_11JSTokenDataE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/KeywordLookup.h' l='481' u='r' c='_ZN3JSC5LexerIhE12parseKeywordEPNS_11JSTokenDataE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='157'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='157' u='r'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='157'/>
<use f='WebKit/JavaScriptCore/DerivedSources/Lexer.lut.h' l='157' u='r'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.cpp' l='1966' c='_ZN3JSC6Parser14parseStatementERT_RPKNS_10IdentifierEPj'/>
<use f='WebKit/Source/JavaScriptCore/parser/Parser.cpp' l='3341' c='_ZN3JSC6Parser31parseExpressionOrLabelStatementERT_b'/>
