<dec f='WebKit/JavaScriptCore/DerivedSources/AirOpcode.h' l='92' type='86'/>
<use f='WebKit/JavaScriptCore/DerivedSources/AirOpcodeUtils.h' l='4913' c='_ZN3JSC2B33Air11isValidFormENS1_6OpcodeEDpT_'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersAndStackAndGenerateCode.cpp' l='546' u='r' c='_ZN3JSC2B33Air28GenerateAndAllocateRegisters8generateERNS_12CCallHelpersE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersAndStackByLinearScan.cpp' l='580' u='r' c='_ZN3JSC2B33Air12_GLOBAL__N_110LinearScan13emitSpillCodeEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirUseCounts.h' l='81' u='r' c='_ZN3JSC2B33Air9UseCountsC1ERNS1_4CodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='1697' c='_ZN3JSC2B33Air12_GLOBAL__N_117ColoringAllocator20mayBeCoalescableImplERKNS1_4InstEPNS1_8TmpWidthE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='1931' u='r' c='_ZN3JSC2B33Air12_GLOBAL__N_131GraphColoringRegisterAllocation20assignRegistersToTmpERKT0_'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='2003' u='r' c='_ZN3JSC2B33Air12_GLOBAL__N_131GraphColoringRegisterAllocation15addSpillAndFillERKT0_RN3WTF9BitVectorE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='2027' c='_ZN3JSC2B33Air12_GLOBAL__N_131GraphColoringRegisterAllocation15addSpillAndFillERKT0_RN3WTF9BitVectorE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='2088' c='_ZN3JSC2B33Air12_GLOBAL__N_131GraphColoringRegisterAllocation15addSpillAndFillERKT0_RN3WTF9BitVectorE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp' l='2142' u='r' c='_ZN3JSC2B33Air12_GLOBAL__N_131GraphColoringRegisterAllocation15addSpillAndFillERKT0_RN3WTF9BitVectorE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirAllocateStackByGraphColoring.cpp' l='69' c='_ZNK3JSC2B33Air12_GLOBAL__N_118StackAllocatorBase17isCoalescableMoveERNS1_4InstE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirEmitShuffle.h' l='48' u='r' c='_ZN3JSC2B33Air7moveForENS0_4BankENS0_5WidthE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirEmitShuffle.cpp' l='108' u='r' c='_ZNK3JSC2B33Air11ShufflePair5instsERNS1_4CodeEPNS0_5ValueE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirEmitShuffle.cpp' l='108' u='r' c='_ZNK3JSC2B33Air11ShufflePair5instsERNS1_4CodeEPNS0_5ValueE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirEmitShuffle.cpp' l='352' u='r' c='_ZN3JSC2B33Air11emitShuffleERNS1_4CodeEN3WTF6VectorINS1_11ShufflePairELm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEESt5arrayINS1_3ArgELm2EENS0_4BankEPNS0_5ValueE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirFixObviousSpills.cpp' l='117' c='_ZN3JSC2B33Air12_GLOBAL__N_116FixObviousSpills13forAllAliasesERKT_'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirFixObviousSpills.cpp' l='211' c='_ZN3JSC2B33Air12_GLOBAL__N_116FixObviousSpills7fixInstEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/AirOpcodeGenerated.h' l='270' c='_ZN3WTF13printInternalERNS_11PrintStreamEN3JSC2B33Air6OpcodeE'/>
<use f='WebKit/JavaScriptCore/DerivedSources/AirOpcodeGenerated.h' l='11238' c='_ZN3JSC2B33Air4Inst11isValidFormEv'/>
<use f='WebKit/JavaScriptCore/DerivedSources/AirOpcodeGenerated.h' l='25669' c='_ZN3JSC2B33Air4Inst11admitsStackEj'/>
<use f='WebKit/JavaScriptCore/DerivedSources/AirOpcodeGenerated.h' l='35111' c='_ZN3JSC2B33Air4Inst8generateERNS_12CCallHelpersERNS1_17GenerationContextE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirLowerMacros.cpp' l='115' u='a' c='_ZN3JSC2B33Air11lowerMacrosERNS1_4CodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirLowerStackArgs.cpp' l='84' u='a' c='_ZN3JSC2B33Air14lowerStackArgsERNS1_4CodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirTmpWidth.cpp' l='96' u='r' c='_ZN3JSC2B33Air8TmpWidth9recomputeERNS1_4CodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirHelpers.h' l='41' u='r' c='_ZN3JSC2B33Air11moveForTypeENS0_4TypeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/air/AirHelpers.h' l='73' u='r' c='_ZN3JSC2B33Air18relaxedMoveForTypeENS0_4TypeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='1037' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir11appendShiftEPNS0_5ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='1048' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir11appendShiftEPNS0_5ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='1049' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir11appendShiftEPNS0_5ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='1152' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir11createStoreENS0_3Air4KindEPNS0_5ValueERKNS3_3ArgE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='1187' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir11storeOpcodeENS0_5WidthENS0_4BankE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2206' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir12appendX86DivENS0_6OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2209' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir12appendX86DivENS0_6OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2220' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir13appendX86UDivENS0_6OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2223' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir13appendX86UDivENS0_6OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2403' u='a' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir9appendCASEPNS0_5ValueEb'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2414' u='a' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir9appendCASEPNS0_5ValueEb'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2489' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir19appendGeneralAtomicENS0_3Air6OpcodeENS0_13CommutativityE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3526' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3528' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3552' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3749' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3797' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3804' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3807' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3883' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3897' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3899' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='4115' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='4119' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='536' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14emitPatchpointEPNS_2B33Air10BasicBlockEPNS2_15PatchpointValueERKN3WTF6VectorIT_Lm8ENS8_15CrashOnOverflowELm16ENS8_10Fast4755338'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='542' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14emitPatchpointEPNS_2B33Air10BasicBlockEPNS2_15PatchpointValueERKN3WTF6VectorIT_Lm8ENS8_15CrashOnOverflowELm16ENS8_10Fast4755338'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='637' c='_ZN3JSC4Wasm14AirIRGenerator9emitCCallEPNS_2B33Air10BasicBlockET_NS0_8TypedTmpEDpT0_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='658' u='r' c='_ZN3JSC4Wasm14AirIRGenerator18moveOpForValueTypeENS0_4TypeE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='762' u='r' c='_ZN3JSC4Wasm14AirIRGenerator22fixupPointerPlusOffsetERNS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='892' u='r' c='_ZN3JSC4Wasm14AirIRGeneratorC1ERKNS0_17ModuleInformationERNS_2B39ProcedureEPNS0_16InternalFunctionERN3WTF6VectorINS0_22UnlinkedWasmToWasmCallELm0ENSA_7929608'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='916' u='r' c='_ZN3JSC4Wasm14AirIRGeneratorC1ERKNS0_17ModuleInformationERNS_2B39ProcedureEPNS0_16InternalFunctionERN3WTF6VectorINS0_22UnlinkedWasmToWasmCallELm0ENSA_7929608'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='960' u='r' c='_ZN3JSC4Wasm14AirIRGenerator29restoreWebAssemblyGlobalStateENS1_23RestoreCachedStackLimitERKNS0_17MemoryInformationENS0_8TypedTmpEPNS_2B33Air10BasicBlockE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='961' u='r' c='_ZN3JSC4Wasm14AirIRGenerator29restoreWebAssemblyGlobalStateENS1_23RestoreCachedStackLimitERKNS0_17MemoryInformationENS0_8TypedTmpEPNS_2B33Air10BasicBlockE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='962' u='r' c='_ZN3JSC4Wasm14AirIRGenerator29restoreWebAssemblyGlobalStateENS1_23RestoreCachedStackLimitERKNS0_17MemoryInformationENS0_8TypedTmpEPNS_2B33Air10BasicBlockE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1019' u='r' c='_ZN3JSC4Wasm14AirIRGenerator8addLocalENS0_4TypeEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1055' u='r' c='_ZN3JSC4Wasm14AirIRGenerator11addConstantEPNS_2B33Air10BasicBlockENS0_4TypeEm'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1060' u='r' c='_ZN3JSC4Wasm14AirIRGenerator11addConstantEPNS_2B33Air10BasicBlockENS0_4TypeEm'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1090' u='r' c='_ZN3JSC4Wasm14AirIRGenerator12addRefIsNullENS0_8TypedTmpERS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1288' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16addCurrentMemoryERNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1289' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16addCurrentMemoryERNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1290' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16addCurrentMemoryERNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1293' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16addCurrentMemoryERNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1399' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9getGlobalEjRNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1408' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9getGlobalEjRNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1416' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9getGlobalEjRNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1419' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9getGlobalEjRNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1421' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9getGlobalEjRNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1434' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1446' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1456' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1459' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1461' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1476' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1477' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1479' u='r' c='_ZN3JSC4Wasm14AirIRGenerator9setGlobalEjNS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1526' u='r' c='_ZN3JSC4Wasm14AirIRGenerator28emitWriteBarrierForJSWrapperEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1527' u='r' c='_ZN3JSC4Wasm14AirIRGenerator28emitWriteBarrierForJSWrapperEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1571' u='r' c='_ZN3JSC4Wasm14AirIRGenerator26emitCheckAndPreparePointerENS0_8TypedTmpEjj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1596' u='r' c='_ZN3JSC4Wasm14AirIRGenerator26emitCheckAndPreparePointerENS0_8TypedTmpEjj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1653' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10emitLoadOpENS0_10LoadOpTypeENS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1729' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10emitLoadOpENS0_10LoadOpTypeENS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1827' u='r' c='_ZN3JSC4Wasm14AirIRGenerator11emitStoreOpENS0_11StoreOpTypeENS0_8TypedTmpES3_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1849' u='r' c='_ZN3JSC4Wasm14AirIRGenerator11emitStoreOpENS0_11StoreOpTypeENS0_8TypedTmpES3_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1911' u='r' c='_ZN3JSC4Wasm14AirIRGenerator34fixupPointerPlusOffsetForAtomicOpsENS0_15ExtAtomicOpTypeENS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1933' u='r' c='_ZN3JSC4Wasm14AirIRGenerator20sanitizeAtomicResultENS0_15ExtAtomicOpTypeENS0_4TypeENS_2B33Air3TmpES6_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1950' u='r' c='_ZN3JSC4Wasm14AirIRGenerator20sanitizeAtomicResultENS0_15ExtAtomicOpTypeENS0_4TypeENS_2B33Air3TmpES6_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='1979' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19appendGeneralAtomicENS0_15ExtAtomicOpTypeENS_2B33Air6OpcodeENS3_13CommutativityENS4_3ArgES7_NS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2028' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19appendGeneralAtomicENS0_15ExtAtomicOpTypeENS_2B33Air6OpcodeENS3_13CommutativityENS4_3ArgES7_NS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2050' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19appendGeneralAtomicENS0_15ExtAtomicOpTypeENS_2B33Air6OpcodeENS3_13CommutativityENS4_3ArgES7_NS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2062' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19appendGeneralAtomicENS0_15ExtAtomicOpTypeENS_2B33Air6OpcodeENS3_13CommutativityENS4_3ArgES7_NS0_8TypedTmpE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2090' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15appendStrongCASENS0_15ExtAtomicOpTypeENS0_8TypedTmpES3_NS_2B33Air3ArgES3_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2102' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15appendStrongCASENS0_15ExtAtomicOpTypeENS0_8TypedTmpES3_NS_2B33Air3ArgES3_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2104' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15appendStrongCASENS0_15ExtAtomicOpTypeENS0_8TypedTmpES3_NS_2B33Air3ArgES3_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2110' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15appendStrongCASENS0_15ExtAtomicOpTypeENS0_8TypedTmpES3_NS_2B33Air3ArgES3_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2187' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16emitAtomicLoadOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2194' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16emitAtomicLoadOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2264' u='r' c='_ZN3JSC4Wasm14AirIRGenerator17emitAtomicStoreOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2331' u='r' c='_ZN3JSC4Wasm14AirIRGenerator21emitAtomicBinaryRMWOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2335' u='r' c='_ZN3JSC4Wasm14AirIRGenerator21emitAtomicBinaryRMWOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2419' u='r' c='_ZN3JSC4Wasm14AirIRGenerator21emitAtomicBinaryRMWOpENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2508' u='r' c='_ZN3JSC4Wasm14AirIRGenerator25emitAtomicCompareExchangeENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_S4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2514' u='r' c='_ZN3JSC4Wasm14AirIRGenerator25emitAtomicCompareExchangeENS0_15ExtAtomicOpTypeENS0_4TypeENS0_8TypedTmpES4_S4_j'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2690' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14truncSaturatedENS0_10Ext1OpTypeENS0_8TypedTmpERS3_NS0_4TypeES5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2699' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14truncSaturatedENS0_10Ext1OpTypeENS0_8TypedTmpERS3_NS0_4TypeES5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2703' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14truncSaturatedENS0_10Ext1OpTypeENS0_8TypedTmpERS3_NS0_4TypeES5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2708' u='r' c='_ZN3JSC4Wasm14AirIRGenerator14truncSaturatedENS0_10Ext1OpTypeENS0_8TypedTmpERS3_NS0_4TypeES5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2811' u='r' c='_ZN3JSC4Wasm14AirIRGenerator20emitEntryTierUpCheckEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='2862' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19emitLoopTierUpCheckEjRKN3WTF6VectorINS0_14FunctionParserIS1_E15TypedExpressionELm16ENS2_20UnsafeVectorOverflowELm16ENS2_10FastMallocEEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3194' u='r' c='_ZN3JSC4Wasm14AirIRGenerator7addCallEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3200' u='r' c='_ZN3JSC4Wasm14AirIRGenerator7addCallEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3202' u='r' c='_ZN3JSC4Wasm14AirIRGenerator7addCallEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3232' u='r' c='_ZN3JSC4Wasm14AirIRGenerator7addCallEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3234' u='r' c='_ZN3JSC4Wasm14AirIRGenerator7addCallEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3294' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3296' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3298' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3299' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3300' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3317' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3321' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3331' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3341' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3350' u='r' c='_ZN3JSC4Wasm14AirIRGenerator15addCallIndirectEjRKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3365' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10addCallRefERKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3368' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10addCallRefERKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3369' u='r' c='_ZN3JSC4Wasm14AirIRGenerator10addCallRefERKNS0_9SignatureERN3WTF6VectorINS0_8TypedTmpELm0ENS5_15CrashOnOverflowELm16ENS5_10FastMallocEEERNS6_IS7_Lm8ES8_Lm16ES9_EE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3377' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16emitIndirectCallENS0_8TypedTmpES2_RKNS0_9SignatureERKN3WTF6VectorIS2_Lm0ENS6_15CrashOnOverflowELm16ENS6_10FastMallocEEER15206329'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3423' u='r' c='_ZN3JSC4Wasm14AirIRGenerator16emitIndirectCallENS0_8TypedTmpES2_RKNS0_9SignatureERKN3WTF6VectorIS2_Lm0ENS6_15CrashOnOverflowELm16ENS6_10FastMallocEEER15206329'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3565' u='r' c='_ZN3JSC4Wasm14AirIRGenerator21emitChecksForModOrDivEbNS0_8TypedTmpES2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3568' u='r' c='_ZN3JSC4Wasm14AirIRGenerator21emitChecksForModOrDivEbNS0_8TypedTmpES2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3663' c='_ZN3JSC4Wasm14AirIRGenerator12emitModOrDivEbNS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3671' u='r' c='_ZN3JSC4Wasm14AirIRGenerator12emitModOrDivEbNS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3674' u='r' c='_ZN3JSC4Wasm14AirIRGenerator12emitModOrDivEbNS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3686' u='r' c='_ZN3JSC4Wasm14AirIRGenerator12emitModOrDivEbNS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='3689' u='r' c='_ZN3JSC4Wasm14AirIRGenerator12emitModOrDivEbNS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4199' u='r' c='_ZN3JSC4Wasm14AirIRGenerator8addShiftENS0_4TypeENS_2B33Air6OpcodeENS0_8TypedTmpES6_RS6_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4200' u='r' c='_ZN3JSC4Wasm14AirIRGenerator8addShiftENS0_4TypeENS_2B33Air6OpcodeENS0_8TypedTmpES6_RS6_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4223' u='r' c='_ZN3JSC4Wasm14AirIRGenerator13addIntegerSubENS_2B33Air6OpcodeENS0_8TypedTmpES5_RS5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4243' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19addFloatingPointAbsENS_2B33Air6OpcodeENS0_8TypedTmpERS5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4248' u='r' c='_ZN3JSC4Wasm14AirIRGenerator19addFloatingPointAbsENS_2B33Air6OpcodeENS0_8TypedTmpERS5_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4410' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4414' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4605' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4609' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4630' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmAirIRGenerator.cpp' l='4960' u='r' c='_ZN3JSC4Wasm14AirIRGenerator5addOpENS0_8TypedTmpES2_RS2_'/>
