<dec f='WebKit/Source/JavaScriptCore/b3/B3Opcode.h' l='90' type='18'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Kind.h' l='96' c='_ZNK3JSC2B34Kind10hasIsChillEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.h' l='437' c='_ZN3JSC2B35Value18adjacencyListSpaceENS0_4KindE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.h' l='602' c='_ZN3JSC2B35Value18numChildrenForKindENS0_4KindEj'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='90' c='_ZNK3JSC2B35Value19adjacencyListOffsetEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='90' c='_ZNK3JSC2B35Value9cloneImplEv'/>
<doc f='WebKit/Source/JavaScriptCore/b3/B3Opcode.h' l='90'>// All bets are off as to what will happen when you execute this for -2^31%-1 and x%0.</doc>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='162' u='r' c='_ZN3JSC3FTL6Output3modEPNS_2B35ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='167' u='r' c='_ZN3JSC3FTL6Output8chillModEPNS_2B35ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='197' u='r' c='_ZN3JSC3FTL6Output9doubleModEPNS_2B35ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmB3IRGenerator.cpp' l='2786' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmB3IRGenerator.cpp' l='2822' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='94' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros19processCurrentBlockEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='126' u='r' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros19processCurrentBlockEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2868' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2871' u='r' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Opcode.cpp' l='156' c='_ZN3WTF13printInternalERNS_11PrintStreamEN3JSC2B36OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='975' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Validate.cpp' l='207' c='_ZN3JSC2B312_GLOBAL__N_19Validater3runEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Validate.cpp' l='215' c='_ZN3JSC2B312_GLOBAL__N_19Validater3runEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Validate.cpp' l='217' u='r' c='_ZN3JSC2B312_GLOBAL__N_19Validater3runEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='583' c='_ZNK3JSC2B35Value7effectsEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='718' c='_ZNK3JSC2B35Value3keyEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='816' c='_ZN3JSC2B35Value7typeForENS0_4KindEPS1_S3_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueKey.cpp' l='89' c='_ZNK3JSC2B38ValueKey11materializeERNS0_9ProcedureENS0_6OriginE'/>
