<dec f='WebKit/Source/JavaScriptCore/profiler/ProfilerCompilationKind.h' l='34' type='3'/>
<use f='WebKit/Source/JavaScriptCore/profiler/ProfilerCompilationKind.cpp' l='45' c='_ZN3WTF13printInternalERNS_11PrintStreamEN3JSC8Profiler15CompilationKindE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGPlan.cpp' l='117' u='r' c='_ZN3JSC3DFG12_GLOBAL__N_130profilerCompilationKindForModeENS_18JITCompilationModeE'/>
