<dec f='WebKit/Source/JavaScriptCore/b3/B3Opcode.h' l='86' type='14'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.h' l='433' c='_ZN3JSC2B35Value18adjacencyListSpaceENS0_4KindE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.h' l='598' c='_ZN3JSC2B35Value18numChildrenForKindENS0_4KindEj'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='86' c='_ZNK3JSC2B35Value19adjacencyListOffsetEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueInlines.h' l='86' c='_ZNK3JSC2B35Value9cloneImplEv'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='142' u='r' c='_ZN3JSC3FTL6Output3subEPNS_2B35ValueES4_'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='182' u='r' c='_ZN3JSC3FTL6Output9doubleSubEPNS_2B35ValueES4_'/>
<use f='WebKit/JavaScriptCore/DerivedSources/WasmB3IRGeneratorInlines.h' l='57' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/JavaScriptCore/DerivedSources/WasmB3IRGeneratorInlines.h' l='245' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/JavaScriptCore/DerivedSources/WasmB3IRGeneratorInlines.h' l='449' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/JavaScriptCore/DerivedSources/WasmB3IRGeneratorInlines.h' l='511' u='r' c='_ZN3JSC4Wasm13B3IRGenerator5addOpEPNS_2B35ValueES4_RS4_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='108' u='r' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros19processCurrentBlockEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='154' u='r' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros19processCurrentBlockEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='165' u='r' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros19processCurrentBlockEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerMacros.cpp' l='487' u='r' c='_ZN3JSC2B312_GLOBAL__N_111LowerMacros22recursivelyBuildSwitchERKN3WTF6VectorINS0_10SwitchCaseELm0ENS3_15CrashOnOverflowELm16ENS3_10FastMallocEEENS0_222151505'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='2695' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3LowerToAir.cpp' l='3377' c='_ZN3JSC2B312_GLOBAL__N_110LowerToAir5lowerEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3MoveConstants.cpp' l='213' c='_ZN3JSC2B312_GLOBAL__N_113MoveConstants14hoistConstantsERKT_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3MoveConstants.cpp' l='233' u='r' c='_ZN3JSC2B312_GLOBAL__N_113MoveConstants14hoistConstantsERKT_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Opcode.cpp' l='144' c='_ZN3WTF13printInternalERNS_11PrintStreamEN3JSC2B36OpcodeE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceDoubleToFloat.cpp' l='324' c='_ZN3JSC2B312_GLOBAL__N_122DoubleToFloatReduction8simplifyEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='595' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='602' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='608' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='621' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='709' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='710' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='717' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='719' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='728' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='756' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='757' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='925' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='1020' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='1811' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='2145' u='r' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength19reduceValueStrengthEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ReduceStrength.cpp' l='2751' c='_ZN3JSC2B312_GLOBAL__N_114ReduceStrength8rangeForEPNS0_5ValueEj'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Validate.cpp' l='203' c='_ZN3JSC2B312_GLOBAL__N_19Validater3runEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='540' c='_ZNK3JSC2B35Value7effectsEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='714' c='_ZNK3JSC2B35Value3keyEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3Value.cpp' l='812' c='_ZN3JSC2B35Value7typeForENS0_4KindEPS1_S3_'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3ValueKey.cpp' l='85' c='_ZNK3JSC2B38ValueKey11materializeERNS0_9ProcedureENS0_6OriginE'/>
