<use f='WebKit/Source/JavaScriptCore/b3/B3VariableLiveness.h' l='46' u='w' c='_ZN3JSC2B323VariableLivenessAdapterC1ERNS0_9ProcedureE'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3VariableLiveness.h' l='56' u='m' c='_ZN3JSC2B323VariableLivenessAdapter10numIndicesEv'/>
<use f='WebKit/Source/JavaScriptCore/b3/B3VariableLiveness.h' l='60' u='m' c='_ZN3JSC2B323VariableLivenessAdapter12indexToValueEj'/>
<dec f='WebKit/Source/JavaScriptCore/b3/B3VariableLiveness.h' l='95' type='JSC::B3::Procedure &amp;'/>
<offset>0</offset>
