<dec f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.h' l='75' type='2'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.cpp' l='98' u='r' c='_ZN3JSC16IntlDisplayNames22initializeDisplayNamesEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.cpp' l='98' u='a' c='_ZN3JSC16IntlDisplayNames22initializeDisplayNamesEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.cpp' l='227' c='_ZNK3JSC16IntlDisplayNames2ofEPNS_14JSGlobalObjectENS_7JSValueE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.cpp' l='264' c='_ZNK3JSC16IntlDisplayNames2ofEPNS_14JSGlobalObjectENS_7JSValueE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDisplayNames.cpp' l='326' c='_ZN3JSC16IntlDisplayNames10typeStringENS0_4TypeE'/>
