<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/StackVisitor.h' l='57' type='3'/>
<dec f='WebKit/Source/JavaScriptCore/interpreter/StackVisitor.h' l='57' type='3'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/CallFrame.cpp' l='229' c='_ZN3JSC9CallFrame18callerSourceOriginERNS_2VME'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/StackVisitor.cpp' l='243' u='r' c='_ZNK3JSC12StackVisitor5Frame8codeTypeEv'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/StackVisitor.cpp' l='296' c='_ZNK3JSC12StackVisitor5Frame12functionNameEv'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/StackVisitor.cpp' l='321' c='_ZNK3JSC12StackVisitor5Frame9sourceURLEv'/>
