<dec f='WebKit/Source/JavaScriptCore/wasm/WasmFormat.h' l='344' type='0'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmFormat.h' l='353' c='_ZN3JSC4Wasm15isValidNameTypeET_'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmNameSectionParser.cpp' l='56' c='_ZN3JSC4Wasm17NameSectionParser5parseEv'/>
<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmFormat.h' l='344' type='0'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmFormat.h' l='353' c='_ZN3JSC4Wasm15isValidNameTypeET_'/>
