<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ParserTokens.h' l='181' type='191490'/>
<dec f='WebKit/Source/JavaScriptCore/parser/ParserTokens.h' l='181' type='191490'/>
<use f='WebKit/Source/JavaScriptCore/parser/Lexer.cpp' l='2138' u='r' c='_ZN3JSC5Lexer32lexWithoutClearingLineTerminatorEPNS_7JSTokenEN3WTF9OptionSetINS_10LexerFlagsEEEb'/>
<use f='WebKit/Source/JavaScriptCore/parser/ASTBuilder.h' l='1556' c='_ZN3JSC10ASTBuilder14makeBinaryNodeERKNS_15JSTokenLocationEiSt4pairIPNS_14ExpressionNodeENS0_12BinaryOpInfoEES8_'/>
