<dec f='WebKit/Source/JavaScriptCore/ftl/FTLState.h' l='77' type='std::unique_ptr&lt;B3::Procedure&gt;'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='59' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='61' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='67' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='77' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='82' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='127' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='158' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='162' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='164' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='170' u='m' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<offset>64</offset>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLOutput.cpp' l='48' u='m' c='_ZN3JSC3FTL6OutputC1ERNS0_5StateE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='70' u='w' c='_ZN3JSC3FTL5StateC1ERNS_3DFG5GraphE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='73' u='m' c='_ZN3JSC3FTL5StateC1ERNS_3DFG5GraphE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='75' u='m' c='_ZN3JSC3FTL5StateC1ERNS_3DFG5GraphE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='80' u='m' c='_ZN3JSC3FTL5StateC1ERNS_3DFG5GraphE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='85' u='m' c='_ZN3JSC3FTL5State15dumpDisassemblyERN3WTF11PrintStreamERKNS2_12ScopedLambdaIFvPNS_3DFG4NodeEEEE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='144' u='m' c='_ZN3JSC3FTL5State15dumpDisassemblyERN3WTF11PrintStreamERKNS2_12ScopedLambdaIFvPNS_3DFG4NodeEEEE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='156' u='m' c='_ZN3JSC3FTL5State15dumpDisassemblyERN3WTF11PrintStreamERKNS2_12ScopedLambdaIFvPNS_3DFG4NodeEEEE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp' l='155' u='m' c='_ZN3JSC3FTL12_GLOBAL__N_112LowerDFGToB3C1ERNS0_5StateE'/>
