<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JITCompilationMode.h' l='36' type='3'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JITCompilationMode.h' l='43' c='_ZN3JSC5isFTLENS_18JITCompilationModeE'/>
<dec f='WebKit/Source/JavaScriptCore/jit/JITCompilationMode.h' l='36' type='3'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITCompilationMode.h' l='43' c='_ZN3JSC5isFTLENS_18JITCompilationModeE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.h' l='55' u='r' c='_ZN3JSC3FTL25verboseCompilationEnabledEv'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.h' l='60' u='r' c='_ZN3JSC3FTL21shouldDumpDisassemblyEv'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLink.cpp' l='73' c='_ZN3JSC3FTL4linkERNS0_5StateE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLState.cpp' l='51' c='_ZN3JSC3FTL5StateC1ERNS_3DFG5GraphE'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITCompilationMode.cpp' l='47' c='_ZN3WTF13printInternalERNS_11PrintStreamEN3JSC18JITCompilationModeE'/>
<use f='WebKit/Source/JavaScriptCore/jit/JITPlan.cpp' l='81' c='_ZNK3JSC7JITPlan4tierEv'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGOperations.cpp' l='3813' u='r' c='_ZN3JSC3DFGL28triggerFTLReplacementCompileERNS_2VMEPNS_9CodeBlockEPNS0_7JITCodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGOperations.cpp' l='3841' u='r' c='_ZN3JSC3DFGL28triggerFTLReplacementCompileERNS_2VMEPNS_9CodeBlockEPNS0_7JITCodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGPlan.cpp' l='116' c='_ZN3JSC3DFG12_GLOBAL__N_130profilerCompilationKindForModeENS_18JITCompilationModeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGPlan.cpp' l='351' c='_ZN3JSC3DFG4Plan19compileInThreadImplEv'/>
