<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Debugger.h' l='155' ll='166'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Debugger.h' l='172' c='_ZN3JSC8Debugger8Observer14didParseSourceEmRKNS0_6ScriptE'/>
<size>64</size>
<doc f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Debugger.h' l='154'>// FIXME: &lt;https://webkit.org/b/162773&gt; Web Inspector: Simplify Debugger::Script to use SourceProvider</doc>
<mbr r='JSC::Debugger::Script::url' o='0' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::source' o='64' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceURL' o='128' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceMappingURL' o='192' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceProvider' o='256' t='RefPtr&lt;JSC::SourceProvider&gt;'/>
<mbr r='JSC::Debugger::Script::startLine' o='320' t='int'/>
<mbr r='JSC::Debugger::Script::startColumn' o='352' t='int'/>
<mbr r='JSC::Debugger::Script::endLine' o='384' t='int'/>
<mbr r='JSC::Debugger::Script::endColumn' o='416' t='int'/>
<mbr r='JSC::Debugger::Script::isContentScript' o='448' t='bool'/>
<def f='WebKit/Source/JavaScriptCore/debugger/Debugger.h' l='155' ll='166'/>
<use f='WebKit/Source/JavaScriptCore/debugger/Debugger.h' l='172' c='_ZN3JSC8Debugger8Observer14didParseSourceEmRKNS0_6ScriptE'/>
<size>64</size>
<doc f='WebKit/Source/JavaScriptCore/debugger/Debugger.h' l='154'>// FIXME: &lt;https://webkit.org/b/162773&gt; Web Inspector: Simplify Debugger::Script to use SourceProvider</doc>
<mbr r='JSC::Debugger::Script::url' o='0' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::source' o='64' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceURL' o='128' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceMappingURL' o='192' t='WTF::String'/>
<mbr r='JSC::Debugger::Script::sourceProvider' o='256' t='RefPtr&lt;JSC::SourceProvider&gt;'/>
<mbr r='JSC::Debugger::Script::startLine' o='320' t='int'/>
<mbr r='JSC::Debugger::Script::startColumn' o='352' t='int'/>
<mbr r='JSC::Debugger::Script::endLine' o='384' t='int'/>
<mbr r='JSC::Debugger::Script::endColumn' o='416' t='int'/>
<mbr r='JSC::Debugger::Script::isContentScript' o='448' t='bool'/>
<use f='WebKit/Source/JavaScriptCore/debugger/Debugger.cpp' l='306' c='_ZN3JSC8Debugger12sourceParsedEPNS_14JSGlobalObjectEPNS_14SourceProviderEiRKN3WTF6StringE'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.h' l='101' c='_ZN9Inspector22InspectorDebuggerAgent14didParseSourceEmRKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.h' l='161' c='_ZN9Inspector22InspectorDebuggerAgent21sourceMapURLForScriptERKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.h' l='206' c='_ZN9Inspector22InspectorDebuggerAgent17resolveBreakpointERKN3JSC8Debugger6ScriptERNS1_10BreakpointE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.h' l='235'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.cpp' l='625' c='_ZN9Inspector22InspectorDebuggerAgent17resolveBreakpointERKN3JSC8Debugger6ScriptERNS1_10BreakpointE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.cpp' l='1087' c='_ZN9Inspector22InspectorDebuggerAgent21sourceMapURLForScriptERKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.cpp' l='1121' c='_ZN9Inspector22InspectorDebuggerAgent14didParseSourceEmRKN3JSC8Debugger6ScriptE'/>
<size>64</size>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorDebuggerAgent.h' l='101' c='_ZN9Inspector22InspectorDebuggerAgent14didParseSourceEmRKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorDebuggerAgent.h' l='161' c='_ZN9Inspector22InspectorDebuggerAgent21sourceMapURLForScriptERKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorDebuggerAgent.h' l='206' c='_ZN9Inspector22InspectorDebuggerAgent17resolveBreakpointERKN3JSC8Debugger6ScriptERNS1_10BreakpointE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/InspectorDebuggerAgent.h' l='235'/>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.h' l='75' c='_ZN7WebCore17PageDebuggerAgent21sourceMapURLForScriptERKN3JSC8Debugger6ScriptE'/>
<size>64</size>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.cpp' l='91' c='_ZN7WebCore17PageDebuggerAgent21sourceMapURLForScriptERKN3JSC8Debugger6ScriptE'/>
<size>64</size>
