<dec f='WebKit/Source/JavaScriptCore/runtime/IntlObject.h' l='52' type='5'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlNumberFormat.cpp' l='292' u='r' c='_ZN3JSC16IntlNumberFormat22initializeNumberFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlNumberFormat.cpp' l='296' u='r' c='_ZN3JSC16IntlNumberFormat22initializeNumberFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlNumberFormat.cpp' l='296' u='r' c='_ZN3JSC16IntlNumberFormat22initializeNumberFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlNumberFormat.cpp' l='304' u='r' c='_ZN3JSC16IntlNumberFormat22initializeNumberFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlObject.cpp' l='847' macro='1' c='_ZN3JSC26relevantExtensionKeyStringENS_20RelevantExtensionKeyE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlRelativeTimeFormat.cpp' l='106' u='r' c='_ZN3JSC22IntlRelativeTimeFormat28initializeRelativeTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlRelativeTimeFormat.cpp' l='110' u='r' c='_ZN3JSC22IntlRelativeTimeFormat28initializeRelativeTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlRelativeTimeFormat.cpp' l='110' u='r' c='_ZN3JSC22IntlRelativeTimeFormat28initializeRelativeTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlRelativeTimeFormat.cpp' l='117' u='r' c='_ZN3JSC22IntlRelativeTimeFormat28initializeRelativeTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='187' c='_ZN3JSC18IntlDateTimeFormat10localeDataERKN3WTF6StringENS_20RelevantExtensionKeyE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='552' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='570' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='570' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp' l='587' u='r' c='_ZN3JSC18IntlDateTimeFormat24initializeDateTimeFormatEPNS_14JSGlobalObjectENS_7JSValueES3_'/>
