<dec f='WebKit/Source/JavaScriptCore/assembler/LinkBuffer.h' l='90' type='2'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCompile.cpp' l='150' u='a' c='_ZN3JSC3FTL7compileERNS0_5StateERNS_9Safepoint6ResultE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLazySlowPath.cpp' l='65' u='r' c='_ZN3JSC3FTL12LazySlowPath8generateEPNS_9CodeBlockE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLink.cpp' l='116' u='a' c='_ZN3JSC3FTL4linkERNS0_5StateE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLink.cpp' l='145' u='a' c='_ZN3JSC3FTL4linkERNS0_5StateE'/>
<use f='WebKit/Source/JavaScriptCore/assembler/LinkBuffer.cpp' l='566' macro='1' c='_ZN3JSC10LinkBuffer21dumpProfileStatisticsESt8optionalIPN3WTF11PrintStreamEE'/>
<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/LinkBuffer.h' l='90' type='2'/>
