<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Breakpoint.h' l='45' ll='59'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Breakpoint.h' l='61'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Debugger.h' l='148' c='_ZN3JSC8Debugger6Client20debuggerWillEvaluateERS0_RKNS_10Breakpoint6ActionE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/Debugger.h' l='149' c='_ZN3JSC8Debugger6Client19debuggerDidEvaluateERS0_RKNS_10Breakpoint6ActionE'/>
<size>24</size>
<fun r='_ZN3JSC10Breakpoint6ActionC1ENS1_4TypeE'/>
<mbr r='JSC::Breakpoint::Action::type' o='0' t='JSC::Breakpoint::Action::Type'/>
<mbr r='JSC::Breakpoint::Action::data' o='64' t='WTF::String'/>
<mbr r='JSC::Breakpoint::Action::id' o='128' t='JSC::BreakpointActionID'/>
<mbr r='JSC::Breakpoint::Action::emulateUserGesture' o='160' t='bool'/>
<def f='WebKit/Source/JavaScriptCore/debugger/Breakpoint.h' l='45' ll='59'/>
<use f='WebKit/Source/JavaScriptCore/debugger/Breakpoint.h' l='61'/>
<use f='WebKit/Source/JavaScriptCore/debugger/Debugger.h' l='148' c='_ZN3JSC8Debugger6Client20debuggerWillEvaluateERS0_RKNS_10Breakpoint6ActionE'/>
<use f='WebKit/Source/JavaScriptCore/debugger/Debugger.h' l='149' c='_ZN3JSC8Debugger6Client19debuggerDidEvaluateERS0_RKNS_10Breakpoint6ActionE'/>
<size>24</size>
<fun r='_ZN3JSC10Breakpoint6ActionC1ENS1_4TypeE'/>
<mbr r='JSC::Breakpoint::Action::type' o='0' t='JSC::Breakpoint::Action::Type'/>
<mbr r='JSC::Breakpoint::Action::data' o='64' t='WTF::String'/>
<mbr r='JSC::Breakpoint::Action::id' o='128' t='JSC::BreakpointActionID'/>
<mbr r='JSC::Breakpoint::Action::emulateUserGesture' o='160' t='bool'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.cpp' l='126' c='_ZN9InspectorL22parseBreakpointOptionsERN3WTF6StringEONS0_6RefPtrINS0_8JSONImpl6ObjectENS0_12RawPtrTraitsIS5_EENS0_21DefaultRefDerefTraitsIS5_EEEENS0_9726839'/>
<size>24</size>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.h' l='56' c='_ZN7WebCore17PageDebuggerAgent20debuggerWillEvaluateERN3JSC8DebuggerERKNS1_10Breakpoint6ActionE'/>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.h' l='57' c='_ZN7WebCore17PageDebuggerAgent19debuggerDidEvaluateERN3JSC8DebuggerERKNS1_10Breakpoint6ActionE'/>
<size>24</size>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.cpp' l='122' c='_ZN7WebCore17PageDebuggerAgent20debuggerWillEvaluateERN3JSC8DebuggerERKNS1_10Breakpoint6ActionE'/>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.cpp' l='128' c='_ZN7WebCore17PageDebuggerAgent19debuggerDidEvaluateERN3JSC8DebuggerERKNS1_10Breakpoint6ActionE'/>
<size>24</size>
