<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ConsoleTypes.h' l='34' type='1'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/ConsoleTypes.h' l='85'/>
<use f='WebKit/Source/WebKit/WebProcess/Network/WebResourceLoader.cpp' l='234' u='r' c='_ZN6WebKit17WebResourceLoader24didFailServiceWorkerLoadERKN7WebCore13ResourceErrorE'/>
<use f='WebKit/Source/WebKit/WebProcess/Network/WebResourceLoader.cpp' l='236' u='r' c='_ZN6WebKit17WebResourceLoader24didFailServiceWorkerLoadERKN7WebCore13ResourceErrorE'/>
<dec f='WebKit/Source/JavaScriptCore/runtime/ConsoleTypes.h' l='34' type='1'/>
<use f='WebKit/Source/JavaScriptCore/runtime/ConsoleTypes.h' l='85'/>
<use f='WebKit/Source/JavaScriptCore/inspector/ConsoleMessage.cpp' l='181' c='_ZN9InspectorL18messageSourceValueEN3JSC13MessageSourceE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.cpp' l='193' u='r' c='_ZN9Inspector33JSGlobalObjectInspectorController18reportAPIExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.cpp' l='195' u='r' c='_ZN9Inspector33JSGlobalObjectInspectorController18reportAPIExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.cpp' l='198' u='a' c='_ZN9Inspector33JSGlobalObjectInspectorController18reportAPIExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/JSGlobalObjectDebuggerAgent.cpp' l='60' u='a' c='_ZN9Inspector27JSGlobalObjectDebuggerAgent19breakpointActionLogEPN3JSC14JSGlobalObjectERKN3WTF6StringE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/ConsoleClient.cpp' l='68' c='_ZN3JSCL19appendMessagePrefixERN3WTF13StringBuilderENS_13MessageSourceENS_11MessageTypeENS_12MessageLevelE'/>
<use f='WebKit/Source/WebCore/testing/Internals.cpp' l='4729' u='r' c='_ZN7WebCore9Internals14queueMicroTaskEi'/>
<use f='WebKit/Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitConsoleMessage.cpp' l='74' c='_Z33webkit_console_message_get_sourceP21_WebKitConsoleMessage'/>
<use f='WebKit/Source/WebCore/css/CSSKeyframesRule.cpp' l='170' u='r' c='_ZN7WebCore16CSSKeyframesRule10insertRuleERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/xml/XMLHttpRequest.cpp' l='98' u='r' c='_ZN7WebCoreL15logConsoleErrorEPNS_22ScriptExecutionContextERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/xml/XMLHttpRequest.cpp' l='529' u='r' c='_ZN7WebCore14XMLHttpRequest4sendERNS_4BlobE'/>
<use f='WebKit/Source/WebCore/xml/XMLHttpRequest.cpp' l='571' u='r' c='_ZN7WebCore14XMLHttpRequest4sendERN3JSC11ArrayBufferE'/>
<use f='WebKit/Source/WebCore/Modules/mediasource/MediaSource.cpp' l='1178' u='r' c='_ZN7WebCore11MediaSource22failedToCreateRendererENS_24MediaSourcePrivateClient12RendererTypeE'/>
<use f='WebKit/Source/WebCore/Modules/cache/DOMCacheEngine.cpp' l='63' u='r' c='_ZN7WebCore14DOMCacheEngine24convertToExceptionAndLogEPNS_22ScriptExecutionContextENS0_5ErrorE'/>
<use f='WebKit/Source/WebCore/Modules/cache/DOMCacheStorage.cpp' l='180' u='r' c='_ZN7WebCoreL26logConsolePersistencyErrorEPNS_22ScriptExecutionContextERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/Modules/webaudio/IIRFilterNode.cpp' l='102' u='r' c='_ZN7WebCore13IIRFilterNode6createERNS_22ScriptExecutionContextERNS_16BaseAudioContextEONS_16IIRFilterOptionsE'/>
<use f='WebKit/Source/WebCore/Modules/webaudio/OfflineAudioContext.cpp' l='51' u='r' c='_ZN7WebCore19OfflineAudioContextC1ERNS_8DocumentERKNS_26OfflineAudioContextOptionsE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='235' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='241' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='246' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='262' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='290' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='298' u='r' c='_ZN7WebCore9WebSocket7connectERKN3WTF6StringERKNS1_6VectorIS2_Lm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='420' u='r' c='_ZN7WebCore9WebSocket5closeESt8optionalItERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/WebSocket.cpp' l='490' u='r' c='_ZN7WebCore9WebSocket13setBinaryTypeERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/Modules/fetch/FetchRequest.cpp' l='151' u='r' c='_ZN7WebCoreL20processInvalidSignalERNS_22ScriptExecutionContextE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptController.cpp' l='339' u='a' c='_ZN7WebCore16ScriptController25setupModuleScriptHandlersERNS_20LoadableModuleScriptERN3JSC17JSInternalPromiseERNS_15DOMWrapperWorldE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptController.cpp' l='339' u='a' c='_ZN7WebCore16ScriptController25setupModuleScriptHandlersERNS_20LoadableModuleScriptERN3JSC17JSInternalPromiseERNS_15DOMWrapperWorldE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptController.cpp' l='339' u='a' c='_ZN7WebCore16ScriptController25setupModuleScriptHandlersERNS_20LoadableModuleScriptERN3JSC17JSInternalPromiseERNS_15DOMWrapperWorldE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptController.cpp' l='339' u='a' c='_ZN7WebCore16ScriptController25setupModuleScriptHandlersERNS_20LoadableModuleScriptERN3JSC17JSInternalPromiseERNS_15DOMWrapperWorldE'/>
<use f='WebKit/Source/WebCore/bindings/js/JSDOMWindowCustom.cpp' l='298' u='r' c='_ZN7WebCore11JSDOMWindow10putByIndexEPN3JSC6JSCellEPNS1_14JSGlobalObjectEjNS1_7JSValueEb'/>
<use f='WebKit/Source/WebCore/page/DOMWindow.cpp' l='1046' u='r' c='_ZN7WebCore9DOMWindow5closeEv'/>
<use f='WebKit/Source/WebCore/page/DOMWindow.cpp' l='1864' u='r' c='_ZN7WebCore9DOMWindow27webkitRequestAnimationFrameEON3WTF3RefINS_29RequestAnimationFrameCallbackENS1_12RawPtrTraitsIS3_EEEE'/>
<use f='WebKit/Source/WebCore/page/DOMWindow.cpp' l='2409' u='r' c='_ZNK7WebCore9DOMWindow17printErrorMessageERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/page/EventSource.cpp' l='175' u='r' c='_ZNK7WebCore11EventSource15responseIsValidERKNS_16ResourceResponseE'/>
<use f='WebKit/Source/WebCore/page/EventSource.cpp' l='185' u='r' c='_ZNK7WebCore11EventSource15responseIsValidERKNS_16ResourceResponseE'/>
<use f='WebKit/Source/WebCore/inspector/agents/page/PageDebuggerAgent.cpp' l='136' u='r' c='_ZN7WebCore17PageDebuggerAgent19breakpointActionLogEPN3JSC14JSGlobalObjectERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/inspector/agents/worker/WorkerDebuggerAgent.cpp' l='53' u='a' c='_ZN7WebCore19WorkerDebuggerAgent19breakpointActionLogEPN3JSC14JSGlobalObjectERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/html/HTMLPlugInElement.cpp' l='425' u='r' c='_ZN7WebCore17HTMLPlugInElement14setReplacementENS_20RenderEmbeddedObject26PluginUnavailabilityReasonERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/html/parser/XSSAuditorDelegate.cpp' l='88' u='r' c='_ZN7WebCore18XSSAuditorDelegate14didBlockScriptERKNS_7XSSInfoE'/>
<use f='WebKit/Source/WebCore/html/HTMLCanvasElement.cpp' l='373' u='r' c='_ZN7WebCore17HTMLCanvasElement15createContext2dERKN3WTF6StringEONS_32CanvasRenderingContext2DSettingsE'/>
<use f='WebKit/Source/WebCore/html/HTMLCanvasElement.cpp' l='938' u='r' c='_ZNK7WebCore17HTMLCanvasElement17createImageBufferEv'/>
<use f='WebKit/Source/WebCore/html/HTMLCanvasElement.cpp' l='946' u='r' c='_ZNK7WebCore17HTMLCanvasElement17createImageBufferEv'/>
<use f='WebKit/Source/WebCore/dom/LoadableClassicScript.cpp' l='82' u='a' c='_ZN7WebCore21LoadableClassicScript14notifyFinishedERNS_14CachedResourceERKNS_18NetworkLoadMetricsE'/>
<use f='WebKit/Source/WebCore/dom/LoadableClassicScript.cpp' l='82' u='a' c='_ZN7WebCore21LoadableClassicScript14notifyFinishedERNS_14CachedResourceERKNS_18NetworkLoadMetricsE'/>
<use f='WebKit/Source/WebCore/dom/LoadableClassicScript.cpp' l='82' u='a' c='_ZN7WebCore21LoadableClassicScript14notifyFinishedERNS_14CachedResourceERKNS_18NetworkLoadMetricsE'/>
<use f='WebKit/Source/WebCore/dom/LoadableClassicScript.cpp' l='82' u='a' c='_ZN7WebCore21LoadableClassicScript14notifyFinishedERNS_14CachedResourceERKNS_18NetworkLoadMetricsE'/>
<use f='WebKit/Source/WebCore/dom/ScriptExecutionContext.cpp' l='441' u='a' c='_ZN7WebCore22ScriptExecutionContext31reportUnhandledPromiseRejectionERN3JSC14JSGlobalObjectERNS1_9JSPromiseEON3WTF6RefPtrIN9Inspector15ScriptCallStack5682128'/>
<use f='WebKit/Source/WebCore/dom/ScriptExecutionContext.cpp' l='443' u='a' c='_ZN7WebCore22ScriptExecutionContext31reportUnhandledPromiseRejectionERN3JSC14JSGlobalObjectERNS1_9JSPromiseEON3WTF6RefPtrIN9Inspector15ScriptCallStack5682128'/>
<use f='WebKit/Source/WebCore/dom/Document.cpp' l='3393' u='r' c='_ZN7WebCore8Document21logExceptionToConsoleERKN3WTF6StringES4_iiONS1_6RefPtrIN9Inspector15ScriptCallStackENS1_12RawPtrTraitsIS7_EENS1_21DefaultRefDerefTraitsIS7_EEEE'/>
<use f='WebKit/Source/WebCore/loader/FrameLoader.cpp' l='3384' u='r' c='_ZN7WebCore11FrameLoader25dispatchBeforeUnloadEventERNS_6ChromeEPS0_'/>
<use f='WebKit/Source/WebCore/loader/FrameLoader.cpp' l='3397' u='r' c='_ZN7WebCore11FrameLoader25dispatchBeforeUnloadEventERNS_6ChromeEPS0_'/>
<use f='WebKit/Source/WebCore/loader/FrameLoader.cpp' l='3648' u='r' c='_ZN7WebCore11FrameLoader35shouldInterruptLoadForXFrameOptionsERKN3WTF6StringERKNS1_3URLEm'/>
<use f='WebKit/Source/WebCore/loader/FrameLoader.cpp' l='3651' u='r' c='_ZN7WebCore11FrameLoader35shouldInterruptLoadForXFrameOptionsERKN3WTF6StringERKNS1_3URLEm'/>
<use f='WebKit/Source/WebCore/loader/ThreadableLoader.cpp' l='153' u='r' c='_ZN7WebCore16ThreadableLoader8logErrorERNS_22ScriptExecutionContextERKNS_13ResourceErrorERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/workers/WorkerOrWorkletScriptController.cpp' l='322' u='a' c='_ZN7WebCore31WorkerOrWorkletScriptController23loadModuleSynchronouslyERNS_19WorkerScriptFetcherERKNS_16ScriptSourceCodeE'/>
<use f='WebKit/Source/WebCore/workers/WorkerOrWorkletScriptController.cpp' l='322' u='a' c='_ZN7WebCore31WorkerOrWorkletScriptController23loadModuleSynchronouslyERNS_19WorkerScriptFetcherERKNS_16ScriptSourceCodeE'/>
<use f='WebKit/Source/WebCore/workers/WorkerOrWorkletScriptController.cpp' l='322' u='a' c='_ZN7WebCore31WorkerOrWorkletScriptController23loadModuleSynchronouslyERNS_19WorkerScriptFetcherERKNS_16ScriptSourceCodeE'/>
<use f='WebKit/Source/WebCore/workers/WorkerOrWorkletScriptController.cpp' l='322' u='a' c='_ZN7WebCore31WorkerOrWorkletScriptController23loadModuleSynchronouslyERNS_19WorkerScriptFetcherERKNS_16ScriptSourceCodeE'/>
