<use f='WebKit/Source/WebCore/bindings/js/SerializedScriptValue.h' l='65'/>
<inh f='WebKit/WTF/Headers/wtf/ThreadSafeRefCounted.h' l='109' c='WTF::ThreadSafeRefCounted'/>
<def f='WebKit/Source/JavaScriptCore/wasm/WasmModule.h' l='45' ll='77'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmModule.h' l='45'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmModule.h' l='47'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmModule.h' l='54' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmModule.h' l='56' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<size>64</size>
<fun r='_ZN3JSC4Wasm6Module12validateSyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<fun r='_ZN3JSC4Wasm6Module13validateAsyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEEONS4_6RefPtrINS4_10SharedTaskIFvONSt10365771'/>
<fun r='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<fun r='_ZNK3JSC4Wasm6Module36signatureIndexFromFunctionIndexSpaceEj'/>
<fun r='_ZNK3JSC4Wasm6Module17moduleInformationEv'/>
<fun r='_ZN3JSC4Wasm6Module11compileSyncEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module12compileAsyncEPNS0_7ContextENS0_10MemoryModeEON3WTF6RefPtrINS5_10SharedTaskIFvONS5_3RefINS0_9CodeBlockENS5_12RawPtrTraitsIS9_EEEEE8450788'/>
<fun r='_ZN3JSC4Wasm6ModuleD1Ev'/>
<fun r='_ZN3JSC4Wasm6Module12codeBlockForENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module20getOrCreateCodeBlockEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6ModuleC1ERNS0_9LLIntPlanE'/>
<mbr r='JSC::Wasm::Module::m_moduleInformation' o='64' t='Ref&lt;JSC::Wasm::ModuleInformation&gt;'/>
<mbr r='JSC::Wasm::Module::m_codeBlocks' o='128' t='RefPtr&lt;JSC::Wasm::CodeBlock&gt; [2]'/>
<mbr r='JSC::Wasm::Module::m_llintCallees' o='256' t='RefPtr&lt;JSC::Wasm::LLIntCallees&gt;'/>
<mbr r='JSC::Wasm::Module::m_llintEntryThunks' o='320' t='MacroAssemblerCodeRef&lt;JITCompilationPtrTag&gt;'/>
<mbr r='JSC::Wasm::Module::m_lock' o='448' t='WTF::Lock'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.h' l='57' c='_ZN3JSC4Wasm8Instance6createEPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.h' l='74' c='_ZN3JSC4Wasm8Instance6moduleEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.h' l='214' c='_ZN3JSC4Wasm8InstanceC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.h' l='224'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.h' l='64' c='_ZN3JSC21JSWebAssemblyInstance9tryCreateERNS_2VMEPNS_14JSGlobalObjectERKNS_10IdentifierEPNS_19JSWebAssemblyModuleEPNS_8JSObjectEPNS_9StructureEON3WTF313901825'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.cpp' l='42' c='_ZN3JSC4Wasm12_GLOBAL__N_120globalMemoryByteSizeERNS0_6ModuleE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.cpp' l='48' c='_ZN3JSC4Wasm8InstanceC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmInstance.cpp' l='88' c='_ZN3JSC4Wasm8Instance6createEPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEPPNS_10EntryFrameEPPvONS4_8FunctionIFvSE_EEE'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGForOSREntryPlan.h' l='51' c='_ZN3JSC4Wasm18OMGForOSREntryPlanC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEONS5_INS0_6CalleeENS7_ISB_EEEEjjNS0_10MemoryModeEONS860654'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGForOSREntryPlan.h' l='64'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGForOSREntryPlan.cpp' l='48' c='_ZN3JSC4Wasm18OMGForOSREntryPlanC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEONS5_INS0_6CalleeENS7_ISB_EEEEjjNS0_10MemoryModeEONS860654'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGPlan.h' l='49' c='_ZN3JSC4Wasm7OMGPlanC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEjNS0_10MemoryModeEONS4_6RefPtrINS4_10SharedTaskIFvRNS0_4PlanEEEE7855961'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGPlan.h' l='62'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOMGPlan.cpp' l='47' c='_ZN3JSC4Wasm7OMGPlanC1EPNS0_7ContextEON3WTF3RefINS0_6ModuleENS4_12RawPtrTraitsIS6_EEEEjNS0_10MemoryModeEONS4_6RefPtrINS4_10SharedTaskIFvRNS0_4PlanEEEE7855961'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOperations.cpp' l='98' c='_ZN3JSC4WasmL28triggerOMGReplacementCompileERNS0_11TierUpCountEPNS0_9OMGCalleeEPNS0_8InstanceERNS0_9CodeBlockEj'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmOperations.cpp' l='398' c='_ZN3JSC4Wasm31operationWasmTriggerOSREntryNowERNS_5Probe7ContextE'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmSlowPaths.cpp' l='135' c='_ZN3JSC5LLInt26jitCompileAndSetHeuristicsEPNS_4Wasm11LLIntCalleeEPNS1_17FunctionCodeBlockEPNS1_8InstanceE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/WasmSlowPaths.cpp' l='229' c='JSC::LLInt::slow_path_wasm_loop_osr'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.h' l='66' c='_ZN3JSC19JSWebAssemblyModule10createStubERNS_2VMEPNS_14JSGlobalObjectEPNS_9StructureEONSt12experimental15fundamentals_v38expectedIN3WTF6RefPtrINS_4Was5992865'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.h' l='76' c='_ZN3JSC19JSWebAssemblyModule6moduleEv'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.h' l='81' c='_ZN3JSC19JSWebAssemblyModuleC1ERNS_2VMEPNS_9StructureEON3WTF3RefINS_4Wasm6ModuleENS5_12RawPtrTraitsIS8_EEEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.h' l='85'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssembly.cpp' l='193' c='_ZN3JSCL11instantiateERNS_2VMEPNS_14JSGlobalObjectEPNS_9JSPromiseEPNS_19JSWebAssemblyModuleEPNS_8JSObjectERKNS_10IdentifierENS_7ResolveENS_4Wasm12CreationModeE'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.cpp' l='160' c='_ZN3JSC21JSWebAssemblyInstance9tryCreateERNS_2VMEPNS_14JSGlobalObjectERKNS_10IdentifierEPNS_19JSWebAssemblyModuleEPNS_8JSObjectEPNS_9StructureEON3WTF313901825'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.cpp' l='64' c='_ZN3JSC19JSWebAssemblyModuleC1ERNS_2VMEPNS_9StructureEON3WTF3RefINS_4Wasm6ModuleENS5_12RawPtrTraitsIS8_EEEE'/>
<use f='WebKit/Source/JavaScriptCore/wasm/js/JSWebAssemblyModule.cpp' l='117' c='_ZN3JSC19JSWebAssemblyModule6moduleEv'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/js/WebAssemblyInstanceConstructor.cpp' l='72' c='_ZN3JSCL30constructJSWebAssemblyInstanceEPNS_14JSGlobalObjectEPNS_9CallFrameE'/>
<size>64</size>
<use f='WebKit/Source/JavaScriptCore/wasm/js/WebAssemblyModuleRecord.cpp' l='616' c='_ZN3JSC23WebAssemblyModuleRecord8evaluateEPNS_14JSGlobalObjectE'/>
<size>64</size>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSWebAssemblyModule.h' l='66' c='_ZN3JSC19JSWebAssemblyModule10createStubERNS_2VMEPNS_14JSGlobalObjectEPNS_9StructureEONSt12experimental15fundamentals_v38expectedIN3WTF6RefPtrINS_4Was5992865'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSWebAssemblyModule.h' l='76' c='_ZN3JSC19JSWebAssemblyModule6moduleEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSWebAssemblyModule.h' l='81' c='_ZN3JSC19JSWebAssemblyModuleC1ERNS_2VMEPNS_9StructureEON3WTF3RefINS_4Wasm6ModuleENS5_12RawPtrTraitsIS8_EEEE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSWebAssemblyModule.h' l='85'/>
<inh f='WebKit/WTF/Headers/wtf/ThreadSafeRefCounted.h' l='109' c='WTF::ThreadSafeRefCounted'/>
<def f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmModule.h' l='45' ll='77'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmModule.h' l='45'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmModule.h' l='47'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmModule.h' l='54' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/WasmModule.h' l='56' c='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<size>64</size>
<fun r='_ZN3JSC4Wasm6Module12validateSyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEE'/>
<fun r='_ZN3JSC4Wasm6Module13validateAsyncEPNS0_7ContextEON3WTF6VectorIhLm0ENS4_15CrashOnOverflowELm16ENS4_10FastMallocEEEONS4_6RefPtrINS4_10SharedTaskIFvONSt10365771'/>
<fun r='_ZN3JSC4Wasm6Module6createERNS0_9LLIntPlanE'/>
<fun r='_ZNK3JSC4Wasm6Module36signatureIndexFromFunctionIndexSpaceEj'/>
<fun r='_ZNK3JSC4Wasm6Module17moduleInformationEv'/>
<fun r='_ZN3JSC4Wasm6Module11compileSyncEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module12compileAsyncEPNS0_7ContextENS0_10MemoryModeEON3WTF6RefPtrINS5_10SharedTaskIFvONS5_3RefINS0_9CodeBlockENS5_12RawPtrTraitsIS9_EEEEE8450788'/>
<fun r='_ZN3JSC4Wasm6ModuleD1Ev'/>
<fun r='_ZN3JSC4Wasm6Module12codeBlockForENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6Module20getOrCreateCodeBlockEPNS0_7ContextENS0_10MemoryModeE'/>
<fun r='_ZN3JSC4Wasm6ModuleC1ERNS0_9LLIntPlanE'/>
<mbr r='JSC::Wasm::Module::m_moduleInformation' o='64' t='Ref&lt;JSC::Wasm::ModuleInformation&gt;'/>
<mbr r='JSC::Wasm::Module::m_codeBlocks' o='128' t='RefPtr&lt;JSC::Wasm::CodeBlock&gt; [2]'/>
<mbr r='JSC::Wasm::Module::m_llintCallees' o='256' t='RefPtr&lt;JSC::Wasm::LLIntCallees&gt;'/>
<mbr r='JSC::Wasm::Module::m_llintEntryThunks' o='320' t='MacroAssemblerCodeRef&lt;JITCompilationPtrTag&gt;'/>
<mbr r='JSC::Wasm::Module::m_lock' o='448' t='WTF::Lock'/>
