<dec f='WebKit/Source/JavaScriptCore/runtime/JSGenerator.h' l='58' type='0'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/Source/JavaScriptCore/runtime/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSGenerator.h' l='58' type='0'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/JSGenerator.h' l='86' u='r' c='_ZN3JSC11JSGenerator13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
<use f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/AbstractModuleRecord.h' l='67' u='r' c='_ZN3JSC20AbstractModuleRecord13initialValuesEv'/>
