<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/SourceProvider.h' l='46' type='1'/>
<dec f='WebKit/Source/JavaScriptCore/parser/SourceProvider.h' l='46' type='1'/>
<use f='WebKit/Source/JavaScriptCore/debugger/DebuggerParseData.cpp' l='161' c='_ZN3JSC32gatherDebuggerParseDataForSourceERNS_2VMEPNS_14SourceProviderERNS_17DebuggerParseDataE'/>
<use f='WebKit/Source/JavaScriptCore/inspector/agents/InspectorDebuggerAgent.cpp' l='1128' u='r' c='_ZN9Inspector22InspectorDebuggerAgent14didParseSourceEmRKN3JSC8Debugger6ScriptE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/CachedTypes.cpp' l='1625' c='_ZN3JSC20CachedSourceProvider6encodeERNS_7EncoderERKNS_14SourceProviderE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/CachedTypes.cpp' l='1642' c='_ZNK3JSC20CachedSourceProvider6decodeERNS_7DecoderE'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='1213' u='r' c='_ZN12GlobalObject17moduleLoaderFetchEPN3JSC14JSGlobalObjectEPNS0_14JSModuleLoaderENS0_7JSValueES5_S5_'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='2520' u='r' c='_ZL25functionCheckModuleSyntaxPN3JSC14JSGlobalObjectEPNS_9CallFrameE'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='3048' u='r' c='_ZL14runWithOptionsP12GlobalObjectR11CommandLineRb'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='413' u='r' c='_ZN7WebCore18ScriptModuleLoader14notifyFinishedERNS_18ModuleScriptLoaderEON3WTF3URLENS3_3RefINS_15DeferredPromiseENS3_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='461' u='r' c='_ZN7WebCore18ScriptModuleLoader14notifyFinishedERNS_18ModuleScriptLoaderEON3WTF3URLENS3_3RefINS_15DeferredPromiseENS3_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='366' u='r' c='_ZN7WebCore13ScriptElement19requestModuleScriptERKN3WTF12TextPositionE'/>
<use f='WebKit/Source/WebCore/workers/WorkerThread.cpp' l='136' u='r' c='_ZN7WebCore12WorkerThread25evaluateScriptIfNecessaryERN3WTF6StringE'/>
