<dec f='WebKit/Source/JavaScriptCore/dfg/DFGNodeType.h' l='182' type='80'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGNodeType.h' l='182' c='_ZN3JSC3DFG12defaultFlagsENS0_8NodeTypeE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLCapabilities.cpp' l='107' c='_ZN3JSC3FTL10canCompileEPNS_3DFG4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGClobberize.h' l='752' c='_ZN3JSC3DFG10clobberizeERNS0_5GraphEPNS0_4NodeERKT_RKT0_RKT1_RKT2_'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp' l='305' c='_ZN3JSC3DFG12_GLOBAL__N_126PredictionPropagationPhase9propagateEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp' l='1273' c='_ZN3JSC3DFG12_GLOBAL__N_126PredictionPropagationPhase24processInvariantsForNodeEv'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGAbstractInterpreterInlines.h' l='995' c='_ZN3JSC3DFG19AbstractInterpreter14executeEffectsEjPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGBackwardsPropagationPhase.cpp' l='338' c='_ZN3JSC3DFG25BackwardsPropagationPhase9propagateEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp' l='1049' c='_ZN3JSC3DFG14ByteCodeParser8makeSafeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp' l='5854' u='r' c='_ZN3JSC3DFG14ByteCodeParser10parseBlockEj'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGSafeToExecute.h' l='701' c='_ZN3JSC3DFG13safeToExecuteERT_RNS0_5GraphEPNS0_4NodeEb'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGDoesGC.cpp' l='578' c='_ZN3JSC3DFG6doesGCERNS0_5GraphEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp' l='191' c='_ZN3JSC3DFG10FixupPhase9fixupNodeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp' l='197' u='r' c='_ZN3JSC3DFG10FixupPhase9fixupNodeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp' l='236' u='r' c='_ZN3JSC3DFG10FixupPhase9fixupNodeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp' l='244' u='r' c='_ZN3JSC3DFG10FixupPhase9fixupNodeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp' l='252' u='r' c='_ZN3JSC3DFG10FixupPhase9fixupNodeEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp' l='5539' u='r' c='_ZN3JSC3DFG14SpeculativeJIT15compileIncOrDecEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/dfg/DFGSpeculativeJIT64.cpp' l='2282' c='_ZN3JSC3DFG14SpeculativeJIT7compileEPNS0_4NodeE'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp' l='786' c='_ZN3JSC3FTL12_GLOBAL__N_112LowerDFGToB311compileNodeEj'/>
<use f='WebKit/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp' l='3351' u='r' c='_ZN3JSC3FTL12_GLOBAL__N_112LowerDFGToB315compileIncOrDecEv'/>
