<dec f='WebKit/JavaScriptCore/PrivateHeaders/JavaScriptCore/CallData.h' l='42' type='2'/>
<dec f='WebKit/Source/JavaScriptCore/runtime/CallData.h' l='42' type='2'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/Interpreter.cpp' l='854' u='r' c='_ZN3JSC11Interpreter11executeCallEPNS_14JSGlobalObjectEPNS_8JSObjectERKNS_8CallDataENS_7JSValueERKNS_7ArgListE'/>
<use f='WebKit/Source/JavaScriptCore/interpreter/Interpreter.cpp' l='930' u='r' c='_ZN3JSC11Interpreter16executeConstructEPNS_14JSGlobalObjectEPNS_8JSObjectERKNS_8CallDataERKNS_7ArgListENS_7JSValueE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSFunction.cpp' l='291' u='r' c='_ZN3JSC10JSFunction11getCallDataEPNS_6JSCellE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/JSFunction.cpp' l='489' u='r' c='_ZN3JSC10JSFunction16getConstructDataEPNS_6JSCellE'/>
<use f='WebKit/Source/JavaScriptCore/runtime/StringPrototype.cpp' l='538' u='r' c='_ZN3JSCL24replaceUsingRegExpSearchERNS_2VMEPNS_14JSGlobalObjectEPNS_9CallFrameEPNS_8JSStringENS_7JSValueERKNS_8CallDataERN3WTF6StringES8_'/>
<use f='WebKit/Source/JavaScriptCore/runtime/StringPrototype.cpp' l='767' u='r' c='_ZN3JSCL24replaceUsingStringSearchERNS_2VMEPNS_14JSGlobalObjectEPNS_9CallFrameEPNS_8JSStringENS_7JSValueES8_NS_11ReplaceModeE'/>
<use f='WebKit/Source/WebCore/bindings/js/JSExecStateInstrumentation.h' l='43' u='r' c='_ZN7WebCore11JSExecState18instrumentFunctionEPNS_22ScriptExecutionContextERKN3JSC8CallDataE'/>
