<dec f='WebKit/Source/JavaScriptCore/jsc.cpp' l='388' type='0'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='3247' u='r' c='_ZN11CommandLine14parseArgumentsEiPPc'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='3253' u='r' c='_ZN11CommandLine14parseArgumentsEiPPc'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='3361' u='r' c='_ZN11CommandLine14parseArgumentsEiPPc'/>
<use f='WebKit/Source/JavaScriptCore/jsc.cpp' l='3408' u='r' c='_ZN11CommandLine14parseArgumentsEiPPc'/>
