<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/ProgressEvent.h' l='40' ll='44'/>
<use f='WebKit/Source/WebCore/dom/ProgressEvent.h' l='46' c='_ZN7WebCore13ProgressEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/ProgressEvent.h' l='59' c='_ZN7WebCore13ProgressEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>24</size>
<mbr r='WebCore::ProgressEvent::Init::lengthComputable' o='24' t='bool'/>
<mbr r='WebCore::ProgressEvent::Init::loaded' o='64' t='unsigned long long'/>
<mbr r='WebCore::ProgressEvent::Init::total' o='128' t='unsigned long long'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSProgressEvent.cpp' l='190' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<use f='WebKit/Source/WebCore/dom/ProgressEvent.cpp' l='35' c='_ZN7WebCore13ProgressEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
