<dec f='WebKit/Source/WebCore/html/track/TextTrackCue.cpp' l='159' type='1'/>
<use f='WebKit/Source/WebCore/html/track/TextTrackCue.cpp' l='173' u='r' c='_ZN7WebCoreL16tagPseudoObjectsERNS_4NodeE'/>
<use f='WebKit/Source/WebCore/html/track/TextTrackCue.cpp' l='173' u='r' c='_ZN7WebCoreL16tagPseudoObjectsERNS_4NodeE'/>
<use f='WebKit/Source/WebCore/html/track/TextTrackCue.cpp' l='221' u='r' c='_ZN7WebCore12TextTrackCue6createERNS_8DocumentEddRNS_16DocumentFragmentE'/>
