<def f='WebKit/Source/WebCore/Modules/fetch/FetchResponse.h' l='54' ll='58'/>
<use f='WebKit/Source/WebCore/Modules/fetch/FetchResponse.h' l='62' c='_ZN7WebCore13FetchResponse6createERNS_22ScriptExecutionContextEOSt8optionalIN3WTF7VariantIJNS4_6RefPtrINS_4BlobENS4_12RawPtrTraitsIS7_EENS4_21DefaultR6707098'/>
<size>48</size>
<mbr r='WebCore::FetchResponse::Init::status' o='0' t='unsigned short'/>
<mbr r='WebCore::FetchResponse::Init::statusText' o='64' t='WTF::String'/>
<mbr r='WebCore::FetchResponse::Init::headers' o='128' t='std::optional&lt;FetchHeaders::Init&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.h' l='100' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.h' l='100' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>48</size>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.cpp' l='121' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.cpp' l='121' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.cpp' l='131' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchResponse.cpp' l='249' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
<use f='WebKit/Source/WebCore/Modules/fetch/FetchResponse.cpp' l='66' c='_ZN7WebCore13FetchResponse6createERNS_22ScriptExecutionContextEOSt8optionalIN3WTF7VariantIJNS4_6RefPtrINS_4BlobENS4_12RawPtrTraitsIS7_EENS4_21DefaultR6707098'/>
<size>48</size>
