<dec f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='85' type='WebCore::ScriptBuffer'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='104' c='_ZNK7WebCore24ServiceWorkerContextData6encodeERT_'/>
<offset>3008</offset>
<use f='WebKit/Source/WebCore/inspector/agents/worker/ServiceWorkerAgent.cpp' l='63' u='m' c='_ZN7WebCore18ServiceWorkerAgent21getInitializationInfoEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.cpp' l='40' u='m' c='_ZNK7WebCore24ServiceWorkerContextData12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.cpp' l='40' u='m' c='_ZNK7WebCore24ServiceWorkerContextData12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerGlobalScope.cpp' l='165' u='w' c='_ZN7WebCore24ServiceWorkerGlobalScope20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_E8252197'/>
<use f='WebKit/Source/WebCore/workers/service/context/ServiceWorkerThread.cpp' l='77' u='r' c='_ZN7WebCore19ServiceWorkerThreadC1EONS_24ServiceWorkerContextDataEON3WTF6StringERKNS_8Settings6ValuesERNS_17WorkerLoaderProxyERNS_19WorkerDebuggerProx11887415'/>
<use f='WebKit/Source/WebCore/workers/service/server/RegistrationDatabase.cpp' l='472' u='r' c='_ZN7WebCore20RegistrationDatabase13doPushChangesERKN3WTF6VectorINS_24ServiceWorkerContextDataELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEERKNS2_6518018'/>
<use f='WebKit/Source/WebCore/workers/service/server/SWServer.cpp' l='172' u='a' c='_ZN7WebCore8SWServer24addRegistrationFromStoreEONS_24ServiceWorkerContextDataE'/>
<use f='WebKit/Source/WebCore/workers/service/server/SWServer.cpp' l='722' u='r' c='_ZN7WebCore8SWServer18installContextDataERKNS_24ServiceWorkerContextDataE'/>
