<inh f='WebKit/Source/WebCore/dom/MouseRelatedEvent.h' l='33' c='WebCore::MouseRelatedEventInit'/>
<def f='WebKit/Source/WebCore/dom/TouchEvent.h' l='53' ll='57'/>
<use f='WebKit/Source/WebCore/dom/TouchEvent.h' l='59' c='_ZN7WebCore10TouchEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/TouchEvent.h' l='83' c='_ZN7WebCore10TouchEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/TouchEvent.cpp' l='51' c='_ZN7WebCore10TouchEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>64</size>
<mbr r='WebCore::TouchEvent::Init::touches' o='320' t='RefPtr&lt;WebCore::TouchList&gt;'/>
<mbr r='WebCore::TouchEvent::Init::targetTouches' o='384' t='RefPtr&lt;WebCore::TouchList&gt;'/>
<mbr r='WebCore::TouchEvent::Init::changedTouches' o='448' t='RefPtr&lt;WebCore::TouchList&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.cpp' l='71' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSTouchEvent.cpp' l='232' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>64</size>
