<use f='WebKit/Source/WebCore/rendering/updating/RenderTreeBuilder.h' l='124' c='_ZN7WebCore17RenderTreeBuilder11rubyBuilderEv'/>
<use f='WebKit/Source/WebCore/rendering/updating/RenderTreeBuilder.h' l='147'/>
<def f='WebKit/Source/WebCore/rendering/updating/RenderTreeBuilderRuby.h' l='40' ll='62'/>
<use f='WebKit/Source/WebCore/rendering/updating/RenderTreeBuilder.cpp' l='129' c='_ZN7WebCore17RenderTreeBuilderC1ERNS_10RenderViewE'/>
<size>8</size>
<fun r='_ZN7WebCore17RenderTreeBuilder4RubyC1ERS0_'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby6attachERNS_13RenderRubyRunESt10unique_ptrINS_12RenderObjectENS_19RenderObjectDeleterEEPS5_'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby6detachERNS_18RenderRubyAsInlineERNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby6detachERNS_17RenderRubyAsBlockERNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby6detachERNS_13RenderRubyRunERNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby12moveChildrenERNS_14RenderRubyBaseES3_'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby26findOrCreateParentForChildERNS_17RenderRubyAsBlockERKNS_12RenderObjectERPS4_'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby26findOrCreateParentForChildERNS_18RenderRubyAsInlineERKNS_12RenderObjectERPS4_'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby18moveInlineChildrenERNS_14RenderRubyBaseES3_PNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby17moveBlockChildrenERNS_14RenderRubyBaseES3_PNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby20moveChildrenInternalERNS_14RenderRubyBaseES3_PNS_12RenderObjectE'/>
<fun r='_ZN7WebCore17RenderTreeBuilder4Ruby12rubyBaseSafeERNS_13RenderRubyRunE'/>
<mbr r='WebCore::RenderTreeBuilder::Ruby::m_builder' o='0' t='WebCore::RenderTreeBuilder &amp;'/>
