<def f='WebKit/Source/WebCore/dom/MutationObserver.h' l='84' ll='92'/>
<use f='WebKit/Source/WebCore/dom/MutationObserver.h' l='94' c='_ZN7WebCore16MutationObserver7observeERNS_4NodeERKNS0_4InitE'/>
<size>40</size>
<mbr r='WebCore::MutationObserver::Init::childList' o='0' t='bool'/>
<mbr r='WebCore::MutationObserver::Init::attributes' o='8' t='std::optional&lt;bool&gt;'/>
<mbr r='WebCore::MutationObserver::Init::characterData' o='24' t='std::optional&lt;bool&gt;'/>
<mbr r='WebCore::MutationObserver::Init::subtree' o='40' t='bool'/>
<mbr r='WebCore::MutationObserver::Init::attributeOldValue' o='48' t='std::optional&lt;bool&gt;'/>
<mbr r='WebCore::MutationObserver::Init::characterDataOldValue' o='64' t='std::optional&lt;bool&gt;'/>
<mbr r='WebCore::MutationObserver::Init::attributeFilter' o='128' t='std::optional&lt;Vector&lt;String&gt; &gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>40</size>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.cpp' l='60' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.cpp' l='70' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMutationObserver.cpp' l='311' c='_ZN7WebCoreL47jsMutationObserverPrototypeFunction_observeBodyEPN3JSC14JSGlobalObjectEPNS0_9CallFrameEPNS_18JSMutationObserverE'/>
<size>40</size>
<use f='WebKit/Source/WebCore/dom/MutationObserver.cpp' l='80' c='_ZN7WebCore16MutationObserver7observeERNS_4NodeERKNS0_4InitE'/>
<size>40</size>
