<dec f='WebKit/Source/WebCore/workers/WorkerType.h' l='32' type='1'/>
<use f='WebKit/Source/WebKit/Shared/WebCoreArgumentCoders.h' l='957'/>
<use f='WebKit/WebCore/DerivedSources/JSWorkerType.cpp' l='39' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_10WorkerTypeE'/>
<use f='WebKit/WebCore/DerivedSources/JSWorkerType.cpp' l='55' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/Source/WebCore/workers/Worker.cpp' l='119' u='r' c='_ZN7WebCore6Worker6createERNS_22ScriptExecutionContextEN3JSC12RuntimeFlagsERKN3WTF6StringERKNS0_7OptionsE'/>
<use f='WebKit/Source/WebCore/workers/WorkerGlobalScope.cpp' l='295' u='r' c='_ZN7WebCore17WorkerGlobalScope13importScriptsERKN3WTF6VectorINS1_6StringELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/workers/service/server/RegistrationDatabase.cpp' l='340' c='_ZN7WebCoreL18workerTypeToStringENS_10WorkerTypeE'/>
<use f='WebKit/Source/WebCore/workers/service/server/RegistrationDatabase.cpp' l='352' u='a' c='_ZN7WebCoreL18stringToWorkerTypeERKN3WTF6StringE'/>
