<def f='WebKit/Source/WebCore/inspector/InspectorAuditResourcesObject.h' l='54' ll='58'/>
<use f='WebKit/Source/WebCore/inspector/InspectorAuditResourcesObject.h' l='65' c='_ZN7WebCore29InspectorAuditResourcesObject12getResourcesERNS_8DocumentE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.h' l='92' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.h' l='92' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.h' l='94' c='_ZN7WebCore21convertDictionaryToJSERN3JSC14JSGlobalObjectERNS_17JSDOMGlobalObjectERKNS_29InspectorAuditResourcesObject8ResourceE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.cpp' l='99' c='_ZN7WebCore21convertDictionaryToJSERN3JSC14JSGlobalObjectERNS_17JSDOMGlobalObjectERKNS_29InspectorAuditResourcesObject8ResourceE'/>
<use f='WebKit/WebCore/DerivedSources/JSInspectorAuditResourcesObject.cpp' l='278' c='_ZN7WebCoreL65jsInspectorAuditResourcesObjectPrototypeFunction_getResourcesBodyEPN3JSC14JSGlobalObjectEPNS0_9CallFrameEPNS_31JSInspectorAuditResourcesObjectE'/>
<size>24</size>
<mbr r='WebCore::InspectorAuditResourcesObject::Resource::id' o='0' t='WTF::String'/>
<mbr r='WebCore::InspectorAuditResourcesObject::Resource::url' o='64' t='WTF::String'/>
<mbr r='WebCore::InspectorAuditResourcesObject::Resource::mimeType' o='128' t='WTF::String'/>
<use f='WebKit/Source/WebCore/inspector/InspectorAuditResourcesObject.cpp' l='59' c='_ZN7WebCore29InspectorAuditResourcesObject12getResourcesERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorAuditResourcesObject.cpp' l='63' c='_ZN7WebCore29InspectorAuditResourcesObject12getResourcesERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorAuditResourcesObject.cpp' l='70' c='_ZN7WebCore29InspectorAuditResourcesObject12getResourcesERNS_8DocumentE'/>
<size>24</size>
