<dec f='WebKit/Source/WebCore/platform/mediacapabilities/TransferFunction.h' l='32' type='1'/>
<use f='WebKit/Source/WebCore/platform/mediacapabilities/TransferFunction.h' l='44'/>
<use f='WebKit/WebCore/DerivedSources/JSTransferFunction.cpp' l='40' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_16TransferFunctionE'/>
<use f='WebKit/WebCore/DerivedSources/JSTransferFunction.cpp' l='57' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
