<dec f='WebKit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='287' type='2'/>
<use f='WebKit/Source/WebCore/rendering/RenderTableCell.h' l='303' u='r' c='_ZNK7WebCore15RenderTableCell17isBaselineAlignedEv'/>
<use f='WebKit/Source/WebCore/rendering/RenderTableCell.cpp' l='213' c='_ZN7WebCore15RenderTableCell23computeIntrinsicPaddingENS_10LayoutUnitE'/>
<use f='WebKit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='2763' c='_ZN7WebCore17CSSPrimitiveValueC1ET_'/>
<use f='WebKit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='2795' u='r' c='_ZNK7WebCore17CSSPrimitiveValuecvT_Ev'/>
<use f='WebKit/Source/WebCore/rendering/style/RenderStyleConstants.cpp' l='1245' c='_ZN7WebCorelsERN3WTF10TextStreamENS_13VerticalAlignE'/>
<use f='WebKit/Source/WebCore/rendering/LegacyRootInlineBox.cpp' l='941' u='r' c='_ZN7WebCore19LegacyRootInlineBox22verticalPositionForBoxEPNS_15LegacyInlineBoxERNS_21VerticalPositionCacheE'/>
<use f='WebKit/Source/WebCore/css/CSSComputedStyleDeclaration.cpp' l='3266' c='_ZN7WebCore22ComputedStyleExtractor23valueForPropertyInStyleERKNS_11RenderStyleENS_13CSSPropertyIDEPNS_13RenderElementE'/>
<use f='WebKit/Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceText.cpp' l='110' c='_ZL37getAttributeSetForAccessibilityObjectPKN7WebCore19AccessibilityObjectE'/>
<use f='WebKit/Source/WebCore/editing/Editor.cpp' l='4054' c='_ZN7WebCore6Editor30fontAttributesAtSelectionStartEv'/>
