<inh f='WebKit/Source/WebCore/dom/UIEventInit.h' l='34' c='WebCore::UIEventInit'/>
<def f='WebKit/Source/WebCore/dom/FocusEvent.h' l='49' ll='51'/>
<use f='WebKit/Source/WebCore/dom/FocusEvent.h' l='53' c='_ZN7WebCore10FocusEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/FocusEvent.h' l='63' c='_ZN7WebCore10FocusEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<mbr r='WebCore::FocusEvent::Init::relatedTarget' o='192' t='RefPtr&lt;WebCore::EventTarget&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.cpp' l='55' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.cpp' l='65' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFocusEvent.cpp' l='192' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/dom/FocusEvent.cpp' l='52' c='_ZN7WebCore10FocusEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>32</size>
