<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionErrorEvent.h' l='36' ll='39'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionErrorEvent.h' l='41' c='_ZN7WebCore27SpeechRecognitionErrorEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionErrorEvent.h' l='48' c='_ZN7WebCore27SpeechRecognitionErrorEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::SpeechRecognitionErrorEvent::Init::error' o='24' t='WebCore::SpeechRecognitionErrorCode'/>
<mbr r='WebCore::SpeechRecognitionErrorEvent::Init::message' o='64' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionErrorEvent.cpp' l='180' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionErrorEvent.cpp' l='35' c='_ZN7WebCore27SpeechRecognitionErrorEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionErrorEvent.cpp' l='45' c='_ZN7WebCore27SpeechRecognitionErrorEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
