<dec f='WebKit/Source/WebCore/page/DragActions.h' l='83' type='16'/>
<use f='WebKit/Source/WebCore/page/DragActions.h' l='89' u='r' c='_ZN7WebCore16anyDragOperationEv'/>
<use f='WebKit/Source/WebCore/page/DragActions.h' l='89' u='r' c='_ZN7WebCore16anyDragOperationEv'/>
<use f='WebKit/Source/WebCore/page/DragActions.h' l='129'/>
<use f='WebKit/Source/WebCore/platform/gtk/GtkUtilities.cpp' l='162' u='r' c='_ZN7WebCore28gdkDragActionToDragOperationE13GdkDragAction'/>
<use f='WebKit/Source/WebCore/platform/gtk/GtkUtilities.cpp' l='175' u='r' c='_ZN7WebCore29dragOperationToGdkDragActionsEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/platform/gtk/GtkUtilities.cpp' l='187' u='r' c='_ZN7WebCore34dragOperationToSingleGdkDragActionEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='187' u='r' c='_ZN7WebCore14DragController28platformGenericDragOperationEv'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='450' u='a' c='_ZN7WebCore14DragController15tryDocumentDragERKNS_8DragDataEN3WTF9OptionSetINS_21DragDestinationActionEEERSt8optionalINS_13DragOperationEE'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='700' u='r' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='700' u='r' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='704' u='r' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/page/DragController.cpp' l='705' u='a' c='_ZN7WebCoreL23defaultOperationForDragEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='2300' u='a' c='_ZN7WebCoreL39convertDropZoneOperationToDragOperationERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='2310' c='_ZN7WebCoreL39convertDragOperationToDropZoneOperationESt8optionalINS_13DragOperationEE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='622' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='622' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='626' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='626' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='628' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='628' u='r' c='_ZN7WebCoreL14dragOpFromIEOpERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='636' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='636' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='638' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
<use f='WebKit/Source/WebCore/dom/DataTransfer.cpp' l='638' u='r' c='_ZN7WebCoreL14IEOpFromDragOpEN3WTF9OptionSetINS_13DragOperationEEE'/>
