<inh f='WebKit/Source/WebCore/dom/MouseEventInit.h' l='32' c='WebCore::MouseEventInit'/>
<def f='WebKit/Source/WebCore/dom/WheelEvent.h' l='46' ll='53'/>
<use f='WebKit/Source/WebCore/dom/WheelEvent.h' l='55' c='_ZN7WebCore10WheelEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/WheelEvent.h' l='78' c='_ZN7WebCore10WheelEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>96</size>
<mbr r='WebCore::WheelEvent::Init::deltaX' o='448' t='double'/>
<mbr r='WebCore::WheelEvent::Init::deltaY' o='512' t='double'/>
<mbr r='WebCore::WheelEvent::Init::deltaZ' o='576' t='double'/>
<mbr r='WebCore::WheelEvent::Init::deltaMode' o='640' t='unsigned int'/>
<mbr r='WebCore::WheelEvent::Init::wheelDeltaX' o='672' t='int'/>
<mbr r='WebCore::WheelEvent::Init::wheelDeltaY' o='704' t='int'/>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>96</size>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.cpp' l='57' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.cpp' l='67' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWheelEvent.cpp' l='434' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>96</size>
<use f='WebKit/Source/WebCore/dom/WheelEvent.cpp' l='51' c='_ZN7WebCore10WheelEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/WheelEvent.cpp' l='82' c='_ZN7WebCore10WheelEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>96</size>
