<dec f='WebKit/Source/WebCore/platform/network/ProxyServer.h' l='40' type='1'/>
<use f='WebKit/Source/WebCore/platform/network/ProxyServer.cpp' l='42' c='_ZN7WebCoreL23appendProxyServerStringERN3WTF13StringBuilderERKNS_11ProxyServerE'/>
