<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/Modules/indexeddb/IDBVersionChangeEvent.h' l='46' ll='49'/>
<use f='WebKit/Source/WebCore/Modules/indexeddb/IDBVersionChangeEvent.h' l='51' c='_ZN7WebCore21IDBVersionChangeEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/indexeddb/IDBVersionChangeEvent.h' l='65' c='_ZN7WebCore21IDBVersionChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<mbr r='WebCore::IDBVersionChangeEvent::Init::oldVersion' o='64' t='uint64_t'/>
<mbr r='WebCore::IDBVersionChangeEvent::Init::newVersion' o='128' t='std::optional&lt;uint64_t&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIDBVersionChangeEvent.cpp' l='178' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/Modules/indexeddb/IDBVersionChangeEvent.cpp' l='46' c='_ZN7WebCore21IDBVersionChangeEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>32</size>
