<dec f='WebKit/Source/WebCore/crypto/JsonWebKey.h' l='58' type='WTF::String'/>
<offset>1408</offset>
<use f='WebKit/WebCore/DerivedSources/JSJsonWebKey.cpp' l='140' u='w' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSJsonWebKey.cpp' l='301' u='r' c='_ZN7WebCore21convertDictionaryToJSERN3JSC14JSGlobalObjectERNS_17JSDOMGlobalObjectERKNS_10JsonWebKeyE'/>
<use f='WebKit/WebCore/DerivedSources/JSJsonWebKey.cpp' l='302' u='r' c='_ZN7WebCore21convertDictionaryToJSERN3JSC14JSGlobalObjectERNS_17JSDOMGlobalObjectERKNS_10JsonWebKeyE'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyAES.cpp' l='89' u='m' c='_ZN7WebCore12CryptoKeyAES9importJwkENS_25CryptoAlgorithmIdentifierEONS_10JsonWebKeyEbiON3WTF8FunctionIFbmRKNS4_6StringEEEE'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyAES.cpp' l='91' u='r' c='_ZN7WebCore12CryptoKeyAES9importJwkENS_25CryptoAlgorithmIdentifierEONS_10JsonWebKeyEbiON3WTF8FunctionIFbmRKNS4_6StringEEEE'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyAES.cpp' l='110' u='w' c='_ZNK7WebCore12CryptoKeyAES9exportJwkEv'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyHMAC.cpp' l='104' u='m' c='_ZN7WebCore13CryptoKeyHMAC9importJwkEmNS_25CryptoAlgorithmIdentifierEONS_10JsonWebKeyEbiON3WTF8FunctionIFbS1_RKNS4_6StringEEEE'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyHMAC.cpp' l='106' u='r' c='_ZN7WebCore13CryptoKeyHMAC9importJwkEmNS_25CryptoAlgorithmIdentifierEONS_10JsonWebKeyEbiON3WTF8FunctionIFbS1_RKNS4_6StringEEEE'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyHMAC.cpp' l='125' u='w' c='_ZNK7WebCore13CryptoKeyHMAC9exportJwkEv'/>
