<dec f='WebKit/Source/WebCore/crypto/CryptoKey.h' l='50' type='1'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyEC.h' l='98' u='r' c='_ZNK7WebCore11CryptoKeyEC8keyClassEv'/>
<use f='WebKit/Source/WebCore/crypto/keys/CryptoKeyEC.h' l='120' u='r' c='_ZN3WTF14TypeCastTraitsIKN7WebCore11CryptoKeyECET_Lb0EE6isTypeERKNS1_9CryptoKeyE'/>
<use f='WebKit/Source/WebCore/bindings/js/SerializedScriptValue.cpp' l='1714' c='_ZN7WebCore15CloneSerializer5writeEPKNS_9CryptoKeyE'/>
