<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/storage/StorageEvent.h' l='41' ll='47'/>
<use f='WebKit/Source/WebCore/storage/StorageEvent.h' l='49' c='_ZN7WebCore12StorageEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/storage/StorageEvent.h' l='68' c='_ZN7WebCore12StorageEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>48</size>
<mbr r='WebCore::StorageEvent::Init::key' o='64' t='WTF::String'/>
<mbr r='WebCore::StorageEvent::Init::oldValue' o='128' t='WTF::String'/>
<mbr r='WebCore::StorageEvent::Init::newValue' o='192' t='WTF::String'/>
<mbr r='WebCore::StorageEvent::Init::url' o='256' t='WTF::String'/>
<mbr r='WebCore::StorageEvent::Init::storageArea' o='320' t='RefPtr&lt;WebCore::Storage&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSStorageEvent.cpp' l='225' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>48</size>
<use f='WebKit/Source/WebCore/storage/StorageEvent.cpp' l='50' c='_ZN7WebCore12StorageEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/storage/StorageEvent.cpp' l='65' c='_ZN7WebCore12StorageEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>48</size>
