<def f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.h' l='37' ll='41'/>
<use f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.h' l='43' c='_ZN7WebCore18PathTraversalStateC1ENS0_6ActionEf'/>
<use f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.h' l='49' c='_ZNK7WebCore18PathTraversalState6actionEv'/>
<use f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.h' l='50' c='_ZN7WebCore18PathTraversalState9setActionENS0_6ActionE'/>
<use f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.h' l='71'/>
<use f='WebKit/Source/WebCore/platform/graphics/PathTraversalState.cpp' l='176' c='_ZN7WebCore18PathTraversalStateC1ENS0_6ActionEf'/>
