<dec f='WebKit/Source/WebCore/editing/EditingBehaviorType.h' l='39' type='0'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='47' u='r' c='_ZNK7WebCore15EditingBehavior36shouldConsiderSelectionAsDirectionalEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='51' u='r' c='_ZNK7WebCore15EditingBehavior40shouldCenterAlignWhenSelectionIsRevealedEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='55' u='r' c='_ZNK7WebCore15EditingBehavior40shouldToggleStyleBasedOnStartOfSelectionEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='59' u='r' c='_ZNK7WebCore15EditingBehavior48shouldAlwaysGrowSelectionWhenExtendingToBoundaryEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='62' u='r' c='_ZNK7WebCore15EditingBehavior33shouldSelectOnContextualMenuClickEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='79' u='r' c='_ZNK7WebCore15EditingBehavior44shouldExtendSelectionByWordOrLineAcrossCaretEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='90' u='r' c='_ZNK7WebCore15EditingBehavior35shouldSelectBasedOnDictionaryLookupEv'/>
<use f='WebKit/Source/WebCore/editing/EditingBehavior.h' l='93' u='r' c='_ZNK7WebCore15EditingBehavior45shouldAlwaysExtendSelectionFromExtentEndpointEv'/>
<use f='WebKit/WebCore/DerivedSources/JSInternalSettings.cpp' l='61' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_19EditingBehaviorTypeE'/>
<use f='WebKit/WebCore/DerivedSources/JSInternalSettings.cpp' l='78' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
