<dec f='WebKit/Source/WebCore/loader/FetchOptions.h' l='39' type='12'/>
<use f='WebKit/Source/WebCore/loader/FetchOptions.h' l='96' u='r' c='_ZN7WebCore23isScriptLikeDestinationENS_12FetchOptions11DestinationE'/>
<use f='WebKit/Source/WebCore/loader/FetchOptions.h' l='120'/>
<use f='WebKit/Source/WebKit/NetworkProcess/NetworkLoadChecker.cpp' l='267' c='_ZN6WebKit18NetworkLoadChecker32isAllowedByContentSecurityPolicyERKN7WebCore15ResourceRequestEPNS1_27ContentSecurityPolicyClientE'/>
<use f='WebKit/Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp' l='409' c='_ZN6WebKit21NetworkResourceLoader16resourceLoadInfoEv'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchRequest.cpp' l='112' u='r' c='_ZN7WebCore26convertEnumerationToStringENS_12FetchOptions11DestinationE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchRequest.cpp' l='157' u='a' c='_ZN7WebCore16parseEnumerationERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='303' u='r' c='_ZN7WebCore18ScriptModuleLoader12importModuleEPN3JSC14JSGlobalObjectEPNS1_14JSModuleLoaderEPNS1_8JSStringENS1_7JSValueERKNS1_12SourceOriginE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='316' u='r' c='_ZN7WebCore18ScriptModuleLoader12importModuleEPN3JSC14JSGlobalObjectEPNS1_14JSModuleLoaderEPNS1_8JSStringENS1_7JSValueERKNS1_12SourceOriginE'/>
<use f='WebKit/Source/WebCore/bindings/js/ScriptModuleLoader.cpp' l='324' u='r' c='_ZN7WebCore18ScriptModuleLoader12importModuleEPN3JSC14JSGlobalObjectEPNS1_14JSModuleLoaderEPNS1_8JSStringENS1_7JSValueERKNS1_12SourceOriginE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='810' u='r' c='_ZN7WebCoreL18destinationForTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/workers/WorkerScriptLoader.cpp' l='60' u='r' c='_ZN7WebCore18WorkerScriptLoader17loadSynchronouslyEPNS_22ScriptExecutionContextERKN3WTF3URLENS_12FetchOptions4ModeENS7_5CacheENS_32ContentSecurityPoli15627940'/>
