<def f='WebKit/Source/WebCore/page/IntersectionObserverEntry.h' l='44' ll='52'/>
<use f='WebKit/Source/WebCore/page/IntersectionObserverEntry.h' l='54' c='_ZN7WebCore25IntersectionObserverEntry6createERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/page/IntersectionObserverEntry.h' l='69' c='_ZN7WebCore25IntersectionObserverEntryC1ERKNS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.h' l='101' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.h' l='101' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>136</size>
<mbr r='WebCore::IntersectionObserverEntry::Init::time' o='0' t='double'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::rootBounds' o='64' t='std::optional&lt;DOMRectInit&gt;'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::boundingClientRect' o='384' t='WebCore::DOMRectInit'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::intersectionRect' o='640' t='WebCore::DOMRectInit'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::intersectionRatio' o='896' t='double'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::target' o='960' t='RefPtr&lt;WebCore::Element&gt;'/>
<mbr r='WebCore::IntersectionObserverEntry::Init::isIntersecting' o='1024' t='bool'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.cpp' l='71' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserverEntry.cpp' l='229' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>136</size>
<use f='WebKit/Source/WebCore/page/IntersectionObserverEntry.cpp' l='35' c='_ZN7WebCore25IntersectionObserverEntryC1ERKNS0_4InitE'/>
<size>136</size>
