<inh f='WebKit/Source/WebCore/workers/service/ExtendableEventInit.h' l='34' c='WebCore::ExtendableEventInit'/>
<def f='WebKit/Source/WebCore/workers/service/FetchEvent.h' l='43' ll='48'/>
<use f='WebKit/Source/WebCore/workers/service/FetchEvent.h' l='52' c='_ZN7WebCore10FetchEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/workers/service/FetchEvent.h' l='75' c='_ZN7WebCore10FetchEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>40</size>
<mbr r='WebCore::FetchEvent::Init::request' o='64' t='RefPtr&lt;WebCore::FetchRequest&gt;'/>
<mbr r='WebCore::FetchEvent::Init::clientId' o='128' t='WTF::String'/>
<mbr r='WebCore::FetchEvent::Init::reservedClientId' o='192' t='WTF::String'/>
<mbr r='WebCore::FetchEvent::Init::targetClientId' o='256' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.h' l='86' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.h' l='86' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>40</size>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.cpp' l='71' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSFetchEvent.cpp' l='219' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>40</size>
<use f='WebKit/Source/WebCore/workers/service/FetchEvent.cpp' l='42' c='_ZN7WebCore10FetchEvent16createForTestingERNS_22ScriptExecutionContextE'/>
<use f='WebKit/Source/WebCore/workers/service/FetchEvent.cpp' l='47' c='_ZN7WebCore10FetchEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>40</size>
<use f='WebKit/Source/WebCore/workers/service/context/ServiceWorkerFetch.cpp' l='170' c='_ZN7WebCore18ServiceWorkerFetch18dispatchFetchEventEON3WTF3RefINS0_6ClientENS1_12RawPtrTraitsIS3_EEEERNS_24ServiceWorkerGlobalScopeESt8optionalINS_29S9661693'/>
<size>40</size>
