<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/WebKitTransitionEvent.h' l='40' ll='44'/>
<use f='WebKit/Source/WebCore/dom/WebKitTransitionEvent.h' l='46' c='_ZN7WebCore21WebKitTransitionEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/WebKitTransitionEvent.h' l='61' c='_ZN7WebCore21WebKitTransitionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<mbr r='WebCore::WebKitTransitionEvent::Init::propertyName' o='64' t='WTF::String'/>
<mbr r='WebCore::WebKitTransitionEvent::Init::elapsedTime' o='128' t='double'/>
<mbr r='WebCore::WebKitTransitionEvent::Init::pseudoElement' o='192' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitTransitionEvent.cpp' l='190' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/dom/WebKitTransitionEvent.cpp' l='43' c='_ZN7WebCore21WebKitTransitionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>32</size>
