<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/WebKitAnimationEvent.h' l='40' ll='44'/>
<use f='WebKit/Source/WebCore/dom/WebKitAnimationEvent.h' l='46' c='_ZN7WebCore20WebKitAnimationEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/WebKitAnimationEvent.h' l='61' c='_ZN7WebCore20WebKitAnimationEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<mbr r='WebCore::WebKitAnimationEvent::Init::animationName' o='64' t='WTF::String'/>
<mbr r='WebCore::WebKitAnimationEvent::Init::elapsedTime' o='128' t='double'/>
<mbr r='WebCore::WebKitAnimationEvent::Init::pseudoElement' o='192' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebKitAnimationEvent.cpp' l='190' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/dom/WebKitAnimationEvent.cpp' l='35' c='_ZN7WebCore20WebKitAnimationEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>32</size>
