<dec f='WebKit/Source/WebCore/page/PerformanceEntry.h' l='54' type='8'/>
<use f='WebKit/Source/WebCore/page/PerformanceResourceTiming.h' l='70' u='r' c='_ZNK7WebCore25PerformanceResourceTiming20performanceEntryTypeEv'/>
<use f='WebKit/Source/WebCore/bindings/js/JSPerformanceEntryCustom.cpp' l='60' c='_ZN7WebCore16toJSNewlyCreatedEPN3JSC14JSGlobalObjectEPNS_17JSDOMGlobalObjectEON3WTF3RefINS_16PerformanceEntryENS5_12RawPtrTraitsIS7_EEEE'/>
<use f='WebKit/Source/WebCore/page/PerformanceEntry.cpp' l='60' u='a' c='_ZN7WebCore16PerformanceEntry20parseEntryTypeStringERKN3WTF6StringE'/>
