<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/MessageEvent.h' l='58' ll='64'/>
<use f='WebKit/Source/WebCore/dom/MessageEvent.h' l='65' c='_ZN7WebCore12MessageEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/MessageEvent.h' l='86' c='_ZN7WebCore12MessageEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.h' l='88' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.h' l='88' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>72</size>
<mbr r='WebCore::MessageEvent::Init::data' o='64' t='JSC::JSValue'/>
<mbr r='WebCore::MessageEvent::Init::origin' o='128' t='WTF::String'/>
<mbr r='WebCore::MessageEvent::Init::lastEventId' o='192' t='WTF::String'/>
<mbr r='WebCore::MessageEvent::Init::source' o='256' t='std::optional&lt;MessageEventSource&gt;'/>
<mbr r='WebCore::MessageEvent::Init::ports' o='448' t='Vector&lt;RefPtr&lt;WebCore::MessagePort&gt; &gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.cpp' l='73' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSMessageEvent.cpp' l='232' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>72</size>
<use f='WebKit/Source/WebCore/dom/MessageEvent.cpp' l='44' c='_ZN7WebCore12MessageEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/MessageEvent.cpp' l='102' c='_ZN7WebCore12MessageEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>72</size>
