<dec f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='46' type='WebCore::ScriptBuffer'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='52' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript6encodeERT_'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='79' u='m' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContextData.h' l='79' u='m' c='_ZNK7WebCore24ServiceWorkerContextData14ImportedScript12isolatedCopyEv'/>
<offset>0</offset>
<use f='WebKit/Source/WebCore/bindings/js/WorkerModuleScriptLoader.cpp' l='68' u='r' c='_ZN7WebCore24WorkerModuleScriptLoader4loadERNS_22ScriptExecutionContextEON3WTF3URLE'/>
<use f='WebKit/Source/WebCore/workers/WorkerScriptLoader.cpp' l='67' u='r' c='_ZN7WebCore18WorkerScriptLoader17loadSynchronouslyEPNS_22ScriptExecutionContextERKN3WTF3URLENS_12FetchOptions4ModeENS7_5CacheENS_32ContentSecurityPoli15627940'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerGlobalScope.cpp' l='172' u='w' c='_ZN7WebCore24ServiceWorkerGlobalScope20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_E8252197'/>
<use f='WebKit/Source/WebCore/workers/service/server/RegistrationDatabase.cpp' l='478' u='r' c='_ZN7WebCore20RegistrationDatabase13doPushChangesERKN3WTF6VectorINS_24ServiceWorkerContextDataELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEERKNS2_6518018'/>
<use f='WebKit/Source/WebCore/workers/service/server/SWServerWorker.cpp' l='269' u='w' c='_ZN7WebCore14SWServerWorker20didSaveScriptsToDiskEONS_12ScriptBufferEON3WTF7HashMapINS3_3URLES1_NS3_11DefaultHashIS5_EENS3_10HashTraitsIS5_EENS8_IS1_E14208208'/>
