<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/ClipboardEvent.h' l='37' ll='39'/>
<use f='WebKit/Source/WebCore/dom/ClipboardEvent.h' l='46' c='_ZN7WebCore14ClipboardEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/ClipboardEvent.h' l='55' c='_ZN7WebCore14ClipboardEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::ClipboardEvent::Init::clipboardData' o='64' t='RefPtr&lt;WebCore::DataTransfer&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSClipboardEvent.cpp' l='166' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='WebKit/Source/WebCore/dom/ClipboardEvent.cpp' l='39' c='_ZN7WebCore14ClipboardEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>16</size>
