<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/html/canvas/WebGLContextEvent.h' l='42' ll='44'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLContextEvent.h' l='46' c='_ZN7WebCore17WebGLContextEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLContextEvent.h' l='58' c='_ZN7WebCore17WebGLContextEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.h' l='81' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::WebGLContextEvent::Init::statusMessage' o='64' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSWebGLContextEvent.cpp' l='166' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='WebKit/Source/WebCore/html/canvas/WebGLContextEvent.cpp' l='43' c='_ZN7WebCore17WebGLContextEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>16</size>
