<dec f='WebKit/Source/WebCore/workers/service/ServiceWorkerContainer.h' l='131' type='std::unique_ptr&lt;ServiceWorkerJob&gt;'/>
<offset>0</offset>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContainer.cpp' l='546' u='m' c='_ZN7WebCore22ServiceWorkerContainer4stopEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContainer.cpp' l='547' u='m' c='_ZN7WebCore22ServiceWorkerContainer4stopEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContainer.cpp' l='547' u='m' c='_ZN7WebCore22ServiceWorkerContainer4stopEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerContainer.cpp' l='569' u='m' c='_ZN7WebCore22ServiceWorkerContainer3jobEN3WTF16ObjectIdentifierINS_30ServiceWorkerJobIdentifierTypeEEE'/>
