<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/html/SubmitEvent.h' l='39' ll='41'/>
<use f='WebKit/Source/WebCore/html/SubmitEvent.h' l='43' c='_ZN7WebCore11SubmitEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='WebKit/Source/WebCore/html/SubmitEvent.h' l='49' c='_ZN7WebCore11SubmitEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::SubmitEvent::Init::submitter' o='64' t='RefPtr&lt;WebCore::HTMLElement&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSubmitEvent.cpp' l='166' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
<use f='WebKit/Source/WebCore/html/SubmitEvent.cpp' l='37' c='_ZN7WebCore11SubmitEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='WebKit/Source/WebCore/html/SubmitEvent.cpp' l='47' c='_ZN7WebCore11SubmitEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<size>16</size>
