<dec f='WebKit/Source/WebCore/loader/cache/CachedResource.h' l='71' type='3'/>
<use f='WebKit/Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp' l='141' c='_ZN6WebKitL20maximumBufferingTimeEPN7WebCore14CachedResourceE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedScript.h' l='67' u='r' c='_ZN3WTF14TypeCastTraitsIKN7WebCore12CachedScriptET_Lb0EE6isTypeERKNS1_14CachedResourceE'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp' l='1396' c='_ZN7WebCore21InspectorNetworkAgent21cachedResourceContentERNS_14CachedResourceEPN3WTF6StringEPb'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorPageAgent.cpp' l='260' c='_ZN7WebCore18InspectorPageAgent21inspectorResourceTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/html/parser/HTMLPreloadScanner.cpp' l='339' u='a' c='_ZNK7WebCore19TokenPreloadScanner15StartTagScanner12resourceTypeEv'/>
<use f='WebKit/Source/WebCore/html/parser/HTMLResourcePreloader.cpp' l='50' u='r' c='_ZN7WebCore14PreloadRequest15resourceRequestERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/html/parser/HTMLResourcePreloader.cpp' l='64' u='r' c='_ZN7WebCore14PreloadRequest15resourceRequestERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/html/parser/HTMLResourcePreloader.cpp' l='69' u='r' c='_ZN7WebCore14PreloadRequest15resourceRequestERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/loader/DefaultResourceLoadPriority.cpp' l='36' c='_ZN7WebCore27DefaultResourceLoadPriority15forResourceTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResource.cpp' l='78' u='r' c='_ZN7WebCoreL46deadDecodedDataDeletionIntervalForResourceTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='123' c='_ZN7WebCoreL14createResourceENS_14CachedResource4TypeEONS_21CachedResourceRequestEN3PAL9SessionIDEPKNS_9CookieJarERKNS_8SettingsE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='165' c='_ZN7WebCoreL14createResourceEONS_21CachedResourceRequestERNS_14CachedResourceE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='302' u='r' c='_ZN7WebCore20CachedResourceLoader13requestScriptEONS_21CachedResourceRequestE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='398' c='_ZN7WebCoreL27contentTypeFromResourceTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='439' c='_ZNK7WebCore20CachedResourceLoader20checkInsecureContentENS_14CachedResource4TypeERKN3WTF3URLE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='502' c='_ZNK7WebCore20CachedResourceLoader30allowedByContentSecurityPolicyENS_14CachedResource4TypeERKN3WTF3URLERKNS_21ResourceLoaderOptionsENS_21ContentSecur5936905'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='809' c='_ZN7WebCoreL18destinationForTypeENS_14CachedResource4TypeE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedResourceLoader.cpp' l='1508' u='r' c='_ZN7WebCore20CachedResourceLoader7preloadENS_14CachedResource4TypeEONS_21CachedResourceRequestE'/>
<use f='WebKit/Source/WebCore/loader/cache/CachedScript.cpp' l='40' u='r' c='_ZN7WebCore12CachedScriptC1EONS_21CachedResourceRequestEN3PAL9SessionIDEPKNS_9CookieJarE'/>
<use f='WebKit/Source/WebCore/loader/cache/MemoryCache.cpp' l='642' c='_ZN7WebCore11MemoryCache13getStatisticsEv'/>
<use f='WebKit/Source/WebCore/loader/LinkLoader.cpp' l='128' u='a' c='_ZN7WebCore10LinkLoader27resourceTypeFromAsAttributeERKN3WTF6StringERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/loader/LinkLoader.cpp' l='145' c='_ZN7WebCoreL31createLinkPreloadResourceClientERNS_14CachedResourceERNS_10LinkLoaderERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/loader/LinkLoader.cpp' l='187' c='_ZN7WebCore10LinkLoader15isSupportedTypeENS_14CachedResource4TypeERKN3WTF6StringERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/loader/ResourceLoadInfo.cpp' l='54' c='_ZN7WebCore17ContentExtensions14toResourceTypeENS_14CachedResource4TypeENS_19ResourceRequestBase9RequesterE'/>
<use f='WebKit/Source/WebCore/loader/SubresourceLoader.cpp' l='589' c='_ZN7WebCoreL17logResourceLoadedEPNS_5FrameENS_14CachedResource4TypeE'/>
