<def f='WebKit/Source/WebCore/page/UndoItem.h' l='42' ll='46'/>
<use f='WebKit/Source/WebCore/page/UndoItem.h' l='48' c='_ZN7WebCore8UndoItem6createEONS0_4InitE'/>
<use f='WebKit/Source/WebCore/page/UndoItem.h' l='66' c='_ZN7WebCore8UndoItemC1EONS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.h' l='97' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSUndoItem.cpp' l='157' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<mbr r='WebCore::UndoItem::Init::label' o='0' t='WTF::String'/>
<mbr r='WebCore::UndoItem::Init::undo' o='64' t='RefPtr&lt;WebCore::VoidCallback&gt;'/>
<mbr r='WebCore::UndoItem::Init::redo' o='128' t='RefPtr&lt;WebCore::VoidCallback&gt;'/>
