<def f='WebKit/Source/WebCore/editing/Editor.h' l='282' ll='304'/>
<use f='WebKit/Source/WebCore/editing/Editor.h' l='305' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/editing/Editor.h' l='306' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<size>32</size>
<fun r='_ZN7WebCore6Editor7CommandC1Ev'/>
<fun r='_ZN7WebCore6Editor7CommandC1EPKNS_21EditorInternalCommandENS_19EditorCommandSourceERNS_8DocumentE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeERKN3WTF6StringEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command11isSupportedEv'/>
<fun r='_ZNK7WebCore6Editor7Command9isEnabledEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5stateEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5valueEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command15isTextInsertionEv'/>
<fun r='_ZNK7WebCore6Editor7Command26allowExecutionWhenDisabledEv'/>
<mbr r='WebCore::Editor::Command::m_command' o='0' t='const WebCore::EditorInternalCommand *'/>
<mbr r='WebCore::Editor::Command::m_source' o='64' t='WebCore::EditorCommandSource'/>
<mbr r='WebCore::Editor::Command::m_document' o='128' t='RefPtr&lt;WebCore::Document&gt;'/>
<mbr r='WebCore::Editor::Command::m_frame' o='192' t='RefPtr&lt;WebCore::Frame&gt;'/>
<use f='WebKit/Source/WebCore/page/ContextMenuController.cpp' l='1236' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<use f='WebKit/Source/WebCore/page/ContextMenuController.cpp' l='1242' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<use f='WebKit/Source/WebCore/page/ContextMenuController.cpp' l='1248' c='_ZNK7WebCore21ContextMenuController21checkOrEnableIfNeededERNS_15ContextMenuItemE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/dom/Document.cpp' l='5746' c='_ZN7WebCoreL7commandEPNS_8DocumentERKN3WTF6StringEb'/>
<use f='WebKit/Source/WebCore/dom/Document.cpp' l='5755' c='_ZN7WebCoreL7commandEPNS_8DocumentERKN3WTF6StringEb'/>
<size>32</size>
<use f='WebKit/Source/WebCore/editing/EditorCommand.cpp' l='1820' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/editing/EditorCommand.cpp' l='1822' c='_ZN7WebCore6Editor7commandERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/editing/EditorCommand.cpp' l='1825' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<use f='WebKit/Source/WebCore/editing/EditorCommand.cpp' l='1827' c='_ZN7WebCore6Editor7commandERKN3WTF6StringENS_19EditorCommandSourceE'/>
<size>32</size>
<fun r='_ZN7WebCore6Editor7CommandC1Ev'/>
<fun r='_ZN7WebCore6Editor7CommandC1EPKNS_21EditorInternalCommandENS_19EditorCommandSourceERNS_8DocumentE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeERKN3WTF6StringEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command7executeEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command11isSupportedEv'/>
<fun r='_ZNK7WebCore6Editor7Command9isEnabledEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5stateEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command5valueEPNS_5EventE'/>
<fun r='_ZNK7WebCore6Editor7Command15isTextInsertionEv'/>
<fun r='_ZNK7WebCore6Editor7Command26allowExecutionWhenDisabledEv'/>
