<def f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='390' type='const GCGLenum'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='372' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='373' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='380' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='381' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='382' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLCommon.cpp' l='1950' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL13texSubImage2DEjiiiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='49' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='85' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='194' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='225' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='572' u='r' c='_ZN7WebCore17GraphicsContextGL30computeFormatAndTypeParametersEjjPjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='124' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='125' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='126' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='127' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='409'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='409' u='r'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4182' u='r' c='_ZN7WebCoreL27numberOfComponentsForFormatEj'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5598' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5599' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5600' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5601' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
