<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionActions.h' l='74'/>
<def f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='126' ll='164'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='141' c='_ZN7WebCore17ContentExtensions6ActionC1EOS1_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='143' c='_ZNK7WebCore17ContentExtensions6ActioneqERKS1_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='150' c='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='158' c='_ZNK7WebCore17ContentExtensions6Action12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='168' c='_ZN7WebCore17ContentExtensions20ContentExtensionRuleC1EONS0_7TriggerEONS0_6ActionE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='171' c='_ZNK7WebCore17ContentExtensions20ContentExtensionRule6actionEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='184'/>
<size>16</size>
<fun r='_ZN7WebCore17ContentExtensions6ActionC1ENS0_10ActionTypeERKN3WTF6StringEj'/>
<fun r='_ZN7WebCore17ContentExtensions6ActionC1ENS0_10ActionTypeEj'/>
<fun r='_ZN7WebCore17ContentExtensions6ActionC1EOS1_'/>
<fun r='_ZNK7WebCore17ContentExtensions6ActioneqERKS1_'/>
<fun r='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<fun r='_ZN7WebCore17ContentExtensions6Action15deserializeTypeEPKhjj'/>
<fun r='_ZN7WebCore17ContentExtensions6Action16serializedLengthEPKhjj'/>
<fun r='_ZNK7WebCore17ContentExtensions6Action4typeEv'/>
<fun r='_ZNK7WebCore17ContentExtensions6Action8actionIDEv'/>
<fun r='_ZNK7WebCore17ContentExtensions6Action14stringArgumentEv'/>
<fun r='_ZNK7WebCore17ContentExtensions6Action12isolatedCopyEv'/>
<mbr r='WebCore::ContentExtensions::Action::m_type' o='0' t='WebCore::ContentExtensions::ActionType'/>
<mbr r='WebCore::ContentExtensions::Action::m_actionID' o='32' t='uint32_t'/>
<mbr r='WebCore::ContentExtensions::Action::m_stringArgument' o='64' t='WTF::String'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtension.cpp' l='100' c='_ZN7WebCore17ContentExtensions16ContentExtension34compileGlobalDisplayNoneStyleSheetEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='250' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='266' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='268' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='270' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='281' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='284' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='289' c='_ZN7WebCore17ContentExtensionsL10loadActionERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='35' c='_ZN7WebCore17ContentExtensions20ContentExtensionRuleC1EONS0_7TriggerEONS0_6ActionE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='58' c='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='67' c='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='70' c='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='128' c='_ZNK7WebCore17ContentExtensions6Action12isolatedCopyEv'/>
<size>16</size>
<fun r='_ZN7WebCore17ContentExtensions6Action11deserializeEPKhjj'/>
<fun r='_ZN7WebCore17ContentExtensions6Action15deserializeTypeEPKhjj'/>
<fun r='_ZN7WebCore17ContentExtensions6Action16serializedLengthEPKhjj'/>
<fun r='_ZNK7WebCore17ContentExtensions6Action12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionsBackend.cpp' l='151' c='_ZNK7WebCore17ContentExtensions24ContentExtensionsBackend22actionsForResourceLoadERKNS0_16ResourceLoadInfoE'/>
<size>16</size>
