<dec f='WebKit/Source/WebCore/workers/service/ServiceWorkerFetchResult.h' l='41' type='WebCore::ScriptBuffer'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerFetchResult.h' l='47' u='m' c='_ZNK7WebCore24ServiceWorkerFetchResult12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerFetchResult.h' l='47' u='m' c='_ZNK7WebCore24ServiceWorkerFetchResult12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerFetchResult.h' l='61' c='_ZNK7WebCore24ServiceWorkerFetchResult6encodeERT_'/>
<use f='WebKit/Source/WebCore/workers/service/ServiceWorkerFetchResult.h' l='79' c='_ZN7WebCore24ServiceWorkerFetchResult6decodeERT_RS0_'/>
<offset>640</offset>
<use f='WebKit/Source/WebCore/workers/service/server/SWServerJobQueue.cpp' l='103' u='r' c='_ZN7WebCore16SWServerJobQueue19scriptFetchFinishedERKNS_24ServiceWorkerFetchResultE'/>
<use f='WebKit/Source/WebCore/workers/service/server/SWServerJobQueue.cpp' l='117' u='r' c='_ZN7WebCore16SWServerJobQueue19scriptFetchFinishedERKNS_24ServiceWorkerFetchResultE'/>
