<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/SecurityPolicyViolationEvent.h' l='37' ll='55'/>
<use f='WebKit/Source/WebCore/dom/SecurityPolicyViolationEvent.h' l='54' c='_ZN7WebCore28SecurityPolicyViolationEvent4Init6decodeERT_RS1_'/>
<use f='WebKit/Source/WebCore/dom/SecurityPolicyViolationEvent.h' l='57' c='_ZN7WebCore28SecurityPolicyViolationEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/SecurityPolicyViolationEvent.h' l='82' c='_ZN7WebCore28SecurityPolicyViolationEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/SecurityPolicyViolationEvent.h' l='132' c='_ZN7WebCore28SecurityPolicyViolationEvent4Init6decodeERT_RS1_'/>
<use f='WebKit/Source/WebCore/dom/Document.h' l='1170' c='_ZN7WebCore8Document35enqueueSecurityPolicyViolationEventEONS_28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
<fun r='_ZN7WebCore28SecurityPolicyViolationEvent4InitC1Ev'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::documentURI' o='64' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::referrer' o='128' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::blockedURI' o='192' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::violatedDirective' o='256' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::effectiveDirective' o='320' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::originalPolicy' o='384' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::sourceFile' o='448' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::sample' o='512' t='WTF::String'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::disposition' o='576' t='WebCore::SecurityPolicyViolationEvent::Disposition'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::statusCode' o='592' t='unsigned short'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::lineNumber' o='608' t='unsigned int'/>
<mbr r='WebCore::SecurityPolicyViolationEvent::Init::columnNumber' o='640' t='unsigned int'/>
<fun r='_ZNK7WebCore28SecurityPolicyViolationEvent4Init6encodeERT_'/>
<fun r='_ZN7WebCore28SecurityPolicyViolationEvent4Init6decodeERT_RS1_'/>
<fun r='_ZNK7WebCore28SecurityPolicyViolationEvent4Init6encodeERT_'/>
<fun r='_ZN7WebCore28SecurityPolicyViolationEvent4Init6decodeERT_RS1_'/>
<use f='WebKit/Source/WebCore/page/csp/ContentSecurityPolicyClient.h' l='54' c='_ZN7WebCore27ContentSecurityPolicyClient35enqueueSecurityPolicyViolationEventEONS_28SecurityPolicyViolationEvent4InitE'/>
<use f='WebKit/Source/WebCore/loader/DocumentLoader.h' l='515' c='_ZN7WebCore14DocumentLoader35enqueueSecurityPolicyViolationEventEONS_28SecurityPolicyViolationEvent4InitE'/>
<use f='WebKit/Source/WebKit/WebProcess/WebPage/WebPage.h' l='435' c='_ZN6WebKit7WebPage35enqueueSecurityPolicyViolationEventEN3WTF16ObjectIdentifierIN7WebCore19FrameIdentifierTypeEEEONS3_28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
<use f='WebKit/Source/WebKit/NetworkProcess/NetworkResourceLoader.h' l='201' c='_ZN6WebKit21NetworkResourceLoader35enqueueSecurityPolicyViolationEventEON7WebCore28SecurityPolicyViolationEvent4InitE'/>
<use f='WebKit/Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp' l='1424' c='_ZN6WebKit21NetworkResourceLoader35enqueueSecurityPolicyViolationEventEON7WebCore28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
<use f='WebKit/Source/WebKit/WebProcess/WebPage/WebPage.cpp' l='4280' c='_ZN6WebKit7WebPage35enqueueSecurityPolicyViolationEventEN3WTF16ObjectIdentifierIN7WebCore19FrameIdentifierTypeEEEONS3_28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.h' l='86' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.h' l='86' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>88</size>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.cpp' l='85' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.cpp' l='85' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.cpp' l='95' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSecurityPolicyViolationEvent.cpp' l='372' c='_ZN7WebCoreL40constructJSSecurityPolicyViolationEvent2EPN3JSC14JSGlobalObjectEPNS0_9CallFrameE'/>
<size>88</size>
<use f='WebKit/Source/WebCore/page/csp/ContentSecurityPolicy.cpp' l='707' c='_ZNK7WebCore21ContentSecurityPolicy15reportViolationERKN3WTF6StringES4_RKNS_34ContentSecurityPolicyDirectiveListERKNS1_3URLES4_S4_RKNS1_12TextPosition3282665'/>
<size>88</size>
<use f='WebKit/Source/WebCore/dom/Document.cpp' l='6655' c='_ZN7WebCore8Document35enqueueSecurityPolicyViolationEventEONS_28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
<use f='WebKit/Source/WebCore/loader/DocumentLoader.cpp' l='2315' c='_ZN7WebCore14DocumentLoader35enqueueSecurityPolicyViolationEventEONS_28SecurityPolicyViolationEvent4InitE'/>
<size>88</size>
