<def f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.h' l='559' type='const GCGLenum'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLBase.cpp' l='379' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL10texImage2DEjijiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGLCommon.cpp' l='1954' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL13texSubImage2DEjiiiiijj8GCGLSpanIKvLm18446744073709551615EE'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='53' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='89' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='187' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='218' u='r' c='_ZN7WebCoreL13getDataFormatEjj'/>
<use f='WebKit/Source/WebCore/platform/graphics/GraphicsContextGL.cpp' l='579' u='r' c='_ZN7WebCore17GraphicsContextGL30computeFormatAndTypeParametersEjjPjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='134' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='135' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='136' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/platform/graphics/opengl/GraphicsContextGLOpenGL.cpp' l='137' u='r' c='_ZN7WebCore23GraphicsContextGLOpenGL38possibleFormatAndTypeForInternalFormatEjRjS1_'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='411'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='411' u='r'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4185' u='r' c='_ZN7WebCoreL27numberOfComponentsForFormatEj'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='4359' u='r' c='_ZN7WebCore25WebGLRenderingContextBase10readPixelsEiiiijjRN3JSC15ArrayBufferViewE'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5608' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5609' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5610' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
<use f='WebKit/Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp' l='5611' u='r' c='_ZN7WebCore25WebGLRenderingContextBase28validateTexFuncFormatAndTypeEPKcjjji'/>
