<dec f='WebKit/Source/WebCore/dom/FocusOptions.h' l='35' type='1'/>
<use f='WebKit/Source/WebCore/dom/Document.h' l='766' u='r' c='_ZNK7WebCore8Document19wasLastFocusByClickEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='2752' u='r' c='_ZN7WebCore12EventHandler18dispatchMouseEventERKN3WTF10AtomStringEPNS_4NodeEiRKNS_18PlatformMouseEventENS0_16FireMouseOverOutE'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='2752' u='r' c='_ZN7WebCore12EventHandler18dispatchMouseEventERKN3WTF10AtomStringEPNS_4NodeEiRKNS_18PlatformMouseEventENS0_16FireMouseOverOutE'/>
