<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/PromiseRejectionEvent.h' l='38' ll='41'/>
<use f='WebKit/Source/WebCore/dom/PromiseRejectionEvent.h' l='43' c='_ZN7WebCore21PromiseRejectionEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/PromiseRejectionEvent.h' l='56' c='_ZN7WebCore21PromiseRejectionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>24</size>
<mbr r='WebCore::PromiseRejectionEvent::Init::promise' o='64' t='RefPtr&lt;WebCore::DOMPromise&gt;'/>
<mbr r='WebCore::PromiseRejectionEvent::Init::reason' o='128' t='JSC::JSValue'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.cpp' l='54' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.cpp' l='54' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.cpp' l='64' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPromiseRejectionEvent.cpp' l='182' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<use f='WebKit/Source/WebCore/dom/PromiseRejectionEvent.cpp' l='40' c='_ZN7WebCore21PromiseRejectionEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
<use f='WebKit/Source/WebCore/dom/RejectedPromiseTracker.cpp' l='164' c='_ZN7WebCore22RejectedPromiseTracker25reportUnhandledRejectionsEON3WTF6VectorINS_16UnhandledPromiseELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE'/>
<use f='WebKit/Source/WebCore/dom/RejectedPromiseTracker.cpp' l='193' c='_ZN7WebCore22RejectedPromiseTracker22reportRejectionHandledEON3WTF3RefINS_10DOMPromiseENS1_12RawPtrTraitsIS3_EEEE'/>
<size>24</size>
