<inh f='WebKit/Source/WebCore/dom/MouseEventInit.h' l='32' c='WebCore::MouseEventInit'/>
<def f='WebKit/Source/WebCore/dom/PointerEvent.h' l='45' ll='56'/>
<use f='WebKit/Source/WebCore/dom/PointerEvent.h' l='60' c='_ZN7WebCore12PointerEvent6createERKN3WTF10AtomStringEONS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/PointerEvent.h' l='67' c='_ZN7WebCore12PointerEvent23createForPointerCaptureERKN3WTF10AtomStringEibNS1_6StringE'/>
<use f='WebKit/Source/WebCore/dom/PointerEvent.h' l='121' c='_ZN7WebCore12PointerEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<size>128</size>
<mbr r='WebCore::PointerEvent::Init::pointerId' o='448' t='WebCore::PointerID'/>
<mbr r='WebCore::PointerEvent::Init::width' o='512' t='double'/>
<mbr r='WebCore::PointerEvent::Init::height' o='576' t='double'/>
<mbr r='WebCore::PointerEvent::Init::pressure' o='640' t='float'/>
<mbr r='WebCore::PointerEvent::Init::tangentialPressure' o='672' t='float'/>
<mbr r='WebCore::PointerEvent::Init::tiltX' o='704' t='long'/>
<mbr r='WebCore::PointerEvent::Init::tiltY' o='768' t='long'/>
<mbr r='WebCore::PointerEvent::Init::twist' o='832' t='long'/>
<mbr r='WebCore::PointerEvent::Init::pointerType' o='896' t='WTF::String'/>
<mbr r='WebCore::PointerEvent::Init::isPrimary' o='960' t='bool'/>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>128</size>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.cpp' l='54' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.cpp' l='54' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.cpp' l='64' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSPointerEvent.cpp' l='464' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>128</size>
<use f='WebKit/Source/WebCore/dom/PointerEvent.cpp' l='79' c='_ZN7WebCore12PointerEventC1ERKN3WTF10AtomStringEONS0_4InitE'/>
<size>128</size>
