<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/Modules/websockets/CloseEvent.h' l='46' ll='50'/>
<use f='WebKit/Source/WebCore/Modules/websockets/CloseEvent.h' l='52' c='_ZN7WebCore10CloseEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/websockets/CloseEvent.h' l='73' c='_ZN7WebCore10CloseEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>16</size>
<mbr r='WebCore::CloseEvent::Init::wasClean' o='24' t='bool'/>
<mbr r='WebCore::CloseEvent::Init::code' o='32' t='unsigned short'/>
<mbr r='WebCore::CloseEvent::Init::reason' o='64' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCloseEvent.cpp' l='190' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>16</size>
