<use f='WebKit/Source/WebCore/style/StyleBuilderState.h' l='56' c='_ZN7WebCore5Style12BuilderStateC1ERNS0_7BuilderERNS_11RenderStyleEONS0_14BuilderContextE'/>
<use f='WebKit/Source/WebCore/style/StyleBuilderState.h' l='58' c='_ZN7WebCore5Style12BuilderState7builderEv'/>
<use f='WebKit/Source/WebCore/style/StyleBuilderState.h' l='106'/>
<use f='WebKit/Source/WebCore/style/StyleBuilderState.h' l='118'/>
<def f='WebKit/Source/WebCore/style/StyleBuilder.h' l='35' ll='68'/>
<use f='WebKit/Source/WebCore/style/StyleBuilderState.cpp' l='58' c='_ZN7WebCore5Style12BuilderStateC1ERNS0_7BuilderERNS_11RenderStyleEONS0_14BuilderContextE'/>
<size>16280</size>
<fun r='_ZN7WebCore5Style7BuilderC1ERNS_11RenderStyleEONS0_14BuilderContextERKNS0_11MatchResultEN3WTF9OptionSetINS0_12CascadeLevelEEENS0_15PropertyCascade18IncludedPropertiesE'/>
<fun r='_ZN7WebCore5Style7BuilderD1Ev'/>
<fun r='_ZN7WebCore5Style7Builder18applyAllPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder27applyHighPriorityPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder26applyLowPriorityPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder13applyPropertyENS_13CSSPropertyIDE'/>
<fun r='_ZN7WebCore5Style7Builder19applyCustomPropertyERKN3WTF6StringE'/>
<fun r='_ZN7WebCore5Style7Builder18applyPropertyValueENS_13CSSPropertyIDEPNS_8CSSValueE'/>
<fun r='_ZN7WebCore5Style7Builder5stateEv'/>
<fun r='_ZN7WebCore5Style7Builder15applyPropertiesEii'/>
<fun r='_ZN7WebCore5Style7Builder23applyDeferredPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder21applyCustomPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder19applyPropertiesImplEii'/>
<fun r='_ZN7WebCore5Style7Builder20applyCascadePropertyERKNS0_15PropertyCascade8PropertyE'/>
<fun r='_ZN7WebCore5Style7Builder13applyPropertyENS_13CSSPropertyIDERNS_8CSSValueENS_15SelectorChecker13LinkMatchMaskE'/>
<fun r='_ZN7WebCore5Style7Builder12resolveValueENS_13CSSPropertyIDERNS_8CSSValueE'/>
<fun r='_ZN7WebCore5Style7Builder21resolvedVariableValueENS_13CSSPropertyIDERKNS_8CSSValueE'/>
<mbr r='WebCore::Style::Builder::m_cascade' o='0' t='const WebCore::Style::PropertyCascade'/>
<mbr r='WebCore::Style::Builder::m_state' o='127936' t='WebCore::Style::BuilderState'/>
<fun r='_ZN7WebCore5Style7BuilderC1ERNS_11RenderStyleEONS0_14BuilderContextERKNS0_11MatchResultEN3WTF9OptionSetINS0_12CascadeLevelEEENS0_15PropertyCascade18IncludedPropertiesE'/>
<fun r='_ZN7WebCore5Style7BuilderD1Ev'/>
<fun r='_ZN7WebCore5Style7Builder18applyAllPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder27applyHighPriorityPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder26applyLowPriorityPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder18applyPropertyValueENS_13CSSPropertyIDEPNS_8CSSValueE'/>
<fun r='_ZN7WebCore5Style7Builder23applyDeferredPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder15applyPropertiesEii'/>
<fun r='_ZN7WebCore5Style7Builder19applyPropertiesImplEii'/>
<fun r='_ZN7WebCore5Style7Builder21applyCustomPropertiesEv'/>
<fun r='_ZN7WebCore5Style7Builder19applyCustomPropertyERKN3WTF6StringE'/>
<fun r='_ZN7WebCore5Style7Builder20applyCascadePropertyERKNS0_15PropertyCascade8PropertyE'/>
<fun r='_ZN7WebCore5Style7Builder13applyPropertyENS_13CSSPropertyIDERNS_8CSSValueENS_15SelectorChecker13LinkMatchMaskE'/>
<fun r='_ZN7WebCore5Style7Builder12resolveValueENS_13CSSPropertyIDERNS_8CSSValueE'/>
<fun r='_ZN7WebCore5Style7Builder21resolvedVariableValueENS_13CSSPropertyIDERKNS_8CSSValueE'/>
<use f='WebKit/Source/WebCore/style/StyleResolver.cpp' l='272' c='_ZN7WebCore5Style8Resolver16styleForKeyframeERKNS_7ElementEPKNS_11RenderStyleES7_PKNS_17StyleRuleKeyframeERNS_13KeyframeValueE'/>
<use f='WebKit/Source/WebCore/style/StyleResolver.cpp' l='427' c='_ZN7WebCore5Style8Resolver12styleForPageEi'/>
<use f='WebKit/Source/WebCore/style/StyleResolver.cpp' l='545' c='_ZN7WebCore5Style8Resolver22applyMatchedPropertiesERNS1_5StateERKNS0_11MatchResultENS1_27UseMatchedDeclarationsCacheE'/>
<use f='WebKit/Source/WebCore/style/StyleResolver.cpp' l='551' c='_ZN7WebCore5Style8Resolver22applyMatchedPropertiesERNS1_5StateERKNS0_11MatchResultENS1_27UseMatchedDeclarationsCacheE'/>
<size>16280</size>
<use f='WebKit/Source/WebCore/css/DOMCSSRegisterCustomProperty.cpp' l='68' c='_ZN7WebCore28DOMCSSRegisterCustomProperty16registerPropertyERNS_8DocumentERKNS_30DOMCSSCustomPropertyDescriptorE'/>
<size>16280</size>
