<def f='WebKit/Source/WebCore/inspector/InspectorHistory.h' l='42' ll='59'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.h' l='48' c='_ZN7WebCore16InspectorHistory6Action5mergeESt10unique_ptrIS1_St14default_deleteIS1_EE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.h' l='63' c='_ZN7WebCore16InspectorHistory7performESt10unique_ptrINS0_6ActionESt14default_deleteIS2_EE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.h' l='71'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='46' c='WebCore::DOMEditor::RemoveChildAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='46'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='50' c='_ZN7WebCore9DOMEditor17RemoveChildActionC1ERNS_4NodeES3_'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='78' c='WebCore::DOMEditor::InsertBeforeAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='78'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='81' c='_ZN7WebCore9DOMEditor18InsertBeforeActionC1ERNS_4NodeEON3WTF3RefIS2_NS4_12RawPtrTraitsIS2_EEEEPS2_'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='126' c='WebCore::DOMEditor::RemoveAttributeAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='126'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='130' c='_ZN7WebCore9DOMEditor21RemoveAttributeActionC1ERNS_7ElementERKN3WTF6StringE'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='159' c='WebCore::DOMEditor::SetAttributeAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='159'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='163' c='_ZN7WebCore9DOMEditor18SetAttributeActionC1ERNS_7ElementERKN3WTF10AtomStringES7_'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='197' c='WebCore::DOMEditor::SetOuterHTMLAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='197'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='200' c='_ZN7WebCore9DOMEditor18SetOuterHTMLActionC1ERNS_4NodeERKN3WTF6StringE'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='242' c='WebCore::DOMEditor::InsertAdjacentHTMLAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='242'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='246' c='_ZN7WebCore9DOMEditor24InsertAdjacentHTMLActionC1ERNS_7ElementERKN3WTF6StringES7_'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='281' c='WebCore::DOMEditor::ReplaceWholeTextAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='281'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='285' c='_ZN7WebCore9DOMEditor22ReplaceWholeTextActionC1ERNS_4TextERKN3WTF6StringE'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='315' c='WebCore::DOMEditor::ReplaceChildNodeAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='315'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='319' c='_ZN7WebCore9DOMEditor22ReplaceChildNodeActionC1ERNS_4NodeEON3WTF3RefIS2_NS4_12RawPtrTraitsIS2_EEEES3_'/>
<ovr f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='347' c='WebCore::DOMEditor::SetNodeValueAction'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='347'/>
<use f='WebKit/Source/WebCore/inspector/DOMEditor.cpp' l='351' c='_ZN7WebCore9DOMEditor18SetNodeValueActionC1ERNS_4NodeERKN3WTF6StringE'/>
<size>16</size>
<fun r='_ZN7WebCore16InspectorHistory6ActionD1Ev'/>
<fun r='_ZN7WebCore16InspectorHistory6Action7mergeIdEv'/>
<fun r='_ZN7WebCore16InspectorHistory6Action5mergeESt10unique_ptrIS1_St14default_deleteIS1_EE'/>
<fun r='_ZN7WebCore16InspectorHistory6Action7performEv'/>
<fun r='_ZN7WebCore16InspectorHistory6Action4undoEv'/>
<fun r='_ZN7WebCore16InspectorHistory6Action4redoEv'/>
<fun r='_ZN7WebCore16InspectorHistory6Action19isUndoableStateMarkEv'/>
<mbr r='WebCore::InspectorHistory::Action::m_name' o='64' t='WTF::String'/>
<ovr f='WebKit/Source/WebCore/inspector/InspectorHistory.cpp' l='38' c='WebCore::UndoableStateMark'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.cpp' l='38'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.cpp' l='46' c='_ZN7WebCore16InspectorHistory7performESt10unique_ptrINS0_6ActionESt14default_deleteIS2_EE'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.cpp' l='73' c='_ZN7WebCore16InspectorHistory4undoEv'/>
<use f='WebKit/Source/WebCore/inspector/InspectorHistory.cpp' l='93' c='_ZN7WebCore16InspectorHistory4redoEv'/>
<size>16</size>
<ovr f='WebKit/Source/WebCore/inspector/agents/InspectorCSSAgent.cpp' l='114' c='WebCore::InspectorCSSAgent::StyleSheetAction'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorCSSAgent.cpp' l='114'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorCSSAgent.cpp' l='118' c='_ZN7WebCore17InspectorCSSAgent16StyleSheetActionC1EPNS_19InspectorStyleSheetE'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorCSSAgent.cpp' l='169' c='_ZN7WebCore17InspectorCSSAgent23SetStyleSheetTextAction5mergeESt10unique_ptrINS_16InspectorHistory6ActionESt14default_deleteIS4_EE'/>
<use f='WebKit/Source/WebCore/inspector/agents/InspectorCSSAgent.cpp' l='210' c='_ZN7WebCore17InspectorCSSAgent18SetStyleTextAction5mergeESt10unique_ptrINS_16InspectorHistory6ActionESt14default_deleteIS4_EE'/>
<size>16</size>
