<dec f='WebKit/Source/WebCore/rendering/HitTestRequest.h' l='35' type='4'/>
<use f='WebKit/Source/WebCore/rendering/HitTestRequest.h' l='63' u='r' c='_ZNK7WebCore14HitTestRequest4moveEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='935' u='r' c='_ZN7WebCore12EventHandler27updateSelectionForMouseDragEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='935' u='r' c='_ZN7WebCore12EventHandler27updateSelectionForMouseDragEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='1962' u='r' c='_ZN7WebCore12EventHandler20handleMouseMoveEventERKNS_18PlatformMouseEventEPNS_13HitTestResultEb'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='1962' u='r' c='_ZN7WebCore12EventHandler20handleMouseMoveEventERKNS_18PlatformMouseEventEPNS_13HitTestResultEb'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='3386' u='r' c='_ZN7WebCore12EventHandler15hoverTimerFiredEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='3386' u='r' c='_ZN7WebCore12EventHandler15hoverTimerFiredEv'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='4497' u='r' c='_ZN7WebCore12EventHandler16handleTouchEventERKNS_18PlatformTouchEventE'/>
<use f='WebKit/Source/WebCore/page/EventHandler.cpp' l='4497' u='r' c='_ZN7WebCore12EventHandler16handleTouchEventERKNS_18PlatformTouchEventE'/>
