<def f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='44' ll='87'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='59' c='_ZNK7WebCore17ContentExtensions7Trigger12isolatedCopyEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='78' c='_ZNK7WebCore17ContentExtensions7TriggereqERKS1_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='90' c='_ZN7WebCore17ContentExtensions11TriggerHash4hashERKNS0_7TriggerE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='94' c='_ZN7WebCore17ContentExtensions11TriggerHash5equalERKNS0_7TriggerES4_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='94' c='_ZN7WebCore17ContentExtensions11TriggerHash5equalERKNS0_7TriggerES4_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='101'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='105' c='_ZN7WebCore17ContentExtensions17TriggerHashTraits21constructDeletedValueERNS0_7TriggerE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='110' c='_ZN7WebCore17ContentExtensions17TriggerHashTraits14isDeletedValueERKNS0_7TriggerE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='115' c='_ZN7WebCore17ContentExtensions17TriggerHashTraits10emptyValueEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='117' c='_ZN7WebCore17ContentExtensions17TriggerHashTraits10emptyValueEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='120' c='_ZN7WebCore17ContentExtensions17TriggerHashTraits12isEmptyValueERKNS0_7TriggerE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='168' c='_ZN7WebCore17ContentExtensions20ContentExtensionRuleC1EONS0_7TriggerEONS0_6ActionE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='170' c='_ZNK7WebCore17ContentExtensions20ContentExtensionRule7triggerEv'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='183'/>
<size>40</size>
<doc f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.h' l='39'>// A ContentExtensionRule is the smallest unit in a ContentExtension.
//
// It is composed of a trigger and an action. The trigger defines on what kind of content this extension should apply.
// The action defines what to perform on that content.</doc>
<mbr r='WebCore::ContentExtensions::Trigger::urlFilter' o='0' t='WTF::String'/>
<mbr r='WebCore::ContentExtensions::Trigger::urlFilterIsCaseSensitive' o='64' t='bool'/>
<mbr r='WebCore::ContentExtensions::Trigger::topURLConditionIsCaseSensitive' o='72' t='bool'/>
<mbr r='WebCore::ContentExtensions::Trigger::flags' o='80' t='WebCore::ContentExtensions::ResourceFlags'/>
<mbr r='WebCore::ContentExtensions::Trigger::conditions' o='128' t='Vector&lt;WTF::String&gt;'/>
<mbr r='WebCore::ContentExtensions::Trigger::conditionType' o='256' t='WebCore::ContentExtensions::Trigger::ConditionType'/>
<fun r='_ZNK7WebCore17ContentExtensions7Trigger12isolatedCopyEv'/>
<fun r='_ZN7WebCore17ContentExtensions7TriggerD1Ev'/>
<fun r='_ZNK7WebCore17ContentExtensions7Trigger7isEmptyEv'/>
<fun r='_ZNK7WebCore17ContentExtensions7TriggereqERKS1_'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionCompiler.cpp' l='76'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionCompiler.cpp' l='344' c='_ZN7WebCore17ContentExtensions15compileRuleListERNS0_33ContentExtensionCompilationClientEON3WTF6StringEONS3_6VectorINS0_20ContentExtensionRuleELm0ENS316765909'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='130' c='_ZN7WebCore17ContentExtensionsL11loadTriggerERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionParser.cpp' l='147' c='_ZN7WebCore17ContentExtensionsL11loadTriggerERN3JSC14JSGlobalObjectERKNS1_8JSObjectE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='35' c='_ZN7WebCore17ContentExtensions20ContentExtensionRuleC1EONS0_7TriggerEONS0_6ActionE'/>
<use f='WebKit/Source/WebCore/contentextensions/ContentExtensionRule.cpp' l='116' c='_ZNK7WebCore17ContentExtensions7Trigger12isolatedCopyEv'/>
<size>40</size>
<fun r='_ZNK7WebCore17ContentExtensions7Trigger12isolatedCopyEv'/>
