<def f='WebKit/Source/WebCore/platform/Theme.h' l='44' ll='93'/>
<use f='WebKit/Source/WebCore/platform/Theme.h' l='46' c='_ZN7WebCore5Theme9singletonEv'/>
<use f='WebKit/Source/WebCore/platform/Theme.h' l='91' c='_ZN7WebCore5ThemeC1ERKS0_'/>
<use f='WebKit/Source/WebCore/platform/Theme.h' l='92' c='_ZN7WebCore5ThemeaSERKS0_'/>
<ovr f='WebKit/Source/WebCore/platform/adwaita/ThemeAdwaita.h' l='36' c='WebCore::ThemeAdwaita'/>
<use f='WebKit/Source/WebCore/platform/adwaita/ThemeAdwaita.h' l='36'/>
<size>8</size>
<fun r='_ZN7WebCore5Theme9singletonEv'/>
<fun r='_ZNK7WebCore5Theme26baselinePositionAdjustmentENS_11ControlPartE'/>
<fun r='_ZNK7WebCore5Theme11controlFontENS_11ControlPartERKNS_11FontCascadeEf'/>
<fun r='_ZNK7WebCore5Theme11controlSizeENS_11ControlPartERKNS_11FontCascadeERKNS_10LengthSizeEf'/>
<fun r='_ZNK7WebCore5Theme18minimumControlSizeENS_11ControlPartERKNS_11FontCascadeERKNS_10LengthSizeES7_f'/>
<fun r='_ZNK7WebCore5Theme14controlPaddingENS_11ControlPartERKNS_11FontCascadeERKNS_9LengthBoxEf'/>
<fun r='_ZNK7WebCore5Theme13controlBorderENS_11ControlPartERKNS_11FontCascadeERKNS_9LengthBoxEf'/>
<fun r='_ZNK7WebCore5Theme28controlRequiresPreWhiteSpaceENS_11ControlPartE'/>
<fun r='_ZN7WebCore5Theme5paintENS_11ControlPartERNS_13ControlStatesERNS_15GraphicsContextERKNS_9FloatRectEfPNS_10ScrollViewEffbb'/>
<fun r='_ZNK7WebCore5Theme23inflateControlPaintRectENS_11ControlPartERKNS_13ControlStatesERNS_9FloatRectEf'/>
<fun r='_ZNK7WebCore5Theme14drawNamedImageERKN3WTF6StringERNS_15GraphicsContextERKNS_9FloatRectE'/>
<fun r='_ZNK7WebCore5Theme19userPrefersContrastEv'/>
<fun r='_ZNK7WebCore5Theme24userPrefersReducedMotionEv'/>
<fun r='_ZN7WebCore5ThemeC1Ev'/>
<fun r='_ZN7WebCore5ThemeD1Ev'/>
<fun r='_ZNK7WebCore5Theme18minimumControlSizeENS_11ControlPartERKNS_11FontCascadeERKNS_10LengthSizeEf'/>
<fun r='_ZN7WebCore5ThemeC1ERKS0_'/>
<fun r='_ZN7WebCore5ThemeaSERKS0_'/>
<use f='WebKit/Source/WebCore/platform/gtk/ThemeGtk.cpp' l='39' c='_ZN7WebCore5Theme9singletonEv'/>
<size>8</size>
<fun r='_ZN7WebCore5Theme9singletonEv'/>
