<dec f='WebKit/Source/WebCore/dom/ScriptElement.h' l='75' type='1'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.h' l='76' u='r' c='_ZNK7WebCore13ScriptElement10scriptTypeEv'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='166' u='a' c='_ZNK7WebCore13ScriptElement19determineScriptTypeENS0_17LegacyTypeSupportE'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='198' u='r' c='_ZN7WebCore13ScriptElement13prepareScriptERKN3WTF12TextPositionENS0_17LegacyTypeSupportE'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='248' u='r' c='_ZN7WebCore13ScriptElement13prepareScriptERKN3WTF12TextPositionENS0_17LegacyTypeSupportE'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='256' u='r' c='_ZN7WebCore13ScriptElement13prepareScriptERKN3WTF12TextPositionENS0_17LegacyTypeSupportE'/>
<use f='WebKit/Source/WebCore/dom/ScriptElement.cpp' l='260' u='r' c='_ZN7WebCore13ScriptElement13prepareScriptERKN3WTF12TextPositionENS0_17LegacyTypeSupportE'/>
