<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionEvent.h' l='37' ll='40'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionEvent.h' l='42' c='_ZN7WebCore22SpeechRecognitionEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionEvent.h' l='49' c='_ZN7WebCore22SpeechRecognitionEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>24</size>
<mbr r='WebCore::SpeechRecognitionEvent::Init::resultIndex' o='64' t='uint64_t'/>
<mbr r='WebCore::SpeechRecognitionEvent::Init::results' o='128' t='RefPtr&lt;WebCore::SpeechRecognitionResultList&gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.cpp' l='53' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSSpeechRecognitionEvent.cpp' l='181' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>24</size>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionEvent.cpp' l='36' c='_ZN7WebCore22SpeechRecognitionEvent6createERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/Modules/speech/SpeechRecognitionEvent.cpp' l='46' c='_ZN7WebCore22SpeechRecognitionEventC1ERKN3WTF10AtomStringEONS0_4InitENS_5Event9IsTrustedE'/>
<size>24</size>
