<def f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='61' ll='66'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='68' c='_ZN7WebCore14WillChangeData10addFeatureENS0_7FeatureENS_13CSSPropertyIDE'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='70'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='87' c='_ZNK7WebCore14WillChangeData17AnimatableFeature7featureEv'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='89' c='_ZNK7WebCore14WillChangeData17AnimatableFeature7featureEv'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.h' l='102' c='_ZN7WebCore14WillChangeData17AnimatableFeatureC1ENS0_7FeatureENS_13CSSPropertyIDE'/>
<use f='WebKit/Source/WebCore/rendering/style/WillChangeData.cpp' l='158' c='_ZN7WebCore14WillChangeData10addFeatureENS0_7FeatureENS_13CSSPropertyIDE'/>
