<dec f='WebKit/Source/WebCore/css/CSSSelector.h' l='68' type='1'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.h' l='534' u='r' c='_ZN7WebCore11CSSSelectorC1ERKS0_'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.h' l='557' u='r' c='_ZN7WebCore11CSSSelectorD1Ev'/>
<use f='WebKit/Source/WebCore/style/PageRuleCollector.cpp' l='97' u='r' c='_ZN7WebCore5StyleL27checkPageSelectorComponentsEPKNS_11CSSSelectorEbbRKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/style/RuleData.cpp' l='69' u='r' c='_ZN7WebCore5StyleL27computeMatchBasedOnRuleHashERKNS_11CSSSelectorE'/>
<use f='WebKit/Source/WebCore/style/RuleSet.cpp' l='128' c='_ZN7WebCore5Style7RuleSet7addRuleERKNS_9StyleRuleEjjPNS1_19MediaQueryCollectorE'/>
<use f='WebKit/Source/WebCore/css/SelectorChecker.cpp' l='572' c='_ZN7WebCoreL33canMatchHoverOrActiveInQuirksModeERKNS_15SelectorChecker12LocalContextE'/>
<use f='WebKit/Source/WebCore/css/SelectorChecker.cpp' l='637' u='r' c='_ZNK7WebCore15SelectorChecker8checkOneERNS0_15CheckingContextERKNS0_12LocalContextERNS0_9MatchTypeE'/>
<use f='WebKit/Source/WebCore/css/SelectorFilter.cpp' l='154' c='_ZN7WebCoreL25collectSimpleSelectorHashERNS_23CollectedSelectorHashesERKNS_11CSSSelectorE'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.cpp' l='56' u='r' c='_ZN7WebCore11CSSSelectorC1ERKNS_13QualifiedNameEb'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.cpp' l='146' c='_ZN7WebCoreL33simpleSelectorSpecificityInternalERKNS_11CSSSelectorE'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.cpp' l='201' c='_ZNK7WebCore11CSSSelector18specificityForPageEv'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.cpp' l='299' u='r' c='_ZNK7WebCore11CSSSelectoreqERKS0_'/>
<use f='WebKit/Source/WebCore/css/CSSSelector.cpp' l='382' u='r' c='_ZNK7WebCore11CSSSelector12selectorTextERKN3WTF6StringE'/>
<use f='WebKit/Source/WebCore/css/CSSSelectorList.cpp' l='155' u='r' c='_ZN7WebCore39SelectorNeedsNamespaceResolutionFunctorclEPKNS_11CSSSelectorE'/>
<use f='WebKit/Source/WebCore/cssjit/SelectorCompiler.cpp' l='1152' c='_ZN7WebCore16SelectorCompilerL26constructFragmentsInternalEPKNS_11CSSSelectorENS0_15SelectorContextERNS0_20SelectorFragmentListENS0_14FragmentsLevelEN1233249'/>
<use f='WebKit/Source/WebCore/dom/SelectorQuery.cpp' l='92' c='_ZN7WebCore16SelectorDataListC1ERKNS_15CSSSelectorListE'/>
