<inh f='WebKit/Source/WebCore/workers/service/ExtendableEventInit.h' l='34' c='WebCore::ExtendableEventInit'/>
<def f='WebKit/Source/WebCore/workers/service/ExtendableMessageEvent.h' l='53' ll='59'/>
<use f='WebKit/Source/WebCore/workers/service/ExtendableMessageEvent.h' l='61' c='_ZN7WebCore22ExtendableMessageEvent6createERN3JSC14JSGlobalObjectERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/workers/service/ExtendableMessageEvent.h' l='79' c='_ZN7WebCore22ExtendableMessageEventC1ERN3JSC14JSGlobalObjectERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSExtendableMessageEvent.h' l='90' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSExtendableMessageEvent.h' l='90' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>72</size>
<mbr r='WebCore::ExtendableMessageEvent::Init::data' o='64' t='JSC::JSValue'/>
<mbr r='WebCore::ExtendableMessageEvent::Init::origin' o='128' t='WTF::String'/>
<mbr r='WebCore::ExtendableMessageEvent::Init::lastEventId' o='192' t='WTF::String'/>
<mbr r='WebCore::ExtendableMessageEvent::Init::source' o='256' t='std::optional&lt;ExtendableMessageEventSource&gt;'/>
<mbr r='WebCore::ExtendableMessageEvent::Init::ports' o='448' t='Vector&lt;RefPtr&lt;WebCore::MessagePort&gt; &gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSExtendableMessageEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSExtendableMessageEvent.cpp' l='63' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSExtendableMessageEvent.cpp' l='73' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>72</size>
<use f='WebKit/Source/WebCore/bindings/js/JSExtendableMessageEventCustom.cpp' l='51' c='_ZN7WebCore33constructJSExtendableMessageEventEPN3JSC14JSGlobalObjectERNS0_9CallFrameE'/>
<size>72</size>
<use f='WebKit/Source/WebCore/workers/service/ExtendableMessageEvent.cpp' l='43' c='_ZN7WebCore22ExtendableMessageEventC1ERN3JSC14JSGlobalObjectERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>72</size>
