<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/ErrorEvent.h' l='55' ll='61'/>
<use f='WebKit/Source/WebCore/dom/ErrorEvent.h' l='63' c='_ZN7WebCore10ErrorEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/ErrorEvent.h' l='86' c='_ZN7WebCore10ErrorEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.h' l='83' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>40</size>
<mbr r='WebCore::ErrorEvent::Init::message' o='64' t='WTF::String'/>
<mbr r='WebCore::ErrorEvent::Init::filename' o='128' t='WTF::String'/>
<mbr r='WebCore::ErrorEvent::Init::lineno' o='192' t='unsigned int'/>
<mbr r='WebCore::ErrorEvent::Init::colno' o='224' t='unsigned int'/>
<mbr r='WebCore::ErrorEvent::Init::error' o='256' t='JSC::JSValue'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.cpp' l='52' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.cpp' l='62' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSErrorEvent.cpp' l='217' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>40</size>
<use f='WebKit/Source/WebCore/dom/ErrorEvent.cpp' l='46' c='_ZN7WebCore10ErrorEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>40</size>
