<dec f='WebKit/Source/WebCore/platform/Cursor.h' l='115' type='29'/>
<use f='WebKit/Source/WebCore/platform/Cursor.h' l='267'/>
<use f='WebKit/Source/WebCore/testing/Internals.cpp' l='3730' c='_ZN7WebCoreL18cursorTypeToStringENS_6Cursor4TypeE'/>
<use f='WebKit/Source/WebCore/platform/Cursor.cpp' l='117' c='_ZN7WebCore6Cursor8fromTypeENS0_4TypeE'/>
<use f='WebKit/Source/WebCore/platform/Cursor.cpp' l='203' u='a' c='_ZN7WebCore10moveCursorEv'/>
<use f='WebKit/Source/WebCore/platform/gtk/CursorGtk.cpp' l='101' c='_ZNK7WebCore6Cursor20ensurePlatformCursorEv'/>
