<inh f='WebKit/Source/WebCore/dom/EventInit.h' l='30' c='WebCore::EventInit'/>
<def f='WebKit/Source/WebCore/dom/OverflowEvent.h' l='51' ll='55'/>
<use f='WebKit/Source/WebCore/dom/OverflowEvent.h' l='57' c='_ZN7WebCore13OverflowEvent6createERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<use f='WebKit/Source/WebCore/dom/OverflowEvent.h' l='73' c='_ZN7WebCore13OverflowEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>8</size>
<mbr r='WebCore::OverflowEvent::Init::orient' o='32' t='unsigned short'/>
<mbr r='WebCore::OverflowEvent::Init::horizontalOverflow' o='48' t='bool'/>
<mbr r='WebCore::OverflowEvent::Init::verticalOverflow' o='56' t='bool'/>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>8</size>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.cpp' l='51' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.cpp' l='61' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSOverflowEvent.cpp' l='203' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>8</size>
<use f='WebKit/Source/WebCore/dom/OverflowEvent.cpp' l='58' c='_ZN7WebCore13OverflowEventC1ERKN3WTF10AtomStringERKNS0_4InitENS_5Event9IsTrustedE'/>
<size>8</size>
