<dec f='WebKit/Source/WebCore/rendering/style/RenderStyleConstants.h' l='921' type='16'/>
<use f='WebKit/Source/WebCore/rendering/style/RenderStyle.h' l='2358' u='r' c='_ZN7WebCore11RenderStyle20isDisplayFlexibleBoxENS_11DisplayTypeE'/>
<use f='WebKit/Source/WebCore/css/CSSPrimitiveValueMappings.h' l='1387' c='_ZN7WebCore17CSSPrimitiveValueC1ET_'/>
<use f='WebKit/Source/WebCore/rendering/style/RenderStyleConstants.cpp' l='453' c='_ZN7WebCorelsERN3WTF10TextStreamENS_11DisplayTypeE'/>
<use f='WebKit/Source/WebCore/rendering/RenderBlock.cpp' l='2882' u='r' c='_ZN7WebCore11RenderBlock39createAnonymousBlockWithStyleAndDisplayERNS_8DocumentERKNS_11RenderStyleENS_11DisplayTypeE'/>
<use f='WebKit/Source/WebCore/rendering/RenderBlock.cpp' l='2883' u='r' c='_ZN7WebCore11RenderBlock39createAnonymousBlockWithStyleAndDisplayERNS_8DocumentERKNS_11RenderStyleENS_11DisplayTypeE'/>
<use f='WebKit/Source/WebCore/rendering/RenderElement.cpp' l='178' c='_ZN7WebCore13RenderElement9createForERNS_7ElementEONS_11RenderStyleEN3WTF9OptionSetINS0_30ConstructBlockLevelRendererForEEE'/>
<use f='WebKit/Source/WebCore/rendering/RenderFullScreen.cpp' l='75' u='r' c='_ZN7WebCoreL21createFullScreenStyleEv'/>
<use f='WebKit/Source/WebCore/style/StyleAdjuster.cpp' l='104' c='_ZN7WebCore5StyleL22equivalentBlockDisplayERKNS_11RenderStyleERKNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/style/StyleAdjuster.cpp' l='119' u='r' c='_ZN7WebCore5StyleL22equivalentBlockDisplayERKNS_11RenderStyleERKNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/style/StyleAdjuster.cpp' l='629' u='r' c='_ZNK7WebCore5Style8Adjuster27adjustForSiteSpecificQuirksERNS_11RenderStyleE'/>
<use f='WebKit/Source/WebCore/html/HTMLButtonElement.cpp' l='67' u='r' c='_ZN7WebCore17HTMLButtonElement21createElementRendererEONS_11RenderStyleERKNS_18RenderTreePositionE'/>
