<def f='WebKit/Source/WebCore/page/IntersectionObserver.h' l='70' ll='74'/>
<use f='WebKit/Source/WebCore/page/IntersectionObserver.h' l='76' c='_ZN7WebCore20IntersectionObserver6createERNS_8DocumentEON3WTF3RefINS_28IntersectionObserverCallbackENS3_12RawPtrTraitsIS5_EEEEONS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.h' l='101' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.h' l='101' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>56</size>
<mbr r='WebCore::IntersectionObserver::Init::root' o='0' t='std::optional&lt;Variant&lt;RefPtr&lt;Element&gt;, RefPtr&lt;Document&gt; &gt; &gt;'/>
<mbr r='WebCore::IntersectionObserver::Init::rootMargin' o='192' t='WTF::String'/>
<mbr r='WebCore::IntersectionObserver::Init::threshold' o='256' t='Variant&lt;double, Vector&lt;double&gt; &gt;'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.cpp' l='72' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.cpp' l='72' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.cpp' l='82' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSIntersectionObserver.cpp' l='189' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>56</size>
<use f='WebKit/Source/WebCore/page/IntersectionObserver.cpp' l='88' c='_ZN7WebCore20IntersectionObserver6createERNS_8DocumentEON3WTF3RefINS_28IntersectionObserverCallbackENS3_12RawPtrTraitsIS5_EEEEONS0_4InitE'/>
<size>56</size>
<use f='WebKit/Source/WebCore/html/LazyLoadFrameObserver.cpp' l='95' c='_ZN7WebCore21LazyLoadFrameObserver20intersectionObserverERNS_8DocumentE'/>
<use f='WebKit/Source/WebCore/html/LazyLoadImageObserver.cpp' l='87' c='_ZN7WebCore21LazyLoadImageObserver20intersectionObserverERNS_8DocumentE'/>
<size>56</size>
