<inh f='WebKit/Source/WebCore/dom/UIEventInit.h' l='34' c='WebCore::UIEventInit'/>
<def f='WebKit/Source/WebCore/dom/CompositionEvent.h' l='46' ll='48'/>
<use f='WebKit/Source/WebCore/dom/CompositionEvent.h' l='50' c='_ZN7WebCore16CompositionEvent6createERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/Source/WebCore/dom/CompositionEvent.h' l='66' c='_ZN7WebCore16CompositionEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.h' l='79' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<size>32</size>
<mbr r='WebCore::CompositionEvent::Init::data' o='192' t='WTF::String'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.cpp' l='56' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.cpp' l='66' c='_ZN7WebCore17convertDictionaryERN3JSC14JSGlobalObjectENS0_7JSValueE'/>
<use f='WebKit/WebCore/DerivedSources/JSCompositionEvent.cpp' l='197' c='_ZN7WebCore16JSDOMConstructor9constructEPN3JSC14JSGlobalObjectEPNS1_9CallFrameE'/>
<size>32</size>
<use f='WebKit/Source/WebCore/dom/CompositionEvent.cpp' l='44' c='_ZN7WebCore16CompositionEventC1ERKN3WTF10AtomStringERKNS0_4InitE'/>
<size>32</size>
