<def f='WebKit/Source/WebDriver/WebDriverService.h' l='54' ll='58'/>
<use f='WebKit/Source/WebDriver/WebDriverService.h' l='59'/>
<size>32</size>
<mbr r='WebDriver::WebDriverService::Command::method' o='0' t='WebDriver::WebDriverService::HTTPMethod'/>
<mbr r='WebDriver::WebDriverService::Command::uriTemplate' o='64' t='const char *'/>
<mbr r='WebDriver::WebDriverService::Command::handler' o='128' t='WebDriver::WebDriverService::CommandHandler'/>
<use f='WebKit/Source/WebDriver/WebDriverService.cpp' l='145'/>
<size>32</size>
