<def f='WebKit/Source/WebKit/Platform/Module.h' l='46' ll='76'/>
<use f='WebKit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleC1ERKS0_'/>
<use f='WebKit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleaSERKS0_'/>
<use f='WebKit/Source/WebKit/Platform/Module.h' l='48' c='_ZN6WebKit6ModuleaSERKS0_'/>
<size>16</size>
<fun r='_ZN6WebKit6ModuleC1ERKS0_'/>
<fun r='_ZN6WebKit6ModuleC1ERKN3WTF6StringE'/>
<fun r='_ZN6WebKit6ModuleD1Ev'/>
<fun r='_ZN6WebKit6Module4loadEv'/>
<fun r='_ZN6WebKit6Module6unloadEv'/>
<fun r='_ZNK6WebKit6Module15functionPointerEPKc'/>
<fun r='_ZNK6WebKit6Module23platformFunctionPointerEPKc'/>
<mbr r='WebKit::Module::m_path' o='0' t='WTF::String'/>
<mbr r='WebKit::Module::m_handle' o='64' t='GModule *'/>
<fun r='_ZNK6WebKit6Module15functionPointerEPKc'/>
<fun r='_ZN6WebKit6Module4loadEv'/>
<fun r='_ZN6WebKit6Module6unloadEv'/>
<fun r='_ZNK6WebKit6Module23platformFunctionPointerEPKc'/>
<use f='WebKit/Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitExtensionManager.h' l='51' c='_ZN6WebKit22WebKitExtensionManager22initializeWebExtensionEPNS_6ModuleEP9_GVariant'/>
<use f='WebKit/Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitExtensionManager.h' l='53'/>
<size>16</size>
<use f='WebKit/Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitExtensionManager.cpp' l='74' c='_ZN6WebKit22WebKitExtensionManager22initializeWebExtensionEPNS_6ModuleEP9_GVariant'/>
<use f='WebKit/Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitExtensionManager.cpp' l='110' c='_ZN6WebKit22WebKitExtensionManager10initializeEPNS_14InjectedBundleEPN3API6ObjectE'/>
<size>16</size>
