<dec f='WebKit/Source/WTF/wtf/URLParser.cpp' l='632' type='0'/>
<use f='WebKit/Source/WTF/wtf/URLParser.cpp' l='685' u='r' c='_ZN3WTFL6schemeENS_10StringViewE'/>
<use f='WebKit/Source/WTF/wtf/URLParser.cpp' l='817' c='_ZN3WTF9URLParser17copyURLPartsUntilERKNS_3URLENS0_7URLPartERKNS_17CodePointIteratorIT_EERPKNS_15URLTextEncodingE'/>
<use f='WebKit/Source/WTF/wtf/URLParser.cpp' l='1200' c='_ZN3WTF9URLParser5parseEPKT_jRKNS_3URLEPKNS_15URLTextEncodingE'/>
